### ISSUE TITLE
TypeError: unhashable type: 'list'

### ISSUE THREAD

**Issue by khasni** [dask/distributed#8349] opened 2023-11-15 13:26 UTC
**Describe the issue**:
Dear all. I have an issue when using the code smallbaselineApp.py in opensarlab
**Minimal Complete Verifiable Example**:
------- start parallel processing using Dask -------
input Dask cluster type: local
initiate Dask cluster
Traceback (most recent call last):
  File "/home/jovyan/.local/envs/osl_mintpy/bin/smallbaselineApp.py", line 10, in <module>
    sys.exit(main())
  File "/home/jovyan/.local/envs/osl_mintpy/lib/python3.9/site-packages/mintpy/cli/smallbaselineApp.py", line 208, in main
    run_smallbaselineApp(inps)
  File "/home/jovyan/.local/envs/osl_mintpy/lib/python3.9/site-packages/mintpy/smallbaselineApp.py", line 1117, in run_smallbaselineApp
    app.run(steps=inps.runSteps)
  File "/home/jovyan/.local/envs/osl_mintpy/lib/python3.9/site-packages/mintpy/smallbaselineApp.py", line 889, in run
    self.run_network_inversion(sname)
  File "/home/jovyan/.local/envs/osl_mintpy/lib/python3.9/site-packages/mintpy/smallbaselineApp.py", line 384, in run_network_inversion
    mintpy.cli.ifgram_inversion.main(iargs)
  File "/home/jovyan/.local/envs/osl_mintpy/lib/python3.9/site-packages/mintpy/cli/ifgram_inversion.py", line 257, in main
    run_ifgram_inversion(inps)
  File "/home/jovyan/.local/envs/osl_mintpy/lib/python3.9/site-packages/mintpy/ifgram_inversion.py", line 1112, in run_ifgram_inversion
    cluster_obj.open()
  File "/home/jovyan/.local/envs/osl_mintpy/lib/python3.9/site-packages/mintpy/objects/cluster.py", line 182, in open
    from dask.distributed import LocalCluster
  File "/home/jovyan/.local/envs/osl_mintpy/lib/python3.9/site-packages/dask/distributed.py", line 13, in <module>
    from distributed import *
  File "/home/jovyan/.local/envs/osl_mintpy/lib/python3.9/site-packages/distributed/__init__.py", line 23, in <module>
    from distributed.actor import Actor, ActorFuture, BaseActorFuture
  File "/home/jovyan/.local/envs/osl_mintpy/lib/python3.9/site-packages/distributed/actor.py", line 13, in <module>
    from distributed.client import Future
  File "/home/jovyan/.local/envs/osl_mintpy/lib/python3.9/site-packages/distributed/client.py", line 116, in <module>
    from distributed.worker import get_client, get_worker, secede
  File "/home/jovyan/.local/envs/osl_mintpy/lib/python3.9/site-packages/distributed/worker.py", line 119, in <module>
    from distributed.worker_memory import (
  File "/home/jovyan/.local/envs/osl_mintpy/lib/python3.9/site-packages/distributed/worker_memory.py", line 55, in <module>
    WorkerDataParameter: TypeAlias = Union[
  File "/home/jovyan/.local/envs/osl_mintpy/lib/python3.9/typing.py", line 243, in inner
    return func(*args, **kwds)
  File "/home/jovyan/.local/envs/osl_mintpy/lib/python3.9/typing.py", line 316, in __getitem__
    return self._getitem(self, parameters)
  File "/home/jovyan/.local/envs/osl_mintpy/lib/python3.9/typing.py", line 421, in Union
    parameters = _remove_dups_flatten(parameters)
  File "/home/jovyan/.local/envs/osl_mintpy/lib/python3.9/typing.py", line 215, in _remove_dups_flatten
    all_params = set(params)
TypeError: unhashable type: 'list'

```python
# Put your MCVE code here
```

**Anything else we need to know?**:

**Environment**:

- Dask version:
- Python version:
- Operating System:
- Install method (conda, pip, source):

**Comment by jrbourbeau** [comment] 2023-11-15 16:49
It looks like this is a duplicate of https://github.com/dask/distributed/issues/7956. I'd recommend upgrading to Python 3.9.2+. Feel free to re-open if this isn't a duplicate of https://github.com/dask/distributed/issues/7956

**Closed by jrbourbeau** 2023-11-15 16:49 UTC
Labels: needs triage
