### ISSUE TITLE
shuffle_transfer failed during shuffle

### ISSUE THREAD

**Issue by b-y-f** [dask/distributed#7613] opened 2023-03-03 03:31 UTC
I think this should be distributed issue
https://github.com/dask/distributed/issues/7615

And the original problem raised here:https://github.com/blue-yonder/tsfresh/issues/1007

**Comment by fjetter** [comment] 2023-03-03 09:16
duplicate of https://github.com/dask/distributed/issues/7615

**Closed by fjetter** 2023-03-03 09:16 UTC
