### ISSUE TITLE
Bokeh 0.12.6 incompatibility for scheduler on some systems

### ISSUE THREAD

**Issue by MathMagique** [dask/distributed#1193] opened 2017-06-20 14:59 UTC
Hi there! I have a virtual environment with the following contents:
```
> pip freeze
backports-abc==0.5
bkcharts==0.2
bokeh==0.12.6           <--------------
boto3==1.4.4
botocore==1.5.71
certifi==2017.4.17
chardet==3.0.4
click==6.7
cloudpickle==0.3.1
dask==0.15.0            <--------------
distributed==1.17.1     <--------------
docutils==0.13.1
futures==3.1.1
graphviz==0.7.1
HeapDict==1.0.0
idna==2.5
Jinja2==2.9.6
jmespath==0.9.3
locket==0.2.0
MarkupSafe==1.0
msgpack-python==0.4.8
numpy==1.13.0
pandas==0.20.2
partd==0.3.8
psutil==5.2.2
python-dateutil==2.6.0
pytz==2017.2
PyYAML==3.12
requests==2.18.1
s3fs==0.1.1
s3transfer==0.1.10
singledispatch==3.4.0.3
six==1.10.0
sortedcontainers==1.5.7
tblib==1.3.2
toolz==0.8.2
tornado==4.5.1
urllib3==1.21.1
zict==0.1.2
```
When I try to start the scheduler, I get the following output:
```
> dask-scheduler
distributed.scheduler - INFO - -----------------------------------------------
distributed.scheduler - INFO - Could not launch service: ('bokeh', 8787)
Traceback (most recent call last):
  File "/home/vagrant/dask_venv/local/lib/python2.7/site-packages/distributed/scheduler.py", line 404, in start_services
    service = v(self, io_loop=self.loop)
  File "/home/vagrant/dask_venv/local/lib/python2.7/site-packages/distributed/bokeh/scheduler.py", line 995, in __init__
    scheduler)))
  File "/home/vagrant/dask_venv/local/lib/python2.7/site-packages/bokeh/application/handlers/function.py", line 11, in __init__
    _check_callback(func, ('doc',))
  File "/home/vagrant/dask_venv/local/lib/python2.7/site-packages/bokeh/util/callback_manager.py", line 12, in _check_callback
    sig = signature(callback)
  File "/home/vagrant/dask_venv/local/lib/python2.7/site-packages/bokeh/util/future.py", line 85, in signature
    for name in func.keywords.keys():
AttributeError: 'NoneType' object has no attribute 'keys'
distributed.scheduler - INFO -   Scheduler at:      tcp://10.0.2.15:8786
distributed.scheduler - INFO -        http at:              0.0.0.0:9786
distributed.scheduler - INFO - Local Directory:      /tmp/scheduler-zmXtOf
distributed.scheduler - INFO - -----------------------------------------------
^Cdistributed.scheduler - INFO - End scheduler at 'tcp://:8786'
```
I can fix this problem by downgrading Bokeh to 0.12.5:
```
> pip install -U bokeh==0.12.5
...
Installing collected packages: bokeh
  Found existing installation: bokeh 0.12.6
    Uninstalling bokeh-0.12.6:
      Successfully uninstalled bokeh-0.12.6
  Running setup.py install for bokeh ... done
Successfully installed bokeh-0.12.5

> dask-scheduler
distributed.scheduler - INFO - -----------------------------------------------
distributed.scheduler - INFO -   Scheduler at:      tcp://10.0.2.15:8786
distributed.scheduler - INFO -       bokeh at:              0.0.0.0:8787
distributed.scheduler - INFO -        http at:              0.0.0.0:9786
distributed.scheduler - INFO - Local Directory:      /tmp/scheduler-U0qy1k
distributed.scheduler - INFO - -----------------------------------------------
^Cdistributed.scheduler - INFO - End scheduler at 'tcp://:8786'
```

I was able to reproduce the issue on my Debian 8 machine with Python 2.7.9. The error does _not_ occur on my Mac with Python 2.7.11.

**Comment by pitrou** [comment] 2017-06-20 15:48
I can't reproduce with Python 2.7.12. You may want to [report an issue at Bokeh](https://github.com/bokeh/bokeh/issues) instead, since it seems it became incompatible with Python 2.7.9.

**Comment by MathMagique** [comment] 2017-06-21 07:00
Thanks for checking! I cross-posted the issue in the Bokeh issue tracker.

**Comment by pitrou** [comment] 2017-06-21 19:29
Since this isn't a Distributed issue, I'm closing.

**Closed by pitrou** 2017-06-21 19:29 UTC
