### ISSUE TITLE
Python2 / macOS

### ISSUE THREAD

**Issue by natekupp** [dask/distributed#2776] opened 2019-06-17 18:31 UTC
Is Python 2 no longer supported?  My env:

- macOS Mojave 10.14.5
- Python 2.7.15 
- dask 1.2.2 
- distributed 1.28.1

And the following hangs forever for me:

```
import dask.distributed
client = dask.distributed.Client()
```

Doing a Ctrl+C, seems like it's stuck in a wait loop:

```
/Users/nate/.pyenv/versions/2.7.15/envs/dagster-2.7.15/lib/python2.7/site-packages/distributed/client.pyc in __init__(self, address, loop, timeout, set_as_default, scheduler_file, security, asynchronous, name, heartbeat_interval, serializers, deserializers, extensions, direct_to_workers, **kwargs)
    710             ext(self)
    711
--> 712         self.start(timeout=timeout)
    713
    714         from distributed.recreate_exceptions import ReplayExceptionClient

/Users/nate/.pyenv/versions/2.7.15/envs/dagster-2.7.15/lib/python2.7/site-packages/distributed/client.pyc in start(self, **kwargs)
    856             self._started = self._start(**kwargs)
    857         else:
--> 858             sync(self.loop, self._start, **kwargs)
    859
    860     def __await__(self):

/Users/nate/.pyenv/versions/2.7.15/envs/dagster-2.7.15/lib/python2.7/site-packages/distributed/utils.pyc in sync(loop, func, *args, **kwargs)
    327     else:
    328         while not e.is_set():
--> 329             e.wait(10)
    330     if error[0]:
    331         six.reraise(*error[0])

/Users/nate/.pyenv/versions/2.7.15/lib/python2.7/threading.pyc in wait(self, timeout)
    612         with self.__cond:
    613             if not self.__flag:
--> 614                 self.__cond.wait(timeout)
    615             return self.__flag
    616

/Users/nate/.pyenv/versions/2.7.15/lib/python2.7/threading.pyc in wait(self, timeout)
    357                         break
    358                     delay = min(delay * 2, remaining, .05)
--> 359                     _sleep(delay)
    360                 if not gotit:
    361                     if __debug__:
```

**Comment by TomAugspurger** [comment] 2019-06-17 18:35
Master is python-3 only, but 1.28.1 should support python 2.7.

**Comment by natekupp** [comment] 2019-06-17 18:41
Anything else I can try to help debug further? We're attempting to hold on to supporting Python 2 for a little while longer if possible

**Comment by TomAugspurger** [comment] 2019-06-17 18:42
Does it work with older versions of distributed?

**Comment by natekupp** [comment] 2019-06-17 18:49
I just did a `pip install dask==0.18.0 distributed==1.22.0` in a clean pyenv/virtualenv and getting the same behavior

**Comment by TomAugspurger** [comment] 2019-06-17 18:53
Hmm, are you doing this in IPython / the regular REPL / a script? If you put that under an `if __name__ == '__main__'` block, do things work?

**Comment by natekupp** [comment] 2019-06-17 18:57
yep I was, but putting this in a `test.py` gets the same:

```
import dask.distributed

def run():
    client = dask.distributed.Client()

if __name__ == '__main__':
    run()
```

**Comment by mrocklin** [comment] 2019-06-30 10:20
I'm unable to reproduce

```
conda create -n gh2776 python=2 dask-core=1.2.2 distributed=1.28.1

The following NEW packages will be INSTALLED:

  backports_abc      pkgs/main/noarch::backports_abc-0.5-py_0
  certifi            pkgs/main/osx-64::certifi-2019.6.16-py27_0
  click              pkgs/main/osx-64::click-7.0-py27_0
  cloudpickle        pkgs/main/noarch::cloudpickle-1.1.1-py_0
  cytoolz            pkgs/main/osx-64::cytoolz-0.9.0.1-py27h1de35cc_1
  dask-core          pkgs/main/noarch::dask-core-1.2.2-py_0
  distributed        pkgs/main/osx-64::distributed-1.28.1-py27_0
  futures            pkgs/main/osx-64::futures-3.2.0-py27_0
  heapdict           pkgs/main/osx-64::heapdict-1.0.0-py27_2
  libcxx             pkgs/main/osx-64::libcxx-4.0.1-hcfea43d_1
  libcxxabi          pkgs/main/osx-64::libcxxabi-4.0.1-hcfea43d_1
  libedit            pkgs/main/osx-64::libedit-3.1.20181209-hb402a30_0
  libffi             pkgs/main/osx-64::libffi-3.2.1-h475c297_4
  msgpack-python     pkgs/main/osx-64::msgpack-python-0.6.1-py27h04f5b5a_1
  ncurses            pkgs/main/osx-64::ncurses-6.1-h0a44026_1
  pip                pkgs/main/osx-64::pip-19.1.1-py27_0
  psutil             pkgs/main/osx-64::psutil-5.6.2-py27h1de35cc_0
  python             pkgs/main/osx-64::python-2.7.16-h97142e2_0
  pyyaml             pkgs/main/osx-64::pyyaml-5.1-py27h1de35cc_0
  readline           pkgs/main/osx-64::readline-7.0-h1de35cc_5
  setuptools         pkgs/main/osx-64::setuptools-41.0.1-py27_0
  singledispatch     pkgs/main/osx-64::singledispatch-3.4.0.3-py27he22c18d_0
  six                pkgs/main/osx-64::six-1.12.0-py27_0
  sortedcontainers   pkgs/main/osx-64::sortedcontainers-2.1.0-py27_0
  sqlite             pkgs/main/osx-64::sqlite-3.28.0-ha441bb4_0
  tblib              pkgs/main/noarch::tblib-1.4.0-py_0
  tk                 pkgs/main/osx-64::tk-8.6.8-ha441bb4_0
  toolz              pkgs/main/osx-64::toolz-0.9.0-py27_0
  tornado            pkgs/main/osx-64::tornado-5.1.1-py27h1de35cc_0
  wheel              pkgs/main/osx-64::wheel-0.33.4-py27_0
  yaml               pkgs/main/osx-64::yaml-0.1.7-hc338f04_2
  zict               pkgs/main/osx-64::zict-0.1.4-py27_0
  zlib               pkgs/main/osx-64::zlib-1.2.11-h1de35cc_3
```

```
$ python
Python 2.7.16 |Anaconda, Inc.| (default, Mar 14 2019, 16:24:02)
[GCC 4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import dask.distributed
>>> client = dask.distributed.Client()
>>> client
<Client: scheduler='tcp://127.0.0.1:50695' processes=4 cores=12>
>>> import sys
>>> sys.platform
'darwin'
```

**Comment by natekupp** [comment] 2019-07-01 18:57
@mrocklin hmm, are you on Mojave? I'm on 10.14.5; a coworker is on 10.14.3 and he can also reproduce this issue. wonder if something's changed w/ Mojave

**Comment by TomAugspurger** [comment] 2019-07-01 19:03
Strange. I'm able to do

```
from distributed import Client

client = Client()
```

but `client = dask.distributed.Client()` hangs. Also on MacOS 10.14.5

**Comment by TomAugspurger** [comment] 2019-07-01 19:07
Nevermind, both seem to be non-deterministic :/ It seems to work about 1/4 or 1/5 of the time, hang otherwise.

**Comment by mrocklin** [comment] 2019-07-01 19:59
Oh, yeah, Python 2 has some issues with forking off processes.  This was
one of the reasons that pushed us away from Python 2.

**Comment by natekupp** [comment] 2019-07-01 21:01
@TomAugspurger yeah no worries, and thanks for the digging thus far! I've definitely seen a bit of that non-deterministic behavior in some of our downstream tests on py2.

It's fine by me if you guys want to just won't-fix this issue and mark dask distributed as not supported on py2—downstream, we're still building our core on both py2/py3, but we've already marked our Dask integration as py3 only. I wanted to flag in case there was interest in further investigation to get py2 working on your end.

Thoughts?

**Comment by mrocklin** [comment] 2019-07-01 21:07
My recollection was that some of the processes just wouldn't start properly
in Python 2.  I don't recall why.  If anyone wanted to fix this that would
be welcome, I personally am unlikely to spend time on it though.

**Comment by jrbourbeau** [comment] 2020-04-07 21:36
Closing this issue as we dropped Python 2 support almost a year ago, so I suspect this issue is less relevant today

**Closed by jrbourbeau** 2020-04-07 21:36 UTC
