### ISSUE TITLE
Server node tried to pass kwargs to object

### ISSUE THREAD

**Issue by jacobtomlinson** [dask/distributed#4788] opened 2021-05-06 13:54 UTC
While debugging an issue in dask-cloudprovider I noticed that `distributed.core.Server` tries to pass any remaining kwargs to `object` which doesn't take any kwargs.

https://github.com/dask/distributed/blob/7bfd1ae202bb973aea36da0e0d41a7377d2a47ab/distributed/core.py#L241

This came about from `dask-spec` being given kwargs which do not exist in `distributed.Worker`.

**Comment by jrbourbeau** [comment] 2021-05-06 14:44
Thanks for reporting @jacobtomlinson! Closing as a duplicate of https://github.com/dask/distributed/issues/4640

**Closed by jrbourbeau** 2021-05-06 14:44 UTC
