### ISSUE TITLE
KeyError during replication

### ISSUE THREAD

**Issue by mdering** [dask/distributed#3990] opened 2020-07-27 14:09 UTC
**What happened**:
I'm implementing a distributed system that has pretty active replication logic, as well as a good amount of workers starting and stopping. Currently I have a method that replicates specific futures that hold valuable intermediate results. However, during this, it seems like a keyerror can occur when a worker goes down during the replication process. I think this is because a worker is retired in the middle of this process (probably due to high memory usage). 

```ERROR - 2020-07-27 09:47:19 - distributed.core.handle_comm.l519 - <Worker 'tcp://172.29.0.4:3031', name: worker-31, memory: 168, processing: 11>
Traceback (most recent call last):
File "/opt/conda/envs/env/lib/python3.7/site-packages/distributed/core.py", line 513, in handle_comm
result = await result
File "/opt/conda/envs/env/lib/python3.7/site-packages/distributed/scheduler.py", line 3255, in replicate
for ws, tasks in del_worker_tasks.items()
File "/opt/conda/envs/env/lib/python3.7/site-packages/distributed/scheduler.py", line 3064, in _delete_worker_data
 ts.who_has.remove(ws)
```
is there any reason why this error can't be caught and ignored?

**What you expected to happen**:
I would expect this not to happen.
**Minimal Complete Verifiable Example**:
Sorry, I don't really have this, but maybe we could force it by allocating a lot of memory on workers and calling replicate on them?

**Comment by quasiben** [comment] 2020-07-28 14:49
I don't see what the error is in the post above.  I only see a few lines of the traceback of where the error occurred. How are you replicating futures ?

**Comment by jakirkham** [comment] 2020-07-31 17:18
Any updates here, @mdering? We probably need some more info here to be helpful 🙂

**Comment by mdering** [comment] 2020-07-31 19:04
I think this has to do with the replication during a worker shutdown. We're currently using workers who cycle in and out pretty regularly due to high memory use, specifically i think this surfaced during a replication-stimulated delete of a future off of a worker that was shutting down. Once I altered the code to only replicate the futures that were only on < n workers, this issue went away. I thought a stack trace would be helpful here. I'm sorry I can't provide more info but this feels like something the library should be able to handle

**Comment by jakirkham** [comment] 2020-07-31 19:46
My only suggestion at this point would be to cutdown on the amount of memory in each task (if possible). Like working with a smaller amount of data and possibly optimizing functions within tasks to have a lower memory footprint (working in-place is often useful). We do try to spill memory (we know about) to disk based on periodic polling of system memory. The OS can also do this itself. That said, there are practical limits on these. So being mindful of memory usage in tasks remains important.

**Comment by mdering** [comment] 2020-07-31 19:50
sure, I get that but we have some leaky code somewhere (I think), and for testing are keeping memory limits low. We had been doing periodic restarts as well and may return to this. I know that having workers enter and exit should be pretty graceful, but this might be liable to happen in adaptive cluster settings as well.

**Comment by jakirkham** [comment] 2020-07-31 20:09
Are there particular kinds of functions that seem to get high memory usage?

That's a fair point and sounds like something worth focusing on. I wonder if we might be able to come up with some cases where the adaptive cluster doesn't communicate data well before closing workers down.

**Comment by mdering** [comment] 2020-07-31 20:35
I'm not sure. It wouldn't surprise me if we have a little memory leak too. Either way its not memory thats managed by dask and were happy enough to let workers enter and exit whenever, but it does seem to cause strange issues in strange places. Replicate through a comms error because it was trying to replicate to a worker that went down. We're also seeing issues like https://github.com/dask/distributed/issues/4001 as well.

**Comment by jakirkham** [comment] 2020-07-31 21:53
Always a possibility.

Running through the code with [`tracemalloc`]( https://docs.python.org/3/library/tracemalloc.html ) can be a useful exercise. If NumPy is involved, it uses [its own domain]( https://numpy.org/doc/stable/release/1.13.0-notes.html#support-for-tracemalloc-in-python-3-6 ), which can be useful to filter out unrelated allocations. Another useful tool is [memprof]( https://jmdana.github.io/memprof/ ), which is like [`line_profiler`]( https://github.com/pyutils/line_profiler ) with memory.

Is it possible some of this memory that is unknown to Dask doesn't serialize between workers? If so, it might be worth figuring out a way to graduate this into Python somehow so that Dask can get a handle on it. Just another thought 🙂

Should add it's still possible there is a bug in adaptive as well. Just trying to give some ideas as to where one might look further.

**Comment by mrocklin** [comment] 2020-07-31 21:59
Replicate isn't super robust.  That and rebalance both have consistency
issues and should only be fully trusted when the cluster is in a quiet
state.  They *may *still work in an active state, but the code there isn't
bullet proof.  Long-term I think that the solution to this is to rework
active memory management.  In the meantime if people want to jump into the
replicate code with patches that would be welcome, but it may be a
moderately large effort.

**Comment by crusaderky** [comment] 2022-06-15 09:40
Closing as a duplicate of #6578

**Closed by crusaderky** 2022-06-15 09:40 UTC
Labels: stability, memory
