### ISSUE TITLE
Issue with Client()

### ISSUE THREAD

**Issue by timhdesilva** [dask/distributed#4846] opened 2021-05-24 23:39 UTC
Hi,

Sorry to raise another issue, but I just ran into an additional problem. When I execute the following code, I get a bunch of error messages below and the code never finishes running. 
```
import pandas as pd
from dask import dataframe as dd
from dask.distributed import Client
client = Client()
```

Error message printed to console many times:

```
Task exception was never retrieved
future: <Task finished name='Task-13' coro=<_wrap_awaitable() done, defined at C:\Users\tdesilva\Anaconda3\lib\asyncio\tasks.py:688> exception=RuntimeError('\n        An attempt has been made to start a new process before the\n        current process has finished its bootstrapping phase.\n\n        This probably means that you are not using fork to start your\n        child processes and you have forgotten to use the proper idiom\n        in the main module:\n\n            if __name__ == \'__main__\':\n                freeze_support()\n                ...\n\n        The "freeze_support()" line can be omitted if the program\n        is not going to be frozen to produce an executable.')>
Traceback (most recent call last):
  File "C:\Users\tdesilva\Anaconda3\lib\asyncio\tasks.py", line 695, in _wrap_awaitable
    return (yield from awaitable.__await__())
  File "C:\Users\tdesilva\Anaconda3\lib\site-packages\distributed\core.py", line 284, in _
    await self.start()
  File "C:\Users\tdesilva\Anaconda3\lib\site-packages\distributed\nanny.py", line 295, in start
    response = await self.instantiate()
  File "C:\Users\tdesilva\Anaconda3\lib\site-packages\distributed\nanny.py", line 378, in instantiate
    result = await self.process.start()
  File "C:\Users\tdesilva\Anaconda3\lib\site-packages\distributed\nanny.py", line 575, in start
    await self.process.start()
  File "C:\Users\tdesilva\Anaconda3\lib\site-packages\distributed\process.py", line 33, in _call_and_set_future
    res = func(*args, **kwargs)
  File "C:\Users\tdesilva\Anaconda3\lib\site-packages\distributed\process.py", line 203, in _start
    process.start()
  File "C:\Users\tdesilva\Anaconda3\lib\multiprocessing\process.py", line 121, in start
    self._popen = self._Popen(self)
  File "C:\Users\tdesilva\Anaconda3\lib\multiprocessing\context.py", line 224, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "C:\Users\tdesilva\Anaconda3\lib\multiprocessing\context.py", line 327, in _Popen
    return Popen(process_obj)
  File "C:\Users\tdesilva\Anaconda3\lib\multiprocessing\popen_spawn_win32.py", line 45, in __init__
    prep_data = spawn.get_preparation_data(process_obj._name)
  File "C:\Users\tdesilva\Anaconda3\lib\multiprocessing\spawn.py", line 154, in get_preparation_data
    _check_not_importing_main()
  File "C:\Users\tdesilva\Anaconda3\lib\multiprocessing\spawn.py", line 134, in _check_not_importing_main
    raise RuntimeError('''
RuntimeError: 
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.

```

As additional information, if I remove ``client = Client()``, the code runs with no issues.

Thanks so much for all the help!

**Comment by jrbourbeau** [comment] 2021-05-25 01:02
You can put your code inside a `if __name__ == "__main__"` block like so:

```python
from dask.distributed import Client

if __name__ == "__main__":
    client = Client()
```

Closing as a duplicate of https://github.com/dask/distributed/issues/2520 (which includes more background information about the underlying cause of this `RuntimeError`)

**Closed by jrbourbeau** 2021-05-25 01:02 UTC

**Comment by timhdesilva** [comment] 2021-05-25 02:06
Great, that works perfectly, thank you!
