### ISSUE TITLE
Order tests failing regularly

### ISSUE THREAD

**Issue by mrocklin** [dask/distributed#8296] opened 2023-10-21 14:33 UTC
`test_decide_worker_coschedule_order_neighbors_`

<img width="297" alt="Screenshot 2023-10-21 at 9 33 14 AM" src="https://github.com/dask/distributed/assets/306380/21261570-50b2-4c25-bf93-263dff8cb6e6">

https://github.com/dask/distributed/actions/runs/6573936698/job/17857964890?pr=8290

cc @fjetter

**Comment by jrbourbeau** [comment] 2023-10-23 14:59
Closing as a duplicate of https://github.com/dask/distributed/issues/8255

**Closed by jrbourbeau** 2023-10-23 14:58 UTC
Labels: needs triage
