### ISSUE TITLE
working with data that cannot be pickled?

### ISSUE THREAD

**Issue by davideps** [dask/distributed#3396] opened 2020-01-21 20:43 UTC
I'd like to use dask tasks or actors to interact with a Grakn database. Grakn uses gRPC objects as its transaction handles. You open a transaction, submit queries, then commit the transaction. These objects cannot be pickled. All ways I've tried to use these objects with dask result in errors like:
````
grpc._cython.cygrpc.Channel.__reduce_cython__
TypeError: no default __reduce__ due to non-trivial __cinit__
````
Is there any way to use gRPC objects with dask?

**Comment by TomAugspurger** [comment] 2020-01-21 20:53
Is this different from https://github.com/dask/distributed/issues/3393? As I say there, you can register custom serializers.

**Comment by jrbourbeau** [comment] 2020-01-22 01:53
Closing as a duplicate of https://github.com/dask/distributed/issues/3393. @davideps as @TomAugspurger  mentioned, I'd recommend engaging with the grakn project to see if there is a way to pickle their objects. Otherwise, you can register your own custom serializer using `distributed`'s extension points (see https://distributed.dask.org/en/latest/serialization.html)

**Closed by jrbourbeau** 2020-01-22 01:53 UTC

**Comment by davideps** [comment] 2020-01-22 05:49
@TomAugspurger, my mistake. Thank you for your input.
