### ISSUE TITLE
Scheduler crashes in SSHCluster in 2023.3.2 but not in 2023.3.1

### ISSUE THREAD

**Issue by jabbera** [dask/distributed#7724] opened 2023-03-29 18:31 UTC
**Describe the issue**: Attempting to use the SSHCluster does not work in 2023.3.2 because the scheduler exits early with an exit code of 1

```
INFO:distributed.deploy.ssh:2023-03-29 18:21:07,199 - distributed.http.proxy - INFO - To route to workers diagnostics web server please install jupyter-server-proxy: python -m pip install jupyter-server-proxy
2023-03-29 18:21:07,204 - distributed.deploy.ssh - INFO - 2023-03-29 18:21:07,204 - distributed.scheduler - INFO - State start
INFO:distributed.deploy.ssh:2023-03-29 18:21:07,204 - distributed.scheduler - INFO - State start
2023-03-29 18:21:07,207 - distributed.deploy.ssh - INFO - 2023-03-29 18:21:07,206 - distributed.scheduler - DEBUG - Clear task state
INFO:distributed.deploy.ssh:2023-03-29 18:21:07,206 - distributed.scheduler - DEBUG - Clear task state
2023-03-29 18:21:07,207 - distributed.deploy.ssh - INFO - 2023-03-29 18:21:07,207 - distributed.scheduler - INFO -   Scheduler at:   tcp://10.15.40.68:36143
INFO:distributed.deploy.ssh:2023-03-29 18:21:07,207 - distributed.scheduler - INFO -   Scheduler at:   tcp://10.15.40.68:36143
INFO:asyncssh:[conn=0, chan=1] Received exit status 1
INFO:asyncssh:[conn=0, chan=1] Received channel close
INFO:asyncssh:[conn=0, chan=1] Channel closed
INFO:asyncssh:[conn=0, chan=1] Sending KILL signal
```

When rolling back to 2023.3.1 the scheduler starts sucessfully:

```
2023-03-29 18:23:33,874 - distributed.deploy.ssh - INFO - 2023-03-29 18:23:33,873 - distributed.http.proxy - INFO - To route to workers diagnostics web server please install jupyter-server-proxy: python -m pip install jupyter-server-proxy
INFO:distributed.deploy.ssh:2023-03-29 18:23:33,873 - distributed.http.proxy - INFO - To route to workers diagnostics web server please install jupyter-server-proxy: python -m pip install jupyter-server-proxy
2023-03-29 18:23:33,878 - distributed.deploy.ssh - INFO - 2023-03-29 18:23:33,878 - distributed.scheduler - INFO - State start
INFO:distributed.deploy.ssh:2023-03-29 18:23:33,878 - distributed.scheduler - INFO - State start
2023-03-29 18:23:33,882 - distributed.deploy.ssh - INFO - 2023-03-29 18:23:33,881 - distributed.scheduler - DEBUG - Clear task state
INFO:distributed.deploy.ssh:2023-03-29 18:23:33,881 - distributed.scheduler - DEBUG - Clear task state
2023-03-29 18:23:33,883 - distributed.deploy.ssh - INFO - 2023-03-29 18:23:33,882 - distributed.scheduler - INFO -   Scheduler at:   tcp://10.15.40.68:40305
INFO:distributed.deploy.ssh:2023-03-29 18:23:33,882 - distributed.scheduler - INFO -   Scheduler at:   tcp://10.15.40.68:40305
INFO:asyncssh:Opening SSH connection to localhost, port 22
INFO:asyncssh:[conn=1] Connected to SSH server at localhost, port 22
```

**Minimal Complete Verifiable Example**:

```python
import logging
logging.basicConfig(level=logging.DEBUG)

from distributed import SSHCluster
cluster = SSHCluster(["localhost", "localhost"])
```

**Anything else we need to know?**: Full repro here:
```
git clone https://github.com/jabbera/distributed-bug.git
cd distributed-bug
python3.10 -m venv .venv
source .venv/bin/activate
pip install -r requirements-bug.txt
python demo.py
```

**Environment**:

- Dask version: 2023.3.2
- Python version: 3.10.5
- Operating System: Ubuntu 20.04.5 LTS
- Install method (conda, pip, source): pip

**Comment by jabbera** [comment] 2023-03-29 18:42
Rolling this back sorts the issue: https://github.com/dask/distributed/pull/7631

**Comment by jrbourbeau** [comment] 2023-03-29 22:06
cc @milesgranger @jacobtomlinson for visibility

**Comment by jabbera** [comment] 2023-03-29 22:57
I did a little more digging and the crash happens somewhere in here: https://github.com/dask/distributed/blob/f1023572623830e12fd162af02eff4d73bf6c6a1/distributed/utils.py#L1252

**Comment by jabbera** [comment] 2023-03-29 23:58
I've figured out what is going on here but I don't know how to fix it. I have the following environment variable set:

DASK_DISTRIBUTED__DASHBOARD__LINK='{JUPYTERHUB_EXTERNAL_BASE_URL}{JUPYTERHUB_SERVICE_PREFIX}proxy/{port}/status'

The issue is those environment variables are not available in the SSH session so the template.format is failing:

```
KeyError: 'JUPYTERHUB_EXTERNAL_BASE_URL'
```

PS. These errors are not being propagated back to the process that started the cluster which has made debugging this much harder.

**Comment by jacobtomlinson** [comment] 2023-03-30 15:50
Thanks for taking the time to dig into this. It sounds like there are two things going on here.

First is that when `DASK_DISTRIBUTED__DASHBOARD__LINK` has been misconfigured `SSHCluster` is crashing. The root of that problem is that you're not seeing helpful error messages, making debugging it a pain. The fix for this would be to explore why tracebacks aren't making it back from the remote process.

The other part is can we make it so that if `DASK_DISTRIBUTED__DASHBOARD__LINK` is misconfigured the failure mode is less aggressive. I'm not sure default behaviour would be best though as it will likely mask the problem and make it hard to debug. Perhaps a better route would be to catch the exception and log an error saying that formatting failed but continue onwards.

https://github.com/dask/distributed/blob/78a926d159b70f7c782b8f297dda6b6e695a0d0b/distributed/scheduler.py#L3873

**Comment by mplough-kobold** [comment] 2023-03-31 16:36
> First is that when `DASK_DISTRIBUTED__DASHBOARD__LINK` has been misconfigured `SSHCluster` is crashing for hard to understand reasons. The root of that problem is that you're not seeing helpful error messages, making debugging it a pain. The fix for this would be to explore why tracebacks aren't making it back from the remote process.

When I initially read this, I didn't totally understand what you meant by "misconfigured" here.  As I understand it, the problem is that the link includes an environment variable that exists only on the host and not on the cluster.

Thus, these would be incorrect...
```bash
export DASK_DISTRIBUTED__DASHBOARD__LINK="{JUPYTERHUB_EXTERNAL_BASE_URL}{JUPYTERHUB_SERVICE_PREFIX}proxy/{port}/status"
# or
export DASK_DISTRIBUTED__DASHBOARD__LINK="{JUPYTERHUB_SERVICE_PREFIX}proxy/{port}/status"
```
...and this would be correct:
(quoted from https://github.com/dask/dask-labextension/issues/109#issuecomment-580151835):
```bash
export DASK_DISTRIBUTED__DASHBOARD__LINK="proxy/{port}/status"
```

However, the correct link doesn't work.  

Suppose I have a JupyterHub deployment and I access my notebook server at:

```
https://jupyterhub.example.com/user/matt.plough/my-named-server/lab
```

Setting my `DASK_DISTRIBUTED__DASHBOARD__LINK="proxy/{port}/status"` results in the browser creating the following link in the output of a cell that says `client`:

```
https://jupyterhub.example.com/user/matt.plough/my-named-server/files/proxy/8787/status?_xsrf=[some token]
```

This is incorrect due to the inclusion of `/files`, something that does not occur when `JUPYTERHUB_SERVICE_PREFIX` is part of the `DASK_DISTRIBUTED__DASHBOARD__LINK` variable.

The [recommendation in Dask documentation](https://docs.dask.org/en/stable/configuration.html#environment-variables) of `/user/<user>/proxy/8787/status` cannot accommodate named servers, and is not flexible enough to deal with standard servers and named servers on the same box.  Use of the `JUPYTERHUB_SERVICE_PREFIX` eliminates all of these problems.

How should users configure the `DASK_DISTRIBUTED__DASHBOARD__LINK` variable when using a JupyterHub proxy?

**Closed** 2023-04-14 12:47 UTC
