### ISSUE TITLE
Bokeh dashboard failures

### ISSUE THREAD

**Issue by mrocklin** [dask/distributed#8022] opened 2023-07-20 15:50 UTC
I think I've seen other reports of this recently, but here's an example of the bokeh dashboard being sad:

https://gist.github.com/mrocklin/417439bf259b8974b502e67d2ac98f22

```python
from dask.distributed import Client
client = Client()

import zarr
import numpy as np
import dask.array as da


n = (100000, 100000)
chunksize = (5000, 5000)
input = zarr.ones(n, chunks=chunksize)

def f1d(chunk):
    return chunk.sum(keepdims=True)

def f2d(chunk, axis=None):
    return chunk.sum(axis=axis, keepdims=True)

x = da.from_array(input, chunks=chunksize)
a = x.map_blocks(f1d)
b = x.map_blocks(f2d, axis=0)
c = x.map_blocks(f2d, axis=1)

import dask
aa, bb, cc = dask.persist(a, b, c)
```

```python-traceback
BokehUserWarning: ColumnDataSource's columns must be of the same length. Current lengths: ('alpha', 519), ('color', 481), ('duration', 519), ('duration_text', 481), ('key', 481), ('name', 481), ('start', 519), ('worker', 481), ('worker_thread', 481), ('y', 519)
BokehUserWarning: ColumnDataSource's columns must be of the same length. Current lengths: ('alpha', 555), ('color', 483), ('duration', 555), ('duration_text', 483), ('key', 483), ('name', 483), ('start', 555), ('worker', 483), ('worker_thread', 483), ('y', 555)
BokehUserWarning: ColumnDataSource's columns must be of the same length. Current lengths: ('alpha', 582), ('color', 490), ('duration', 582), ('duration_text', 490), ('key', 490), ('name', 490), ('start', 582), ('worker', 490), ('worker_thread', 490), ('y', 582)
BokehUserWarning: ColumnDataSource's columns must be of the same length. Current lengths: ('alpha', 614), ('color', 478), ('duration', 614), ('duration_text', 478), ('key', 478), ('name', 478), ('start', 614), ('worker', 478), ('worker_thread', 478), ('y', 614)
BokehUserWarning: ColumnDataSource's columns must be of the same length. Current lengths: ('alpha', 644), ('color', 492), ('duration', 644), ('duration_text', 492), ('key', 492), ('name', 492), ('start', 644), ('worker', 492), ('worker_thread', 492), ('y', 644)
BokehUserWarning: ColumnDataSource's columns must be of the same length. Current lengths: ('alpha', 672), ('color', 480), ('duration', 672), ('duration_text', 480), ('key', 480), ('name', 480), ('start', 672), ('worker', 480), ('worker_thread', 480), ('y', 672)
BokehUserWarning: ColumnDataSource's columns must be of the same length. Current lengths: ('alpha', 700), ('color', 492), ('duration', 700), ('duration_text', 492), ('key', 492), ('name', 492), ('start', 700), ('worker', 492), ('worker_thread', 492), ('y', 700)
```

Sorry for the not entirely minimal example.  Hopefully it's easy to reproduce though.

**Comment by quasiben** [comment] 2023-08-08 18:29
I think there was a change between bokeh 3.2.0 and 3.2.1 .  FWIW I like @jacobtomlinson 's [poke code](https://gist.github.com/jacobtomlinson/9a13c73e1845d64ffa34f4331824d7dd) for testing the dashboard.  @bryevdv, if you have any time, do you know what may have changed relating to `ColumnDataSource`  or anything related to the above warnings ?

**Comment by bryevdv** [comment] 2023-08-08 18:36
That message indicates a usage error. Creating a CDS with different column lengths as *never* been supported, but I think a hard error was only added recently (previously you'd just get silent failures / undefined behavior). I don't think that check went in with 3.2.1 though (very little went into 3.2.1 -- https://github.com/bokeh/bokeh/milestone/82?closed=1).

If you need to update a CDS with new data that has a different length, then you need to update the entire `.data` at once:
```python
new_data_dict = ... # new dict with all new columns the same length

source.data = new_data_dict # "atomic" update
```

**Comment by v2thegreat** [comment] 2023-08-08 20:12
> I think there was a change between bokeh 3.2.0 and 3.2.1 . FWIW I like @jacobtomlinson 's [poke code](https://gist.github.com/jacobtomlinson/9a13c73e1845d64ffa34f4331824d7dd) for testing the dashboard. @bryevdv, if you have any time, do you know what may have changed relating to `ColumnDataSource` or anything related to the above warnings ?

Hi, I'm running into the issue right now. Would it make sense to downgrade to 3.2.0 and just wait it out? It's making using Dask difficult

**Comment by quasiben** [comment] 2023-08-08 20:30
Yes, I would recommend downgrading to 3.2.0 until we get this sorted out

**Comment by bryevdv** [comment] 2023-08-08 22:53
The only remotely possibly relevant change I can see was this small bugfix for streaming for the `rollover=0` case:

* https://github.com/bokeh/bokeh/pull/13239

Is the dashboard using `stream`? Can someone point me at that code if so? Is it possible you are not streaming all the columns? (Though I would expect that to have always errored)

**Comment by bryevdv** [comment] 2023-08-08 23:00
In any case the quickest test someone could perform to see if that change had any bearing would be to install 3.2.1 but copy over the `src/bokeh/core/property/wrappers.py` file from 3.2.0.

**Comment by quasiben** [comment] 2023-08-09 03:20
Apologies for the delay. It is a `stream` use case: 
https://github.com/dask/distributed/blob/de86523e2bc9a7b2fe7afd7c4053212c244aaaed/distributed/dashboard/components/scheduler.py#L2149-L2154

As you suggested I pulled the 3.2.0 wrappers.py file and that indeed did resolve the warnings from popping up

**Comment by quasiben** [comment] 2023-08-09 16:34
After exploring a bit more I think this is happening when rollover is larger than the array.  In the dask case, `L` in [wrappers.py](https://github.com/bokeh/bokeh/blob/99310e6e9140cb4f8e0655eaebe6bab156a94d2e/src/bokeh/core/property/wrappers.py#L470-L481
) will be 504 and rollover is 1000.  So there is a substantive difference between `del L[:-rollover]` and `del L[:len(L) - rollover]`. I'm not exactly clear on what is happening on the bokeh side but would it be correct to say that if rollover > len(L)  do nothing ?

**Comment by jrbourbeau** [comment] 2023-08-09 21:46
Thanks @quasiben @bryevdv!

**Comment by bryevdv** [comment] 2023-08-09 23:14
Fix PR is verified and merged. I will try to backport and cut a 3.2.2 release in the next few days

**Comment by graelo** [comment] 2023-08-11 08:43
@bryevdv this works great on 3.3, thanks a ton! Looking forward to a release ;)

**Comment by bryevdv** [comment] 2023-08-11 22:03
👍 Should be Monday

**Comment by bryevdv** [comment] 2023-08-14 02:50
3.2.2 is available on PyPI and the Bokeh `anaconda.org` channel. I am not plugged into the process for availability on conda-forge and defaults these days.

**Comment by quasiben** [comment] 2023-08-14 12:36
Thanks @bryevdv for all the help!  Confirmed 3.2.2 works.  Since this is a warning I don't think it's worth the trouble excluding bokeh 3.2.1 from installing with Distributed though if others feel differently please say so.  Closing

**Closed by quasiben** 2023-08-14 12:36 UTC
Labels: bug, dashboard

**Comment by jrbourbeau** [comment] 2023-08-14 14:30
That sounds good to me @quasiben. Thanks again for fixing / releasing @bryevdv
