### ISSUE TITLE
KeyError: 'services'

### ISSUE THREAD

**Issue by frol** [dask/distributed#383] opened 2016-07-22 09:57 UTC
I was playing wtih long-running tasks with Distributed Dask scaling a number of workers up and down, so I'm not exactly sure what actions led to the hanging Distributed master with the following log:

```
7/22/2016 12:39:37 PM distributed.utils - ERROR - 'services'
7/22/2016 12:39:37 PM Traceback (most recent call last):
7/22/2016 12:39:37 PM  File "/opt/conda/lib/python3.5/site-packages/distributed/utils.py", line 206, in log_errors
7/22/2016 12:39:37 PM    yield
7/22/2016 12:39:37 PM  File "/opt/conda/lib/python3.5/site-packages/distributed/scheduler.py", line 1616, in restart
7/22/2016 12:39:37 PM    for addr, d in self.worker_info.items()}
7/22/2016 12:39:37 PM  File "/opt/conda/lib/python3.5/site-packages/distributed/scheduler.py", line 1616, in <dictcomp>
7/22/2016 12:39:37 PM    for addr, d in self.worker_info.items()}
7/22/2016 12:39:37 PM KeyError: 'services'
```

Full log:

```
7/22/2016 12:39:20 PM distributed.scheduler - INFO - Starting worker compute stream, 10.42.145.247:42383
7/22/2016 12:39:20 PM distributed.scheduler - INFO - Register 10.42.145.247:40939
7/22/2016 12:39:20 PM distributed.scheduler - INFO - Starting worker compute stream, 10.42.145.247:46179
7/22/2016 12:39:20 PM distributed.scheduler - INFO - Starting worker compute stream, 10.42.145.247:40939
7/22/2016 12:39:20 PM distributed.core - INFO - Connection from 10.42.145.247:53876 to Scheduler
7/22/2016 12:39:20 PM distributed.scheduler - INFO - Register 10.42.145.247:43829
7/22/2016 12:39:20 PM distributed.core - INFO - Connection from 10.42.145.247:53878 to Scheduler
7/22/2016 12:39:20 PM distributed.scheduler - INFO - Starting worker compute stream, 10.42.145.247:43829
7/22/2016 12:39:20 PM distributed.scheduler - INFO - Register 10.42.145.247:42268
7/22/2016 12:39:20 PM distributed.scheduler - INFO - Starting worker compute stream, 10.42.145.247:42268
7/22/2016 12:39:20 PM distributed.core - INFO - Connection from 10.42.145.247:53880 to Scheduler
7/22/2016 12:39:20 PM distributed.scheduler - INFO - Register 10.42.145.247:46043
7/22/2016 12:39:20 PM distributed.scheduler - INFO - Starting worker compute stream, 10.42.145.247:46043
7/22/2016 12:39:37 PM distributed.utils - ERROR - 'services'
7/22/2016 12:39:37 PM Traceback (most recent call last):
7/22/2016 12:39:37 PM  File "/opt/conda/lib/python3.5/site-packages/distributed/utils.py", line 206, in log_errors
7/22/2016 12:39:37 PM    yield
7/22/2016 12:39:37 PM  File "/opt/conda/lib/python3.5/site-packages/distributed/scheduler.py", line 1616, in restart
7/22/2016 12:39:37 PM    for addr, d in self.worker_info.items()}
7/22/2016 12:39:37 PM  File "/opt/conda/lib/python3.5/site-packages/distributed/scheduler.py", line 1616, in <dictcomp>
7/22/2016 12:39:37 PM    for addr, d in self.worker_info.items()}
7/22/2016 12:39:37 PM KeyError: 'services'
7/22/2016 12:39:37 PM distributed.scheduler - ERROR - 'services'
7/22/2016 12:39:37 PM Traceback (most recent call last):
7/22/2016 12:39:37 PM  File "/opt/conda/lib/python3.5/site-packages/distributed/scheduler.py", line 1426, in handle_messages
7/22/2016 12:39:37 PM    yield result
7/22/2016 12:39:37 PM  File "/opt/conda/lib/python3.5/site-packages/tornado/gen.py", line 1008, in run
7/22/2016 12:39:37 PM    value = future.result()
7/22/2016 12:39:37 PM  File "/opt/conda/lib/python3.5/site-packages/tornado/concurrent.py", line 232, in result
7/22/2016 12:39:37 PM    raise_exc_info(self._exc_info)
7/22/2016 12:39:37 PM  File "<string>", line 3, in raise_exc_info
7/22/2016 12:39:37 PM  File "/opt/conda/lib/python3.5/site-packages/tornado/gen.py", line 282, in wrapper
7/22/2016 12:39:37 PM    yielded = next(result)
7/22/2016 12:39:37 PM  File "/opt/conda/lib/python3.5/site-packages/distributed/scheduler.py", line 1616, in restart
7/22/2016 12:39:37 PM    for addr, d in self.worker_info.items()}
7/22/2016 12:39:37 PM  File "/opt/conda/lib/python3.5/site-packages/distributed/scheduler.py", line 1616, in <dictcomp>
7/22/2016 12:39:37 PM    for addr, d in self.worker_info.items()}
7/22/2016 12:39:37 PM KeyError: 'services'
7/22/2016 12:39:37 PM distributed.utils - ERROR - 'services'
7/22/2016 12:39:37 PM Traceback (most recent call last):
7/22/2016 12:39:37 PM  File "/opt/conda/lib/python3.5/site-packages/distributed/utils.py", line 206, in log_errors
7/22/2016 12:39:37 PM    yield
7/22/2016 12:39:37 PM  File "/opt/conda/lib/python3.5/site-packages/distributed/scheduler.py", line 1426, in handle_messages
7/22/2016 12:39:37 PM    yield result
7/22/2016 12:39:37 PM  File "/opt/conda/lib/python3.5/site-packages/tornado/gen.py", line 1008, in run
7/22/2016 12:39:37 PM    value = future.result()
7/22/2016 12:39:37 PM  File "/opt/conda/lib/python3.5/site-packages/tornado/concurrent.py", line 232, in result
7/22/2016 12:39:37 PM    raise_exc_info(self._exc_info)
7/22/2016 12:39:37 PM  File "<string>", line 3, in raise_exc_info
7/22/2016 12:39:37 PM  File "/opt/conda/lib/python3.5/site-packages/tornado/gen.py", line 282, in wrapper
7/22/2016 12:39:37 PM    yielded = next(result)
7/22/2016 12:39:37 PM  File "/opt/conda/lib/python3.5/site-packages/distributed/scheduler.py", line 1616, in restart
7/22/2016 12:39:37 PM    for addr, d in self.worker_info.items()}
7/22/2016 12:39:37 PM  File "/opt/conda/lib/python3.5/site-packages/distributed/scheduler.py", line 1616, in <dictcomp>
7/22/2016 12:39:37 PM    for addr, d in self.worker_info.items()}
7/22/2016 12:39:37 PM KeyError: 'services'
7/22/2016 12:39:37 PM distributed.scheduler - INFO - Close connection to Scheduler, 996a9048-4fda-11e6-90b1-0211f410711f
7/22/2016 12:39:37 PM distributed.core - ERROR - 'services'
7/22/2016 12:39:37 PM Traceback (most recent call last):
7/22/2016 12:39:37 PM  File "/opt/conda/lib/python3.5/site-packages/distributed/core.py", line 206, in handle_stream
7/22/2016 12:39:37 PM    result = yield gen.maybe_future(handler(stream, **msg))
7/22/2016 12:39:37 PM  File "/opt/conda/lib/python3.5/site-packages/tornado/gen.py", line 1008, in run
7/22/2016 12:39:37 PM    value = future.result()
7/22/2016 12:39:37 PM  File "/opt/conda/lib/python3.5/site-packages/tornado/concurrent.py", line 232, in result
7/22/2016 12:39:37 PM    raise_exc_info(self._exc_info)
7/22/2016 12:39:37 PM  File "<string>", line 3, in raise_exc_info
7/22/2016 12:39:37 PM  File "/opt/conda/lib/python3.5/site-packages/tornado/gen.py", line 1017, in run
7/22/2016 12:39:37 PM    yielded = self.gen.send(value)
7/22/2016 12:39:37 PM  File "/opt/conda/lib/python3.5/site-packages/distributed/scheduler.py", line 1353, in add_client
7/22/2016 12:39:37 PM    yield self.handle_messages(stream, bstream, client=client)
7/22/2016 12:39:37 PM  File "/opt/conda/lib/python3.5/site-packages/tornado/gen.py", line 1008, in run
7/22/2016 12:39:37 PM    value = future.result()
7/22/2016 12:39:37 PM  File "/opt/conda/lib/python3.5/site-packages/tornado/concurrent.py", line 232, in result
7/22/2016 12:39:37 PM    raise_exc_info(self._exc_info)
7/22/2016 12:39:37 PM  File "<string>", line 3, in raise_exc_info
7/22/2016 12:39:37 PM  File "/opt/conda/lib/python3.5/site-packages/tornado/gen.py", line 1014, in run
7/22/2016 12:39:37 PM    yielded = self.gen.throw(*exc_info)
7/22/2016 12:39:37 PM  File "/opt/conda/lib/python3.5/site-packages/distributed/scheduler.py", line 1426, in handle_messages
7/22/2016 12:39:37 PM    yield result
7/22/2016 12:39:37 PM  File "/opt/conda/lib/python3.5/site-packages/tornado/gen.py", line 1008, in run
7/22/2016 12:39:37 PM    value = future.result()
7/22/2016 12:39:37 PM  File "/opt/conda/lib/python3.5/site-packages/tornado/concurrent.py", line 232, in result
7/22/2016 12:39:37 PM    raise_exc_info(self._exc_info)
7/22/2016 12:39:37 PM  File "<string>", line 3, in raise_exc_info
7/22/2016 12:39:37 PM  File "/opt/conda/lib/python3.5/site-packages/tornado/gen.py", line 282, in wrapper
7/22/2016 12:39:37 PM    yielded = next(result)
7/22/2016 12:39:37 PM  File "/opt/conda/lib/python3.5/site-packages/distributed/scheduler.py", line 1616, in restart
7/22/2016 12:39:37 PM    for addr, d in self.worker_info.items()}
7/22/2016 12:39:37 PM  File "/opt/conda/lib/python3.5/site-packages/distributed/scheduler.py", line 1616, in <dictcomp>
7/22/2016 12:39:37 PM    for addr, d in self.worker_info.items()}
7/22/2016 12:39:37 PM KeyError: 'services'
7/22/2016 12:39:37 PM distributed.core - INFO - Lost connection: ('10.42.138.167', 38072)
7/22/2016 12:39:37 PM distributed.core - INFO - Close connection from 10.42.138.167:38072 to Scheduler
7/22/2016 12:39:43 PM /opt/conda/lib/python3.5/site-packages/distributed/bokeh/status_monitor.py:132: BokehDeprecationWarning: bokeh.io.vplot was deprecated in Bokeh 0.12.0; please use bokeh.models.layouts.Column instead
7/22/2016 12:39:43 PM  table = vplot(slow, fast)
7/22/2016 12:39:43 PM bokeh.server.views.ws - INFO - WebSocket connection closed: code=1001, reason=None
7/22/2016 12:39:45 PM bokeh.server.views.ws - INFO - WebSocket connection opened
7/22/2016 12:39:45 PM /opt/conda/lib/python3.5/site-packages/distributed/bokeh/status_monitor.py:132: BokehDeprecationWarning: bokeh.io.vplot was deprecated in Bokeh 0.12.0; please use bokeh.models.layouts.Column instead
7/22/2016 12:39:45 PM  table = vplot(slow, fast)
7/22/2016 12:39:45 PM bokeh.server.views.ws - INFO - ServerConnection created
```

**Comment by mrocklin** [comment] 2016-07-22 11:19
Hrm, my guess is that the following happened:

1.  Scheduler started normally
2.  Worker started normally
3.  Worker left normally
4.  Some errant message comes in from worker after it leaves, causing an empty entry to re-appear in worker_info because it is a `defaultdict`
5.  Restart call fails on `scheduler.worker_info[address]['services']` access because the entry in the defaultdict exists but is empty

This can possibly be resolved by guarding all access to `worker_info` and discarding messages from unregistered workers.

I could also be wrong with this analysis.  Do you have any more information about how you're scaling the network up and down?

**Comment by frol** [comment] 2016-07-22 11:27
> Do you have any more information about how you're scaling the network up and down?

I'm using separate Docker containers for master and every worker, linking the containers together with Rancher (it sets up IPsec for inter-container communication). Thus, from the network point of view, new workers arrive with new IPs, and once I scale them down, they receive SIGTERM, so they should be able to terminate gracefully.

**Comment by mrocklin** [comment] 2016-07-22 11:30
How frequently are you scaling them up and down?  Are you doing computations during this process?  At some point it appears that you're calling `restart`, is this happening repeatedly?

All of these things should work fine in theory.  I'm just trying to understand the breadth of the issue.

**Comment by frol** [comment] 2016-07-22 12:09
I had a 10-minute-long computation with 1.5k+ tasks (`dataframe.read_csv` 100GB TSV file from HDFS) started with one worker with `--nproc 20 --threads 1`; I scaled it up to 5 such workers, then to 10 and later 20; I let it working for a couple of minutes and I scaled number of workers down to 19; I confirmed that some tasks are recomputing (which is perfect!), so I stopped another worker and decided to let it finish, but unfortunately, it stuck saying that 6 tasks out of 1500+ are left and it never finished, so I interrupted Jupyter Notebook cell and tried to restart.

Does this make sense?

**Comment by mrocklin** [comment] 2016-07-22 12:14
That does make sense, and is very helpful.  

Let me try rejecting messages from unknown workers and push a change up to a branch.  Are you able/willing to test this again a few times?  Case studies like this are very valuable but also tricky for me to reproduce locally.

**Comment by mrocklin** [comment] 2016-07-22 12:21
In particular, if you can run the same experiment from this branch: https://github.com/dask/distributed/pull/384 I would still expect things to fail, but I would expect them to fail earlier and help us understand where the error originates.

If it's a pain to redo this experiment multiple times that's fine too.  I can perform the fix that I *think* will solve the problem, and I can also try to design experiments that will trigger the issue.

**Comment by frol** [comment] 2016-07-22 12:21
@mrocklin I will sure be able to run the fixed version. Let me know once you have it. These types of bugs are really nasty, so it will be nice to have detailed logging there, so we can see whether we could have had the state in which it failed previously.

**Comment by mrocklin** [comment] 2016-07-27 21:11
Closing for now.  Please reopen if the problem persists.

**Closed by mrocklin** 2016-07-27 21:11 UTC
