### ISSUE TITLE
Perhaps you already have a cluster running?  In CI

### ISSUE THREAD

**Issue by mrocklin** [dask/distributed#4919] opened 2021-06-15 13:01 UTC
Looking at CI results I see hundreds of messages like these:

```python
distributed/tests/test_multi_locks.py::test_multiple_locks
  /Users/runner/work/distributed/distributed/distributed/node.py:160: UserWarning: Port 8787 is already in use.
  Perhaps you already have a cluster running?
  Hosting the HTTP server on port 64808 instead
    warnings.warn(
```

Perhaps we left a server running in one of our tests?

**Comment by fgebhart** [comment] 2021-06-15 13:31
Might be a duplicate of #4806 ?

**Comment by jacobtomlinson** [comment] 2021-06-15 13:37
Yeah closing as duplicate of #4806

**Closed by jacobtomlinson** 2021-06-15 13:37 UTC
