### ISSUE TITLE
distributed.nanny cannot start worker process

### ISSUE THREAD

**Issue by seanstorey** [dask/distributed#1770] opened 2018-02-16 09:25 UTC
**start dask-worker tcp://192.168.1.251:8786**

outputs

distributed.nanny - INFO -     Start nanny at: 'tcp://192.168.1.251:51329'
distributed.nanny - INFO - Failed to start worker process.  Restarting
distributed.nanny - INFO - Failed to start worker process.  Restarting
...

task manager shows the worker processes are being spawned but stop after a couple of seconds 

**start dask-worker tcp://192.168.1.251:8786 --no-nanny** 

runs correctly connecting to the distributed.scheduler. 

Using dask==0.17.0, distributed==1.21.0, tornado==4.5.3 on Windows 10 Professional with 

logging:
  distributed: info
  distributed.client: warning
  distributed.nanny: debug
  distributed.nanny: debug

Is it possible to redirect the logs to file, particularly for the spawned worker processes ?

**Comment by mrocklin** [comment] 2018-02-16 12:24
Logs are sent to stderr, you can redirect them as follows:

    dask-worker ... 2> log.txt

**Comment by mrocklin** [comment] 2018-02-16 15:26
I don't generally have any helpful information on what might be going on.  You might also consider trying one version back to see if this was newly introduced.

**Comment by nav1n** [comment] 2018-02-27 15:42
I have the same issue, but worked around it by extending the timeout found in nanny.py within the start method of the WorkerProcess class from 5 to 10 seconds:
```
                yield self.process.start()
                if self.status == 'starting':
                    yield gen.with_timeout(timedelta(seconds=10),
                                           self._wait_until_running())
```
I see this log message when the worker starts up:
`distributed.core - WARNING - Event loop was unresponsive in Nanny for 5.54s.  This is often caused by long-running GIL-holding functions or moving large chunks of data. This can cause timeouts and instability.`

**Comment by mrocklin** [comment] 2018-02-27 19:36
Hrm, that's interesting feedback.  Ideally there wouldn't be any hard-coded timeouts like that (I see that there are a few more floating around).  

Presumably you're on a system where startup times are longer, both due to Windows' spawn and possibly also due to things like network filesystems, etc..  This reliance on a fixed timeout seems like a bug to me.

**Comment by seanstorey** [comment] 2018-02-27 20:21
Thanks nav1n, I had found this and tried seconds=10 with out success though have also tried it at seconds=20 again without luck. I'm following the code / adding logging but as it works with -no-nanny it hasn't been on the top of my to-do list :-) though I will investigate further

**Comment by jakirkham** [comment] 2018-02-28 08:33
Does 1.21.1 work for you @seanstorey?

**Comment by jfnk** [comment] 2018-02-28 12:34
Hi, I am running into the same problem as described by seanstorey. Upon starting a worker with 

``dask-worker tcp://127.0.0.1:8786``

I get the output: 
``distributed.nanny - INFO -         Start Nanny at: 'tcp://127.0.0.1:61027'
distributed.nanny - INFO - Failed to start worker process.  Restarting
distributed.nanny - INFO - Failed to start worker process.  Restarting``
...

using the argument ``--no-nanny`` works fine.

Starting a local cluster fails if ``processes = True`` and works if ``processes = False``

My versions: 
``dask=0.17.1, distributed=1.21.1, tornado=4.5.3``
running on Windows 7.

**Comment by mrocklin** [comment] 2018-02-28 12:42
OK, my guess is just that starting on Windows is taking longer than expected (probably due to things like the lack of fork).  On my Windows VM I'm getting times between two and three seconds, but I wouldn't be surprised to see this number jump depending on other factors, like network file systems.  

There are a couple of different approaches.  We could try to reduce import time https://github.com/dask/distributed/issues/1399 or we could increase the allowed timeout.  Regardless the timeout should be configurable.

**Comment by mrocklin** [comment] 2018-02-28 13:55
Possibly resolved in https://github.com/dask/distributed/pull/1793

**Closed** 2018-03-01 18:11 UTC
