### ISSUE TITLE
TaskGroups visual fails to load static images

### ISSUE THREAD

**Issue by mrocklin** [dask/distributed#5014] opened 2021-07-01 14:18 UTC
Failed to load resource: the server responded with a status of 404 (). statics/images/pandas.png:1

This is running on Coiled with `mrocklin/dev`

```
CONDA
{
  "dependencies": [
    "bokeh",
    "dask",
    "s3fs"
  ]
}
PIP
[
  "git+https://github.com/dask/dask@main",
  "git+https://github.com/dask/distributed@main"
]
```

cc @ncclementi @ian-r-rose

**Comment by ian-r-rose** [comment] 2021-07-01 15:13
Interesting, I can't reproduce this with a `LocalCluster`. Trying now with a remote cluster.

**Comment by mrocklin** [comment] 2021-07-01 15:16
Maybe also this has to do with Coiled and a different location?

It could also be with how I installed things, with `pip install git+https://
...`

**Comment by ian-r-rose** [comment] 2021-07-01 15:41
I was just able to reproduce on coiled, and listing the contents of the statics directory using `client.run_on_scheduler` reveals that they are indeed missing. Something must be missing in the bundling process, looking into it.

**Comment by jrbourbeau** [comment] 2021-07-01 15:47
Just a shot in the dark, but maybe we should include `*.png` files similar to

https://github.com/dask/distributed/blob/b8b4ff81f4071b46453ecdee4bdc26b648139603/MANIFEST.in#L6

in our `MANIFEST.in`?

**Comment by ian-r-rose** [comment] 2021-07-01 15:54
> Just a shot in the dark, but maybe we should include `*.png` files similar to
> 
> https://github.com/dask/distributed/blob/b8b4ff81f4071b46453ecdee4bdc26b648139603/MANIFEST.in#L6
> 
> in our `MANIFEST.in`?

Yep, just opened a PR with that fix

**Comment by jrbourbeau** [comment] 2021-07-01 16:03
Awesome, thank you!

FWIW I'm not sure why we're using png instead of svg for the images in the task group plot. We tend to use svg for their nice scaling properties. Perhaps @ncclementi or @ian-r-rose has some insight here

**Comment by ncclementi** [comment] 2021-07-01 16:05
When I tried using `svg` images, they wouldn't load and I couldn't find out why. @ian-r-rose you also noticed this when moving to statics right?

**Comment by ian-r-rose** [comment] 2021-07-01 16:07
> When I tried using `svg` images, they wouldn't load and I couldn't find out why. @ian-r-rose you also noticed this when moving to statics right?

Yeah, I found that svg loading by bokeh was unreliable. Some worked, others did not. I couldn't figure out why in ~30 minutes, so I kicked the can down the road.

**Closed** 2021-07-01 21:52 UTC
