### ISSUE TITLE
Dashboard link in client repr doesn't work

### ISSUE THREAD

**Issue by jcrist** [dask/distributed#1974] opened 2018-05-09 03:12 UTC
When repr-ing a `Client` in the notebook, the dashboard link is unclickable, while the link in the `LocalCluster` repr works fine. This is in jupyterlab, which overrides the right click behavior, so I can't just right-click and "copy link" either.
<img width="425" alt="screen shot 2018-05-08 at 11 09 06 pm" src="https://user-images.githubusercontent.com/2783717/39793828-1b173992-5315-11e8-862f-def2e94e1003.png">

**Comment by mrocklin** [comment] 2018-05-09 09:59
Hrm, interestingly I'm able to reproduce on a jupyterhub deployment (I'm using pangeo) but not on my local machine.

**Comment by GenevieveBuckley** [comment] 2021-10-18 05:40
I am not able to reproduce this, either locally or on pangeo (I clicked the mybinder link from [this pangeo example notebook](http://gallery.pangeo.io/repos/pangeo-data/pangeo-tutorial-gallery/dask.html)). I tried using both Firefox and Chrome browsers.

@jcrist do you still see this problem, or can the issue be closed? It might be possible things changed in the last few years and this doesn't happen anymore.

**Comment by jrbourbeau** [comment] 2021-11-02 23:07
Closing due to @GenevieveBuckley not being able to reproduce. Let's re-open as needed

**Closed by jrbourbeau** 2021-11-02 23:07 UTC
Labels: needs info
