### ISSUE TITLE
client.compute() not properly working with "workers" and dask.array

### ISSUE THREAD

**Issue by cbyrohl** [dask/distributed#3590] opened 2020-03-19 09:33 UTC
Hi there,

client.compute() properly works with a delayed object and "workers" specified, but not with a dask array.

For an existing (distributed) client

```python
from dask import delayed
from operator import add
x = delayed(add)(1, 2)
xx = client.compute([x],workers=['tcp://130.183.183.160:34655'])
```

is fine, but

```python
import dask.array as da
y = da.random.random(10)
y = client.compute([y],workers=['tcp://130.183.183.160:34655'])
```

fails with:

```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
/freya/u/cbyrohl/repos/voroILTIS/production_LAE_SBr/haloprofiles.py in <module>
      1 from dask import delayed
      2 y = da.random.random(10)
----> 3 y = client.compute([y],workers=['tcp://130.183.183.160:34655'])

~/anaconda3/envs/lya/lib/python3.7/site-packages/distributed/client.py in compute(self, collections, sync, optimize_graph, workers, allow_other_workers, resources, retries, priority, fifo_timeout, actors, traverse, **kwargs)
   2767 
   2768         restrictions, loose_restrictions = self.get_restrictions(
-> 2769             collections, workers, allow_other_workers
   2770         )
   2771 

~/anaconda3/envs/lya/lib/python3.7/site-packages/distributed/client.py in get_restrictions(cls, collections, workers, allow_other_workers)
   3814         """ Get restrictions from inputs to compute/persist """
   3815         if isinstance(workers, (str, tuple, list)):
-> 3816             workers = {tuple(collections): workers}
   3817         if isinstance(workers, dict):
   3818             restrictions = {}

TypeError: unhashable type: 'Array'
```

Easy workaround is to create a delayed object from the array, but I think client.compute() is supposed to work with all dask collections?

Thanks,
Chris

**Comment by mrocklin** [comment] 2020-03-23 20:53
Yes indeed, this appears to be a bug.  Thank you for raising @cbyrohl

**Comment by mrocklin** [comment] 2020-03-23 20:53
Is this something that you're interesting in helping to resolve?

**Comment by andrewfulton9** [comment] 2020-09-25 00:05
Is this issue already resolved? I'm not able to reproduce it.

**Comment by mrocklin** [comment] 2020-09-26 01:13
Great.  Thanks for checking @andrewfulton9 .  Closing.

**Comment by jrbourbeau** [comment] 2020-11-30 22:02
Reopening as 

```python

import dask.array as da
from dask.distributed import Client

if __name__ == "__main__":
    with Client() as client:
        w = min(client.scheduler_info()["workers"])
        client.compute(da.arange(10), workers=w)
```

raises

```
Traceback (most recent call last):
  File "test-bug.py", line 8, in <module>
    client.compute(da.arange(10), workers=w)
  File "/Users/james/projects/dask/distributed/distributed/client.py", line 2852, in compute
    restrictions, loose_restrictions = self.get_restrictions(
  File "/Users/james/projects/dask/distributed/distributed/client.py", line 3931, in get_restrictions
    workers = {tuple(collections): workers}
TypeError: unhashable type: 'Array'
```

using the latest development version of distributed (e9cd97f)

**Comment by jrbourbeau** [comment] 2021-03-20 16:16
Closing as today one can specify which workers to compute a collection on using Dask's [annotation macheinery](https://docs.dask.org/en/latest/api.html#dask.annotate)

xref https://github.com/dask/distributed/pull/4406

**Closed by jrbourbeau** 2021-03-20 16:16 UTC
Labels: good second issue, help wanted
