### ISSUE TITLE
WorkerState localdirectory not initialized

### ISSUE THREAD

**Issue by adamklein** [dask/distributed#2382] opened 2018-11-29 20:59 UTC
I have been seeing these tracebacks occassionally when using distributed (1.24.0)

	python3.5/site-packages/distributed/utils.py", line 277, in sync
		six.reraise(*error[0])
	  File "./.conda/envs/xyz/lib/python3.5/site-packages/six.py", line 693, in reraise
		raise value
	  File "./.conda/envs/xyz/lib/python3.5/site-packages/distributed/utils.py", line 262, in f
		result[0] = yield future
	  File "./.conda/envs/xyz/lib/python3.5/site-packages/tornado/gen.py", line 1133, in run
		value = future.result()
	  File "./.conda/envs/xyz/lib/python3.5/asyncio/futures.py", line 294, in result
		raise self._exception
	  File "./.conda/envs/xyz/lib/python3.5/site-packages/tornado/gen.py", line 1141, in run
		yielded = self.gen.throw(*exc_info)
	  File "./.conda/envs/xyz/lib/python3.5/site-packages/distributed/client.py", line 821, in _start
		yield self._ensure_connected(timeout=timeout)
	  File "./.conda/envs/xyz/lib/python3.5/site-packages/tornado/gen.py", line 1133, in run
		value = future.result()
	  File "./.conda/envs/xyz/lib/python3.5/asyncio/futures.py", line 294, in result
		raise self._exception
	  File "./.conda/envs/xyz/lib/python3.5/site-packages/tornado/gen.py", line 1141, in run
		yielded = self.gen.throw(*exc_info)
	  File "./.conda/envs/xyz/lib/python3.5/site-packages/distributed/client.py", line 862, in _ensure_connected
		self._update_scheduler_info())
	  File "./.conda/envs/xyz/lib/python3.5/site-packages/tornado/gen.py", line 1133, in run
		value = future.result()
	  File "./.conda/envs/xyz/lib/python3.5/asyncio/futures.py", line 294, in result
		raise self._exception
	  File "./.conda/envs/xyz/lib/python3.5/site-packages/tornado/gen.py", line 1141, in run
		yielded = self.gen.throw(*exc_info)
	  File "./.conda/envs/xyz/lib/python3.5/site-packages/distributed/client.py", line 896, in _update_scheduler_info
		self._scheduler_identity = yield self.scheduler.identity()
	  File "./.conda/envs/xyz/lib/python3.5/site-packages/tornado/gen.py", line 1133, in run
		value = future.result()
	  File "./.conda/envs/xyz/lib/python3.5/asyncio/futures.py", line 294, in result
		raise self._exception
	  File "./.conda/envs/xyz/lib/python3.5/site-packages/tornado/gen.py", line 1141, in run
		yielded = self.gen.throw(*exc_info)
	  File "./.conda/envs/xyz/lib/python3.5/site-packages/distributed/core.py", line 574, in send_recv_from_rpc
		result = yield send_recv(comm=comm, op=key, **kwargs)
	  File "./.conda/envs/xyz/lib/python3.5/site-packages/tornado/gen.py", line 1133, in run
		value = future.result()
	  File "./.conda/envs/xyz/lib/python3.5/asyncio/futures.py", line 294, in result
		raise self._exception
	  File "./.conda/envs/xyz/lib/python3.5/site-packages/tornado/gen.py", line 1147, in run
		yielded = self.gen.send(value)
	  File "./.conda/envs/xyz/lib/python3.5/site-packages/distributed/core.py", line 466, in send_recv
		six.reraise(*clean_exception(**response))
	  File "./.conda/envs/xyz/lib/python3.5/site-packages/six.py", line 692, in reraise
		raise value.with_traceback(tb)
	  File "./.conda/envs/xyz/lib/python3.5/site-packages/distributed/core.py", line 337, in handle_comm
		result = handler(comm, **msg)
	  File "./.conda/envs/xyz/lib/python3.5/site-packages/distributed/scheduler.py", line 1018, in identity
		for worker in self.workers.values()}}
	  File "./.conda/envs/xyz/lib/python3.5/site-packages/distributed/scheduler.py", line 1018, in <dictcomp>
		for worker in self.workers.values()}}
	  File "./.conda/envs/xyz/lib/python3.5/site-packages/distributed/scheduler.py", line 251, in identity
		'local_directory': self.local_directory,
	AttributeError: local_directory

The `local_directory` slot is not initialized in `__init__`. Is this intentional, or an oversight?

**Comment by mrocklin** [comment] 2018-11-30 00:31
Nice catch. I suspect that the problem is here:

https://github.com/dask/distributed/blob/e6b1ef5027c4914170af12882ab4528dce2e2ba3/distributed/scheduler.py#L1276-L1302

Notice that we create the `WorkerState` object, then there is a `yield` (during which anything can happen really, including the identity/heartbeat check) and then we finally assign `local_directory`.  The easist solution is probably to assign a dummy value like `None` or the empty string for that (and all other values) in the constructor.

**Comment by jcrist** [comment] 2018-11-30 21:44
Should be fixed by #2388.

**Closed** 2018-11-30 23:01 UTC
