### ISSUE TITLE
`dask worker --nworkers 256` does not start 256 workers on machines with 256 cores

### ISSUE THREAD

**Issue by arneyjfs** [dask/distributed#8768] opened 2024-07-15 15:20 UTC
**Describe the issue**:

[The documentation](https://docs.dask.org/en/stable/deploying-cli.html#:~:text=Number%20of%20worker%20processes%20to%20launch) says that if the argument passed to `--nworkers` is negative, then `(CPU_COUNT + 1 + nworkers)` is used for the number of processes. I have 2 machines in the cluster, both with the same specs (`nproc = 256`) however I do not get 256 workers. 

Full CPU specs:
```shell
> lscpu | egrep 'Model name|Socket|Core|Thread|NUMA|CPU\(s\)'
CPU(s):                             256
On-line CPU(s) list:                0-255
Model name:                         AMD EPYC 7713 64-Core Processor
Thread(s) per core:                 2
Core(s) per socket:                 64
Socket(s):                          2
NUMA node(s):                       2
NUMA node0 CPU(s):                  0-63,128-191
NUMA node1 CPU(s):                  64-127,192-255
```

The number i actually get seems to fluctuate each time I run the `dask worker` command. One server normally starts with around 210 workers, and the other with around 70 workers, but this changes. The UI therefore reports about 280 workers  in total with 1 thread each.

![image](https://github.com/user-attachments/assets/e91f8604-74c8-47fd-8ad6-50b07a8a2cf6)

Firstly, why the variability? And secondly, how can I maximise this count? The workloads I need to run are simple single process medium length tasks. 

**Minimal Complete Verifiable Example**:

```shell
# Scheduler
dask scheduler --host X.X.X.7
```

```shell
# Workers
dask worker tcp://X.X.X.7:8786 --nworkers -1
```

**Anything else we need to know?**:
Things I've ruled out:
- setting `--nworkers` explicitly to 256 behaves the same as -1
- also specifying `--nthreads` makes no change
- halfing the nworkers to 128 works - I get 128 workers with 2 threads each. Is dask hitting an upper limit here? If so why is it vaiable between 70-210?
- nothing else is consuming significant resources on the servers

**Environment**:

- Dask version: 2024.6.2
- Python version: 3.10.12
- Operating System: Ubuntu 22.04.4 LTS
- Install method (conda, pip, source): pip

**Comment by jacobtomlinson** [comment] 2024-10-17 16:40
Looking at the source the logic for `-1` definitely results in `nworkers` being set to `256`.

https://github.com/dask/distributed/blob/48509b35d74a605340108a3a129278efb231f417/distributed/cli/dask_worker.py#L295-L296

I think given that you confirm that setting `--nworkers 256` results in the same thing then the whole negative math thing is a red herring.

In which case there must be some problem with starting that high number of workers on machines with hight CPU core counts. My machine has 12 cores and behaves as expected. I'll have a go at starting a large VM on the cloud and trying to reproduce there.

**Comment by jacobtomlinson** [comment] 2024-10-18 10:44
The largest VM I could create on AWS had 192 cores, and running `dask worker --nworkers -1` resulted in 192 workers joining the cluster.

**Comment by jacobtomlinson** [comment] 2024-10-18 11:06
I also tried launching a second VM and running the same command and can confirm that I now have 384 workers connected.

<img width="961" alt="image" src="https://github.com/user-attachments/assets/e11c6c67-78ac-40dc-a763-f26a56df4377">

This suggests that maybe you are running into a limitation on the system you are running on. I'm going to close this issue out as "cannot reproduce" but if you have any more ideas about how we can see this bug in action then please feel free to comment here and we can reopen.

**Closed by jacobtomlinson** 2024-10-18 11:06 UTC
Labels: bug, needs info
