### ISSUE TITLE
maximum recursion depth exceeded while calling a Python object

### ISSUE THREAD

**Issue by bhagatsajan0073** [dask/distributed#4684] opened 2021-04-07 19:38 UTC
**Getting below error while executing model.fit in joblib on dask cluster** 

    model.fit(x_train, y_train)
  File "/usr/local/lib/python3.8/site-packages/sklearn/ensemble/_forest.py", line 304, in fit
    X, y = self._validate_data(X, y, multi_output=True,
  File "/usr/local/lib/python3.8/site-packages/sklearn/base.py", line 433, in _validate_data
    X, y = check_X_y(X, y, **check_params)
  File "/usr/local/lib/python3.8/site-packages/sklearn/utils/validation.py", line 63, in inner_f
    return f(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/sklearn/utils/validation.py", line 814, in check_X_y
    X = check_array(X, accept_sparse=accept_sparse,
  File "/usr/local/lib/python3.8/site-packages/sklearn/utils/validation.py", line 63, in inner_f
    return f(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/sklearn/utils/validation.py", line 616, in check_array
    array = np.asarray(array, order=order, dtype=dtype)
  File "/usr/local/lib/python3.8/site-packages/numpy/core/_asarray.py", line 102, in asarray
    return array(a, dtype, copy=False, order=order)
  File "/usr/local/lib/python3.8/site-packages/dask/dataframe/core.py", line 371, in __array__
    self._computed = self.compute()
  File "/usr/local/lib/python3.8/site-packages/dask/base.py", line 167, in compute
    (result,) = compute(self, traverse=False, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/dask/base.py", line 452, in compute
    results = schedule(dsk, keys, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/distributed/client.py", line 2725, in get
    results = self.gather(packed, asynchronous=asynchronous, direct=direct)
  File "/usr/local/lib/python3.8/site-packages/distributed/client.py", line 1986, in gather
    return self.sync(
  File "/usr/local/lib/python3.8/site-packages/distributed/client.py", line 832, in sync
    return sync(
  File "/usr/local/lib/python3.8/site-packages/distributed/utils.py", line 340, in sync
    raise exc.with_traceback(tb)
  File "/usr/local/lib/python3.8/site-packages/distributed/utils.py", line 324, in f
    result[0] = yield future
  File "/usr/local/lib/python3.8/site-packages/tornado/gen.py", line 762, in run
    value = future.result()
  File "/usr/local/lib/python3.8/site-packages/distributed/client.py", line 1851, in _gather
    raise exception.with_traceback(traceback)
Exception: maximum recursion depth exceeded while calling a Python object

**Comment by jrbourbeau** [comment] 2021-04-07 19:49
Thanks for raising an issue @bhagatsajan0073. Are you able to provide a [minimal example](https://blog.dask.org/2018/02/28/minimal-bug-reports)? Otherwise it may be difficult for others to help with the level of information given

**Comment by bhagatsajan0073** [comment] 2021-04-08 10:01
import dask
from dask.distributed import Client,progress
import joblib
import pandas as pd
import dask.dataframe as dd

client = Client('127.0.0.1:8786')
client.ncores()

customer=pd.DataFrame({
    "customer_id":list(range(1,100)),
    "Rank" : list(range(1,100))
})

--------------------------------------------------------
### Error is as follow
---------------------------------------------------------------------------
Exception                                 Traceback (most recent call last)
<ipython-input-19-f85e001511cc> in <module>
      2 df = client.persist(df)
      3 
----> 4 df.head()

c:\users\bhaga\anaconda3\envs\mlq-env\lib\site-packages\dask\dataframe\core.py in head(self, n, npartitions, compute)
   1004             Whether to compute the result, default is True.
   1005         """
-> 1006         return self._head(n=n, npartitions=npartitions, compute=compute, safe=True)
   1007 
   1008     def _head(self, n, npartitions, compute, safe):

c:\users\bhaga\anaconda3\envs\mlq-env\lib\site-packages\dask\dataframe\core.py in _head(self, n, npartitions, compute, safe)
   1037 
   1038         if compute:
-> 1039             result = result.compute()
   1040         return result
   1041 

c:\users\bhaga\anaconda3\envs\mlq-env\lib\site-packages\dask\base.py in compute(self, **kwargs)
    165         dask.base.compute
    166         """
--> 167         (result,) = compute(self, traverse=False, **kwargs)
    168         return result
    169 

c:\users\bhaga\anaconda3\envs\mlq-env\lib\site-packages\dask\base.py in compute(*args, **kwargs)
    450         postcomputes.append(x.__dask_postcompute__())
    451 
--> 452     results = schedule(dsk, keys, **kwargs)
    453     return repack([f(r, *a) for r, (f, a) in zip(results, postcomputes)])
    454 

c:\users\bhaga\anaconda3\envs\mlq-env\lib\site-packages\distributed\client.py in get(self, dsk, keys, restrictions, loose_restrictions, resources, sync, asynchronous, direct, retries, priority, fifo_timeout, actors, **kwargs)
   2723                     should_rejoin = False
   2724             try:
-> 2725                 results = self.gather(packed, asynchronous=asynchronous, direct=direct)
   2726             finally:
   2727                 for f in futures.values():

c:\users\bhaga\anaconda3\envs\mlq-env\lib\site-packages\distributed\client.py in gather(self, futures, errors, direct, asynchronous)
   1984             else:
   1985                 local_worker = None
-> 1986             return self.sync(
   1987                 self._gather,
   1988                 futures,

c:\users\bhaga\anaconda3\envs\mlq-env\lib\site-packages\distributed\client.py in sync(self, func, asynchronous, callback_timeout, *args, **kwargs)
    830             return future
    831         else:
--> 832             return sync(
    833                 self.loop, func, *args, callback_timeout=callback_timeout, **kwargs
    834             )

c:\users\bhaga\anaconda3\envs\mlq-env\lib\site-packages\distributed\utils.py in sync(loop, func, callback_timeout, *args, **kwargs)
    338     if error[0]:
    339         typ, exc, tb = error[0]
--> 340         raise exc.with_traceback(tb)
    341     else:
    342         return result[0]

c:\users\bhaga\anaconda3\envs\mlq-env\lib\site-packages\distributed\utils.py in f()
    322             if callback_timeout is not None:
    323                 future = asyncio.wait_for(future, callback_timeout)
--> 324             result[0] = yield future
    325         except Exception as exc:
    326             error[0] = sys.exc_info()

c:\users\bhaga\anaconda3\envs\mlq-env\lib\site-packages\tornado\gen.py in run(self)
    760 
    761                     try:
--> 762                         value = future.result()
    763                     except Exception:
    764                         exc_info = sys.exc_info()

c:\users\bhaga\anaconda3\envs\mlq-env\lib\site-packages\distributed\client.py in _gather(self, futures, errors, direct, local_worker)
   1849                             exc = CancelledError(key)
   1850                         else:
-> 1851                             raise exception.with_traceback(traceback)
   1852                         raise exc
   1853                     if errors == "skip":

Exception: maximum recursion depth exceeded while calling a Python object

-------------------------------------------------------------------------------------
### Cluster config (scheduler, worker) and Client Config
 
Geeting same error on executing any operation on dask dataframe which involves compute interanlly on later cluster with dask version 2021.4.0 as well

{'scheduler': {'host': {'python': '3.8.0.final.0',
   'python-bits': 64,
   'OS': 'Linux',
   'OS-release': '5.4.72-microsoft-standard-WSL2',
   'machine': 'x86_64',
   'processor': '',
   'byteorder': 'little',
   'LC_ALL': 'C.UTF-8',
   'LANG': 'C.UTF-8'},
  'packages': {'python': '3.8.0.final.0',
   'dask': '2.30.0',
   'distributed': '2.30.1',
   'msgpack': '1.0.0',
   'cloudpickle': '1.6.0',
   'tornado': '6.1',
   'toolz': '0.11.1',
   'numpy': '1.18.1',
   'lz4': '3.1.1',
   'blosc': '1.9.2'}},
 'workers': {'tcp://172.21.0.2:34547': {'host': {'python': '3.8.0.final.0',
    'python-bits': 64,
    'OS': 'Linux',
    'OS-release': '5.4.72-microsoft-standard-WSL2',
    'machine': 'x86_64',
    'processor': '',
    'byteorder': 'little',
    'LC_ALL': 'C.UTF-8',
    'LANG': 'C.UTF-8'},
   'packages': {'python': '3.8.0.final.0',
    'dask': '2.30.0',
    'distributed': '2.30.1',
    'msgpack': '1.0.0',
    'cloudpickle': '1.6.0',
    'tornado': '6.1',
    'toolz': '0.11.1',
    'numpy': '1.18.1',
    'lz4': '3.1.1',
    'blosc': '1.9.2'}}},
 'client': {'host': {'python': '3.8.5.final.0',
   'python-bits': 64,
   'OS': 'Windows',
   'OS-release': '10',
   'machine': 'AMD64',
   'processor': 'Intel64 Family 6 Model 158 Stepping 10, GenuineIntel',
   'byteorder': 'little',
   'LC_ALL': 'None',
   'LANG': 'None'},
  'packages': {'python': '3.8.5.final.0',
   'dask': '2.30.0',
   'distributed': '2.30.1',
   'msgpack': '1.0.2',
   'cloudpickle': '1.6.0',
   'tornado': '6.1',
   'toolz': '0.11.1',
   'numpy': '1.19.2',
   'lz4': None,
   'blosc': None}}}

**Comment by fjetter** [comment] 2021-04-08 11:34
@bhagatsajan0073 I cannot reproduce this on my machine but I do not have access to windows atm. Can you please double check your example? You're importing `joblib` but are not using it. Maybe it requires a more complex example to reproduce.

I also noticed, that you're using a bit older version of `dask` `distributed`. Could you try upgrading to see if the problem persists?

**Comment by hristog** [comment] 2021-04-08 16:31
Hi @bhagatsajan0073 - I haven't been able to reproduce this either (with both sets of versions of `dask` and `distributed` you've mentioned).

```python
import dask
from dask.distributed import Client, LocalCluster, progress
import joblib
import pandas as pd
import dask.dataframe as dd

cluster = LocalCluster()
client = Client(cluster)

client.ncores()
client.restart()

customer=pd.DataFrame({
"customer_id":list(range(1,100)),
"Rank" : list(range(1,100))
})

df = dd.from_pandas(customer,npartitions=1)
df.head()

"""
Out[]:
   customer_id  Rank
0            1     1
1            2     2
2            3     3
3            4     4
4            5     5

In []: client.get_versions(check=True)['scheduler']['packages']
Out[]:
{'python': '3.8.5.final.0',
 'dask': '2021.04.0', # Also working with '2.30.0'
 'distributed': '2021.04.0', # Also working with '2.30.1'
 'msgpack': '1.0.0',
 'cloudpickle': '1.6.0',
 'tornado': '6.0.4',
 'toolz': '0.11.1',
 'numpy': '1.20.2', # Also working with '1.18.1'
 'lz4': None,
 'blosc': None}

# Same output for: client.get_versions(check=True)['client']['packages']
"""
```

Could you confirm if you've been able to get your example to run on _any_ other combination of OS and `dask`/`distributed` versions, besides the ones you've referenced?
If not - this could narrow it down to a possible WSL-related issue.

**Comment by jrbourbeau** [comment] 2021-06-10 19:04
Closing for now as it seems we're having trouble reproducing. @bhagatsajan0073 let us know if you'd like to pick this up again

**Closed by jrbourbeau** 2021-06-10 19:04 UTC
Labels: needs info
