### ISSUE TITLE
as_completed doesn't return already completed tasks when data was scattered first

### ISSUE THREAD

**Issue by wyegelwel** [dask/distributed#2038] opened 2018-06-07 19:55 UTC
Ok, this is a weird one. If you have a dask task and pass it to as_completed, it will return that task when it is completed. If you pass an already completed task to as_completed, it will still do the correct thing. Except, if the task was created by passing it scattered data and then not holding onto the scattered future.

Repro:

Set up:

```python
import distributed

cluster = distributed.LocalCluster()
dask_client = distributed.Client(cluster)

def bad_fn(x):
    raise Exception('lol')

fut = dask_client.submit(bad_fn, dask_client.scatter(1))
list(distributed.as_completed([fut]))
list(distributed.as_completed([fut]))
```

Returns an empty list.

However, 

```python
fut = dask_client.submit(bad_fn, 1)
list(distributed.as_completed([fut]))
list(distributed.as_completed([fut]))
```

and 

```python
scattered = dask_client.scatter(1)
fut = dask_client.submit(bad_fn, scattered)
list(distributed.as_completed([fut]))
list(distributed.as_completed([fut]))
```

Return a list with the future in it.

Interestingly I can't reproduce this if the task doesn't raise an exception.

**Comment by mrocklin** [comment] 2018-06-11 18:13
Yup, that's an odd one.  It looks like the scattered future was told that it could be released:

```python
In [3]: s = cluster.scheduler

In [5]: s.transition_log
Out[5]: 
deque([('bad_fn-34ef2fea0c40f1429b2afdaa11c80750',
        'released',
        'waiting',
        OrderedDict([('bad_fn-34ef2fea0c40f1429b2afdaa11c80750',
                      'processing')]),
        1528740584.7117703),
       ('bad_fn-34ef2fea0c40f1429b2afdaa11c80750',
        'waiting',
        'processing',
        {},
        1528740584.7120674),
       ('bad_fn-34ef2fea0c40f1429b2afdaa11c80750',
        'processing',
        'erred',
        {},
        1528740584.7223704),
       ('int-c0a8a20f903a4915b94db8de3ea63195',
        'memory',
        'released',
        OrderedDict([('int-c0a8a20f903a4915b94db8de3ea63195', 'forgotten')]),
        1528740584.7263565),
       ('int-c0a8a20f903a4915b94db8de3ea63195',
        'released',
        'forgotten',
        {'bad_fn-34ef2fea0c40f1429b2afdaa11c80750': 'forgotten'},
        1528740584.7264178),
       ('bad_fn-34ef2fea0c40f1429b2afdaa11c80750',
        'erred',
        'forgotten',
        {},
        1528740584.7264576)])
```

This isn't wrong necessarily, no one can use it except for the future that just erred and it won't need it any longer.  However when the scattered future went away I suspect that it cancelled all of its dependencies.  Probably it should leave those that are in memory or erred alive.

**Comment by mrocklin** [comment] 2018-06-11 18:20
It looks like this was a typo in the scheduler.  Resolved in https://github.com/dask/distributed/pull/2047

Thank you for the nice reproducible example @wyegelwel .  This was quite helpful.

**Closed** 2018-06-11 20:33 UTC

**Comment by wyegelwel** [comment] 2018-06-11 20:44
Thanks for the fast reply and fix @mrocklin!
