### ISSUE TITLE
capability to publish xarray dataset 

### ISSUE THREAD

**Issue by petacube** [dask/distributed#1329] opened 2017-08-12 19:46 UTC
Hi, i am interested in developing capability of publishing distributed xarray dataset 
did anybody looked into it before?

Stanislav Seltser
Petacube

**Comment by shoyer** [comment] 2017-08-12 22:07
Closing this as a duplicate of https://github.com/dask/distributed/issues/1261. @mrocklin wrote some guidance there, all of which looks quite doable.

**Closed** 2017-08-12 22:08 UTC
