### ISSUE TITLE
Incompatibility with Bokeh 3.0.1

### ISSUE THREAD

**Issue by luminosa42** [dask/distributed#7263] opened 2022-11-07 12:35 UTC
**Describe the issue**:  

Bokeh had a recent upgrade from 2.4 to 3.0 and some of the variables used are renamed. When using the latest version of distributed with latest version of Bokeh, an import error occurs. 

**Minimal Complete Verifiable Example**:

from dask.distributed import Client
Client.get_task_stream()
            
_The error message is:_ 
/usr/local/lib/python3.9/site-packages/distributed/client.py:4589: in _get_task_stream
distributed.dashboard.components.scheduler import task_stream_figure
ImportError: cannot import name 'Panel' from 'bokeh.models' (/usr/local/lib/python3.9/site-packages/bokeh/models/__init__.py)
/usr/local/lib/python3.9/site-packages/distributed/dashboard/components/scheduler.py:17: ImportError

**Anything else we need to know?**: 
For this specific error, Panel has been renamed into TabPanel in Bokeh 3.0.
Here is the full Bokeh migration guide in case of checking all the changes: https://github.com/bokeh/bokeh/wiki/Migration-Guides

**Environment**:

- Dask version: 2022.10.2
- Python version: 3.9
- Operating System: Linux
- Install method (conda, pip, source): pip
- Other packages: Tornado=6.1, Bokeh=3.0.1

**Comment by jrbourbeau** [comment] 2022-11-07 21:22
Thanks @luminosa42! We're currently working on `bokeh=3` compatibility (xref https://github.com/dask/distributed/issues/7173). For now I'd recommend using `bokeh < 3`. Closing as a duplicate of https://github.com/dask/distributed/issues/7173 for now

**Closed by jrbourbeau** 2022-11-07 21:22 UTC
