### ISSUE TITLE
Include timestamps in log format by default?

### ISSUE THREAD

**Issue by gjoseph92** [dask/distributed#5649] opened 2022-01-11 17:30 UTC
There is a lot of work to do to improve the quality of our logging: https://github.com/dask/distributed/issues/4762. In lieu of that though, should we consider adding the timestamp [`%(asctime)`](https://docs.python.org/3/library/logging.html#logging.Formatter.format) to the default `distributed.admin.log-format` string?
https://github.com/dask/distributed/blob/1bab9e54b2199f0b49934b7e84e10b449cd5fef2/distributed/distributed.yaml#L267

As discussed in #4762, it's very hard to figure out causality from logs right now. Adding timestamps would at least give you a better guess as to how close in time things are happening, and help matching up with worker logs, which would help get a better sense of causality for now.

cc @jrbourbeau @fjetter @sevberg

**Comment by jrbourbeau** [comment] 2022-01-11 17:56
Thanks @gjoseph92 -- closing as a duplicate of https://github.com/dask/distributed/issues/1650

**Closed by jrbourbeau** 2022-01-11 17:56 UTC
Labels: diagnostics
