### ISSUE TITLE
GPU scheduler cannot start in windows due to use of nvml diagnostics

### ISSUE THREAD

**Issue by lmeyerov** [dask/distributed#5628] opened 2021-12-24 01:03 UTC
**Edit 1: Maybe no longer an issue?** Attempt to work around wsl @ https://github.com/dask/distributed/pull/5568

**Edit 2: Related upstream nvml issue**: I filed https://github.com/gpuopenanalytics/pynvml/issues/42

--

The full issue is in https://github.com/rapidsai/cudf/issues/9955

---

The interesting parts wrt `dask.distributed`:

https://github.com/dask/distributed/blob/96ee7f7b2cdaac5a23f4e5221083f0bdcff8b862/distributed/system_monitor.py#L132

=>

https://github.com/dask/distributed/blob/96ee7f7b2cdaac5a23f4e5221083f0bdcff8b862/distributed/diagnostics/nvml.py#L128-L133

=>

https://github.com/dask/distributed/blob/96ee7f7b2cdaac5a23f4e5221083f0bdcff8b862/distributed/diagnostics/nvml.py#L100-L104

_get_memory_used() uses a working nvml call, but _get_utilization() fails on pynvml.nvmlDeviceGetUtilizationRates(h) throwing `pynvml.nvml.NVMLError_Unknown` instead of ` pynvml.NVMLError_NotSupported` . An exception here is reasonable (see original issue), but `dask.distributed` is not handling the exn that `pynvml` throws.

---

A separate issue is _why_ `pynvml `receives and propagates an unknown error code in wls2 and whether it can switch to `NVMLError_NotSupported` , but in the meanwhile, `dask.distributed` should probably just warn and continue on this case. I'll file an upstream `pynvml` issue, but suspect it may have an arbitrarily long ETA, so should work around here.

**Comment by lmeyerov** [comment] 2021-12-24 01:09
Also of relevance is this PR: https://github.com/dask/distributed/pull/5568

**Comment by jrbourbeau** [comment] 2022-01-05 20:30
Thanks for raising an issue @lmeyerov 

> Edit 1: Maybe no longer an issue? Attempt to work around wsl @ #5568

Yeah, I'm not sure if this has already been resolved or not since we've disabled NVML monitoring on WSL (xref https://github.com/dask/distributed/pull/5568). Could you try with the `main` branch of `distributed` to see if the issue you're having is still present? 

cc @pentschev @charlesbluca for visibility

**Comment by charlesbluca** [comment] 2022-01-05 20:46
This should be resolved with #5568 as that blocks the calls to `nvmlDeviceGetUtilizationRates` altogether, but I am interested in the fact that you got `NVMLError_Unknown` instead of `NVMLError_NotSupported` - do you still get an unknown error when running a minimal reproducer?

```python
from pynvml import *

nvmlInit()

h = nvmlDeviceGetHandleByIndex(0)
nvmlDeviceGetUtilizationRates(h)
```

If so, then we might be able to isolate this issue to PyNVML specifically; I get a `NVMLError_NotSupported` from the above with PyNVML 11.0.0.

**Comment by lmeyerov** [comment] 2022-01-08 22:45
Some reason I'm now seeing the expected `NotSupported` so I think we can close for now, and watch for if my system or anyone else starts seeing `Unknown` again

**Comment by jrbourbeau** [comment] 2022-01-10 23:56
Thanks @lmeyerov @charlesbluca -- closing in favor of https://github.com/rapidsai/cudf/issues/9955

**Closed by jrbourbeau** 2022-01-10 23:56 UTC
Labels: needs info
