### ISSUE TITLE
 'NoneType' object has no attribute 'read_bytes'

### ISSUE THREAD

**Issue by rames037** [dask/distributed#5292] opened 2021-08-31 22:27 UTC
import dask
from dask.delayed import delayed
from dask.distributed import Client, progress
client = Client(threads_per_worker=72, n_workers=16)

I never used to get this error - I used to use dask extensively on databricks till 3 months ago and a lot of work depends on dask.delayed - Im getting this 'NoneType' object has no attribute 'read_bytes' when I ran it today - I have no idea of how to diagnose this.

- Dask version: 2021.08.1
- Python version: 3.7.5
- Operating System: DataBricks 
- Install method (conda, pip, source): pip

**Comment by jrbourbeau** [comment] 2021-08-31 22:39
Thanks for raising an issue @rames037. Are you able to provide any additional information? For example a traceback or cluster logs? 

It's difficult to say without any additional information, but this may be a duplicate of https://github.com/dask/distributed/issues/5277 and https://github.com/dask/distributed/issues/5254 which were resolved by https://github.com/dask/distributed/pull/5257

**Comment by joni-herttuainen** [comment] 2021-09-01 10:56
I have the same issue. Everything is working ok for `2021.8.0` but failing with `2021.8.1`. 
I am running it with `dask_mpi==2.21.0` and it fails already on `dask_mpi.initialize()`. 

Traceback:
```
Traceback (most recent call last):
    ...
    dask_mpi.initialize(local_directory='./dask_dump')
  File ".../venv/lib/python3.7/site-packages/dask_mpi/core.py", line 69, in initialize
    asyncio.get_event_loop().run_until_complete(run_scheduler())
  File ".../lib/python3.7/asyncio/base_events.py", line 579, in run_until_complete
    return future.result()
  File ".../venv/lib/python3.7/site-packages/dask_mpi/core.py", line 63, in run_scheduler
    dashboard_address=dashboard_address,
  File ".../venv/lib/python3.7/site-packages/distributed/scheduler.py", line 3809, in __init__
    **kwargs,
  File ".../venv/lib/python3.7/site-packages/distributed/scheduler.py", line 1978, in __init__
    super().__init__(**kwargs)
  File ".../venv/lib/python3.7/site-packages/distributed/core.py", line 160, in __init__
    self.monitor = SystemMonitor()
  File ".../venv/lib/python3.7/site-packages/distributed/system_monitor.py", line 64, in __init__
    self.update()
  File ".../venv/lib/python3.7/site-packages/distributed/system_monitor.py", line 110, in update
    read_bytes_disk = (disk_ioc.read_bytes - last_disk.read_bytes) / (
AttributeError: 'NoneType' object has no attribute 'read_bytes'
```

**Comment by rames037** [comment] 2021-09-01 16:55
So I used conda install based on one of the other issues raised, and it worked

**Closed** 2021-09-01 16:54 UTC
Labels: needs info
