### ISSUE TITLE
Dangling stream when program exits

### ISSUE THREAD

**Issue by jsonjunky** [dask/distributed#1064] opened 2017-05-05 23:26 UTC
Hi,
  Not sure if this is a bug. There is no "close()" method on Client objects, but when my python program exits, I always see this.

distributed.comm.tcp - WARNING - Closing dangling stream in <TCP 'tcp://54.158.230.6:8786'>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP 'tcp://54.158.230.6:8786'>
Exception in thread Thread-6 (most likely raised during interpreter shutdown):
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
  File "/usr/lib/python2.7/threading.py", line 754, in run
  File "/home/radiant/radiantfind/python/radiant/local/lib/python2.7/site-packages/tornado/ioloop.py", line 904, in start
<type 'exceptions.AttributeError'>: 'NoneType' object has no attribute '_current'

**Comment by mrocklin** [comment] 2017-05-06 01:08
What version are you running?

import distributed
distributed.__version__

**Comment by jsonjunky** [comment] 2017-05-06 01:21
>>> import distributed
>>> distributed.__version__
u'1.16.3'
>>>

**Comment by mrocklin** [comment] 2017-05-06 15:49
cc @pitrou any thoughts?

**Comment by pitrou** [comment] 2017-05-06 15:56
@jsonjunky, do you have a small reproducer?

**Comment by jsonjunky** [comment] 2017-05-07 20:19
Here is the smallest test. Using a remote dask scheduler. Do you want my pip freeze for this interpreter?

>>> from dask.distributed import Client
>>> client = Client("XX.211.XX.XX:8786")
>>> <ctrl-d>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP 'tcp://XX.211.XX.XX:8786'>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP 'tcp://XX.211.XX.XX:8786'>

**Comment by pitrou** [comment] 2017-05-10 16:35
Ok. According to my observations, the answer is the Client is not garbage-collected if you don't call Client.shutdown() explicitly (and/or use a context manager such as `with Client(...)`). The reason is probably that the client's event loop, which is running in a separate background thread, is holding references to the client, so even deleting all references from the client in your environment does not make the object vanish.

Ideally we would find a way to garbage-collected the Client (and close its thread and communications) when all user-visible references to it vanish, but due to the afore-mentioned problem, it is harder than it may seem at first.

**Comment by pitrou** [comment] 2017-05-10 16:36
That said, the warnings are specific to Python 2 and they are related to an issue in our compatibility code.

**Comment by pitrou** [comment] 2017-05-10 16:53
PR #1073 should fix the warnings, at least in the simple case of the global client still running at exit.

**Comment by jsonjunky** [comment] 2017-05-10 18:21
I really appreciate that. I will try to use context when possible but I created a Dask function decorator that accepts a strategy singlton and when this is client.get it is forced to be global. Maybe not a great design in that respect but for my modules there's no need to always create and tear down clients. Use just one singleton.

**Closed** 2017-05-10 19:50 UTC

**Comment by summerela** [comment] 2018-12-27 01:37
I'm getting these warnings in python3.6. 

    import dask
    from dask import dataframe as dd
    import dask.multiprocessing
    import multiprocessing as mp
    from dask.distributed import Client

    # import logger
    log = logging.getLogger(__name__)

    class Parse_files():
    
        # instance parameters
        def __init__(self, 
                 input_s6,
                 output_dir, 
                 target_fa, 
                 mutation_file, 
                 encoder_file):
        self.input_s6 = input_s6
        self.output_dir = output_dir
        self.target_fa = target_fa
        self.mutation_file = mutation_file
        self.encoder_file = encoder_file
        self.workers = (mp.cpu_count()-1)*2
        self.client= Client()

    def read_s6(self, input_s6):
        
        print("Reading in S6 file...\n")
        
        # specify S6 datatypes
        dtypes = {'Features':'str',
          'fov': 'uint8',
          'x': 'uint8',
          'y': 'uint8'}
        
        # read in S6 file and create feature id's
        df = dd.read_csv(input_s6, dtype=dtypes, blocksize=1024*1024)
        df = self.client.persist(df)
        
        #Remove cheeky comma column, if it exists
        df = df.loc[:,~df.columns.str.contains('^Unnamed')]
        
        #Remove whitespace from column headers
        df.columns = df.columns.str.strip()
        
        df["FeatureID"] = df["Features"].astype(str) + "_" + df["x"].astype(str) + "_" + df["y"].astype(str)
        df= df.drop(["Features", "fov", "x", "y"], axis=1)

        return df
    
    def melt(self, frame, id_vars=None, value_vars=None, var_name=None,
         value_name='value', col_level=None):

        from dask.dataframe.core import no_default
    
        return frame.map_partitions(pd.melt, meta=no_default, id_vars=id_vars,
                                    value_vars=value_vars,
                                    var_name=var_name, value_name=value_name,
                                    col_level=col_level, token='melt')
    
    @jit
    def pivot_s6(self, input_s6):
        
        print("Parsing S6 file...\n")
        
        # expand basecalls to one row per feature
        s6_df = self.melt(input_s6, id_vars="FeatureID")
        
        # split up pool and cycle info
        s6_df["cycle"] = s6_df['variable'].str.partition('P')[0]
        s6_df["cycle"] = s6_df["cycle"].str.partition("C")[2]
        s6_df["pool"] = s6_df['variable'].str.partition('P')[2]

        # drop variable column
        s6_df = s6_df.drop("variable", axis=1)
        
        col_map = {"FeatureID":"FeatureID",
                   "value":"BC",
                   "cycle":"cycle",
                   "pool":"pool"}
        
        s6_df = s6_df.rename(columns=col_map)
        s6_df["BC"] = s6_df.BC.astype('str')

        return s6_df
    
    def filter_s6(self, input_s6):
        
        print("Filtering S6 file...\n")
        
        # filter out rows where basecall contains uncalled bases of 0 
        pass_calls = input_s6[input_s6.BC.str.contains("0") == False]
        # filter out rows with missing digits (non 3 spotters)
        s6_df = pass_calls[pass_calls.BC.astype(int) > 111111].compute()

        
        # save raw call data to file
        s6_df_outfile = Path("{}/all3spotters.tsv".format(self.output_dir))
        s6_df.to_csv(s6_df_outfile, sep="\t", index=False)
        
        return s6_df

    
    def main_parser(self):
        
        # parse mutation file if provided
        if self.mutation_file != "none": 
            mutation_df = self.parse_mutations()
        else: 
            mutation_df = "none"
       
        # parse encoding file    
        encoding_df = self.parse_encoding()
        
        # parse input fasta file
        fasta_df = self.parse_fasta()
        
        # read in and parse S6
        s6_rows = self.read_s6(self.input_s6)
        s6_df = self.pivot_s6(s6_rows)
        
        # filtering S6 dataframe
        s6_df = self.filter_s6(s6_df)
        
        # I added this to resolve the issue.. I still get a warning about dangling processes but am able to move forward
        self.client.close()
  
        return mutation_df, s6_df, fasta_df, encoding_df

The output is correct, but I get the warnings when calling this class from another class. Please let me know if I should open a new issue?

**Comment by mrocklin** [comment] 2018-12-27 01:54
Hi @summerela .  Thanks for commenting.

If you're able to produce the errors here with the latest release then yes, that would be useful as a new issue.   It would be especially useful if you're able to produce a minimal example that generates the error.  See http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports

**Comment by summerela** [comment] 2018-12-27 19:48
@mrocklin will do!

**Comment by Nathan-Furnal** [comment] 2019-01-10 21:15
I believe I can provide a relatively minimalist example, pardon me for mistakes I'm getting started.
Running on a single laptop, Windows 10, Python 3.7, 4-cores, conda install and environment.
```
import numpy as np
import pandas as pd
from numba import jit
from dask import dataframe as dd
from dask.distributed import Client
client = Client(processes=False)
```

```
data = np.random.randint(-10, 10, (10**8, 3))
df = pd.DataFrame(data=data, columns=["A", "B", "C"], index=None)
df["F"] = np.random.choice(["apple", "banana", "orange", 
                            "pear","grape","lime","citrus","peach"],10**8)
ddf = dd.from_pandas(df,npartitions=16)

@jit
def remove_special_char_with_numba(x):
    return x.replace('r','')
```
this cell : 

```
%%timeit
ddf["F"].map_partitions(remove_special_char_with_numba).compute()
```
Provides the error : 

> distributed.comm.inproc - WARNING - Closing dangling queue in  <InProc local=inproc...

I'm not absolutelty positive that this is what you are looking for but I hope it could help nonetheless. I don't get this error when using multiprocessing though.

**Comment by summerela** [comment] 2019-01-10 21:20
Thanks @Nathan-Furnal . I'm swamped at work and have  not had time to pull down a minimal example out of our entire script. But I can assure you that this happens frequently, on CentOS.

**Comment by Nathan-Furnal** [comment] 2019-01-10 21:23
No worries @summerela I'd be interested to know why this happens though, I feel like this might be a garbage collection issue but someone more experienced might be able to shed some light on this.

**Comment by mrocklin** [comment] 2019-01-10 21:38
Thanks for providing a smaller example @Nathan-Furnal .  I wasn't able to run it on my personal machine (the data seems to be quite large) but I'm glad that others were able to reliably trigger it as well.  When I tried to run it on a smaller dataset the error didn't show up unfortunately.

I'm also interested if you need Numba to be present in order to trigger the error.  If so that seems different from what @summerela was experiencing?

**Comment by summerela** [comment] 2019-01-10 21:39
Ahhhh.. I am using Numba.

**Comment by mrocklin** [comment] 2019-01-10 21:42
Oh, I see now that there is indeed a `@jit` line in your code.  I just did a search for `numba` and didn't see anything.  Interesting!  Any further exploration you all can do would be welcome.

**Comment by Nathan-Furnal** [comment] 2019-01-10 21:42
I'm re-running the exact same code without Numba, I'll see what it says

**Comment by Nathan-Furnal** [comment] 2019-01-10 21:54
Alright, I ran the code again without using @jit and I'm getting the same issue as the in code I posted above.

**Comment by mrocklin** [comment] 2019-01-10 21:57
Are there any other elements that you're able to take out while still
getting the same issue?  One way to identify what is going wrong is to
remove parts of your computation piece by piece until the problem goes
away, and then to dig into that piece that caused the difference.

**Comment by Nathan-Furnal** [comment] 2019-01-10 22:15
Alright I re-started a Jupyter lab session with the same code but different imports, note that I'm using Numba but it doesn't cause an issue. This is all run locally on my laptop, so it seems that the default for dask dataframes doesn't create the error.

```
import numpy as np
import pandas as pd
from numba import jit
from dask import dataframe as dd

data = np.random.randint(-10, 10, (10**8, 3))
df = pd.DataFrame(data=data, columns=["A", "B", "C"], index=None)
df["F"] = np.random.choice(["apple", "banana", "orange", "pear",
                            "grape","lime","citrus","peach"],10**8)

ddf = dd.from_pandas(df,npartitions=16)

@jit
def remove_special_char_with_numba(x):
    return x.replace('r','')
```
the cell in question, no error anymore : 

```
%%timeit
ddf["F"].map_partitions(remove_special_char_with_numba).compute()
```
