### ISSUE TITLE
register_worker_plugin doesn't work as advertised

### ISSUE THREAD

**Issue by seertaak** [dask/distributed#4106] opened 2020-09-10 14:48 UTC
`register_worker_plugin` does not work as advertised. The docs provide the following example:

```
>>> client.register_worker_plugin(other_plugin, name='my-plugin')
>>> def f():
...    worker = get_worker()
...    plugin = worker.plugins['my-plugin']
...    return plugin.my_state
```

The docs also say the following:
> Registers a lifecycle worker plugin for all current and future workers.
> This registers a new object to handle setup, task state transitions and teardown for workers in this cluster. The plugin will instantiate itself on all currently connected workers. It will also be run on any worker that connects in the future.

Unfortunately, when used in the following code:
```
...
client.wait_for_workers(n) # wait for all the workers to be ready - the number is n
client.register_worker_plugin(MyPlugin(), name='my_plugin')
<do work here>
```
In the code above, sometimes the dask workers can actually use the plugin as per the first quotes snippet. Other times, I get a `KeyError`.

In order to make this work, I have to use `sleep(60)` - and pray - in order to ensure that the Dask worker actually sees the plugin.

**Comment by jsignell** [comment] 2020-11-04 18:47
I have been using worker plugins recently and haven't run into any issues. Since there isn't an example on this issue, I am going to close it for now, but if you are able to create a reproducible example @seertaak then please reopen!

**Closed by jsignell** 2020-11-04 18:47 UTC
