### ISSUE TITLE
client dashboard 404

### ISSUE THREAD

**Issue by msmicker** [dask/distributed#3741] opened 2020-04-26 22:15 UTC
With 2.15.0 of dask and dask distributed I now get 404 errors in the client dashboard. When downgrading, everything works fine. I am using a cluster.

**Comment by mrocklin** [comment] 2020-04-26 22:18
Thank you for reporting.  Were there any log messages that came out of the scheduler process?

**Comment by mrocklin** [comment] 2020-04-26 22:18
Those will be helpful to determine what went wrong.

**Comment by jrbourbeau** [comment] 2020-04-28 12:50
I'm going to close this issue for now as I suspect the 404 errors were related to https://github.com/dask/distributed/pull/3746. @msmicker feel free to re-open if you're still experiencing issues

**Closed by jrbourbeau** 2020-04-28 12:50 UTC

**Comment by msmicker** [comment] 2020-04-29 02:13
I still see this error with 2.15.1. @mrocklin  apologies but how do I check distributed logs? I am not yet scheduling anything. Simply starting the cluster and client and then opening the dashboard.

```python
from dask_jobqueue import SGECluster
from dask.distributed import Client

cluster = SGECluster(...)

cluster.adapt(minimum_jobs=5, maximum_jobs=150)

client = Client(cluster)
client
```

**Comment by mrocklin** [comment] 2020-04-29 03:18
With `SGECluster` there may be a `silence_logs=False` keyword option.  I don't remember exactly though.

**Comment by msmicker** [comment] 2020-05-06 03:45
@mrocklin just to check if logs I added via update were enough or should I try for more (e.g. with silence_logs=True)

**Comment by lenaWitterauf** [comment] 2020-05-07 11:22
I have the same problem. I'm using dask-jobqueue with a HTCondor Cluster.

**Comment by TomAugspurger** [comment] 2020-05-07 11:24
@msmicker @lenaWitterauf can you try with 2.15.2? It includes a second fix that others have reported success with.

**Comment by lenaWitterauf** [comment] 2020-05-07 12:41
@TomAugspurger  I just updated dask distributed to 2.15.2 and the dashboard worked! Thanks a lot :-)

**Comment by msmicker** [comment] 2020-05-08 20:25
Same, all is good with 2.15.2, thanks!

**Comment by elanmart** [comment] 2020-05-28 14:33
For anyone stumbling upon this issue by searching for `dask dashboard 404`:

You will see `404` if you try to run it in an environment without `bokeh` installed.

**Comment by jrbourbeau** [comment] 2020-05-28 14:38
Thanks for engaging @elanmart. There's an open PR (xref https://github.com/dask/dask/pull/6215) to add a note to the docs about getting 404 errors when `bokeh` isn't installed. Hopefully that will help others running into this issue

**Comment by elanmart** [comment] 2020-05-28 14:41
@jrbourbeau oops, in that case apologies for adding noise, thanks for the reference!

**Comment by mrocklin** [comment] 2020-05-28 14:46
Perhaps we should include a vanilla route under `/status` (the common
entry point for Bokeh users) that says "please install bokeh" with some
conda/pip install lines if Bokeh isn't installed.  The relevant code is
probably in distributed/http/scheduler/info.py .  I suspect that someone
even very mildly familiar with web programming could accomplish this by
copying examples that are already there.

**Comment by mrocklin** [comment] 2020-05-28 15:01
@dankerrigan you might find this interesting

**Comment by jrbourbeau** [comment] 2020-05-28 15:06
That seems like a nice improvement @mrocklin. I've opened up a separate issue (xref https://github.com/dask/distributed/issues/3836) for tracking

**Comment by ruslaniv** [comment] 2020-06-15 17:23
> For anyone stumbling upon this issue by searching for `dask dashboard 404`:
> 
> You will see `404` if you try to run it in an environment without `bokeh` installed.
I have bokeh installed bu unfortunately I'm still getting 404: Not Found when visiting dashboard address.

**Comment by JohnEmhoff** [comment] 2020-06-16 03:45
Same here:

```
$ /deploy/env/bin/pip freeze | grep bokeh
bokeh==2.1.0
$ curl localhost:8787
<html><title>404: Not Found</title><body>404: Not Found</body></html>
```

**Comment by JohnEmhoff** [comment] 2020-06-16 03:56
If it helps, this reliably reproduces it for me:

```
$ virtualenv -p python3 dask
$ source dask/bin/activate
$ pip install 'dask[distributed,diagnostics]'
$ pip freeze | grep bokeh
bokeh==2.1.0
$ pip freeze | grep dask
dask==2.18.1
$ dask-scheduler
# localhost:8787 now 404s
```

**Comment by mrocklin** [comment] 2020-06-16 13:31
Yes, reproduced.  It looks like an internal function in bokeh moved in bokeh 2.1.0.  I'll resolve this on our end.  In the meantime, I recommend downgrading to bokeh 2.0.

In the future, I also recommend raising a new issue rather than commenting on an old one, although the symptoms are the same as this old issue, the cause is entirely new.

**Comment by JohnEmhoff** [comment] 2020-06-16 13:33
Thanks! Apologies, the issue seemed pretty fresh.

**Comment by mrocklin** [comment] 2020-06-16 13:33
No need to apologize, and thank you for providing explicit steps to reproduce.  This is a serious issue and I thank you for catching and reporting it.

**Comment by mrocklin** [comment] 2020-06-16 13:44
OK, the critical fix is in here: https://github.com/dask/distributed/pull/3904

Additionally, it looks like there is a deserialiation warning here: https://github.com/dask/distributed/issues/3905

**Comment by jacobtomlinson** [comment] 2020-06-17 10:46
Given that doing a naive install of Dask like `conda create -n newenv python=3.7 dask` will result in the dashboard not working should we consider pushing a `2.18.1` release of distributed which just pins bokeh to `2.0` (i.e branch from last tag and change requirements only)?

For completeness you can do an install like `conda create -n newenv python=3.7 dask bokeh=2.0` and you'll be fine, but I just wasted 30 minutes working that out.

cc @mrocklin @jrbourbeau

**Comment by CMCDragonkai** [comment] 2020-10-09 02:56
I'm seeing this as well, and I've got bokeh installed.

Also shouldn't this issue be reopened?

**Comment by jrbourbeau** [comment] 2020-10-09 03:40
@CMCDragonkai I'd recommend opening a new issue with a minimal reproducer

**Comment by ahuang11** [comment] 2020-11-20 16:48
I am also getting this:
![image](https://user-images.githubusercontent.com/15331990/99826360-defb7700-2b1d-11eb-97af-cfbd4b371858.png)
```
from dask.distributed import Client

client = Client()
client
```
![image](https://user-images.githubusercontent.com/15331990/99826383-e589ee80-2b1d-11eb-8f0c-c30581208d80.png)
