### ISSUE TITLE
cant client.upload_file(str)

### ISSUE THREAD

**Issue by xxxxsk** [dask/distributed#5137] opened 2021-07-29 13:01 UTC
When I was deploying my project， I can't  import func from my *.py, and there is a FileNotFoundError after client.upload_file('')

The directory structure
dask_test
 - run.sh
 - test.py
 - upload_file.py
 
run.sh:
```
/opt/anaconda3/envs/pymodel/bin/dask-yarn submit \
  --environment python:///opt/anaconda3/envs/pymodel/bin/python \
  --worker-count 5 \
  --worker-vcores 2 \
  --worker-memory 4GiB \
  test.py
```

test.py:
```python
from dask_yarn import YarnCluster
from dask.distributed import Client
import time
import pandas as pd
import os

cluster = YarnCluster.from_current()
client = Client(cluster)

def square(x):
    return x ** 2
ts = time.time()
client.upload_file('upload_file.py')
A = client.map(square, range(5))
total = client.submit(sum, A)
print(total.result())
print('1cost time :%s'%(time.time()-ts))
client.close()
cluster.close()
```

**Anything else we need to know?**:
I want to konw how to correctly upload file and import ?

**Environment**:

- Dask version:2.11.0
- Python version:3.6.10
- Install method (conda, pip, source):pip

**Comment by jrbourbeau** [comment] 2021-07-29 14:10
This looks like a duplicate of https://github.com/dask/distributed/issues/5137. Closing in favor of the other issue

**Closed by jrbourbeau** 2021-07-29 14:10 UTC
