### ISSUE TITLE
Timeout OSError while running dask on local cluster

### ISSUE THREAD

**Issue by ghltshubh** [dask/distributed#3802] opened 2020-05-15 16:31 UTC
I am trying to run the following code on a Power PC with config:

    Operating System: Red Hat Enterprise Linux Server 7.6 (Maipo)
    CPE OS Name: cpe:/o:redhat:enterprise_linux:7.6:GA:server
              Kernel: Linux 3.10.0-957.21.3.el7.ppc64le
        Architecture: ppc64-le

single node localcluster with 20 cores.

    import os, subprocess
    from timeit import default_timer as timer
    from dask.distributed import Client, LocalCluster, fire_and_forget, as_completed
    
    def run_client(n_workers):
        files = []
        for dirpaths, dirnames, filenames in os.walk('cap_logs/'):
            if not dirnames:
                files.extend([os.path.join(dirpaths, file) for file in filenames])
    
        def parser(file):
            val = subprocess.run(['./test.sh', file], stdout=subprocess.PIPE)
            return val.stdout.decode()
    
        cluster = LocalCluster(n_workers=n_workers, dashboard_address=None)
        with Client(cluster) as client:
            futures = []
            files = client.scatter(files)
            futures = client.map(parser, files)
            results = [future.result() for future in as_completed(futures)]
            del futures
            cluster.close()
    
    workers = [20, 18, 16, 14, 12, 10, 8, 7, 6, 5, 4, 3, 2, 1]
    times = {}
    for n_workers in workers:
        tic = timer()
        run_client(n_workers)
        toc = timer()
        time = toc - tic
        times[n_workers] = round(time, 2)

It works fine if n_workers is relatively smaller (<15) than the total num of cores i.e. 20 but as soon as I set n_workers to be >15 it gives the following error:

    OSError: Timed out trying to connect to 'tcp://127.0.0.1:34487' after 10 s: connect() didn't finish in time

**Comment by ghltshubh** [comment] 2020-05-15 17:43
@jrbourbeau Sorry I forgot to mention that.
They are pretty straight forward. Create a directory structure for caps_logs as follows (touch file1, file2....):
```
caps_logs/
|
|-dir1/
|   |
|   |-file1, file2
|
|-dir2/
    |
    |-file3, file4

```
and the test.sh just echos that file name i.e. it has only 1 line in it:
`echo $1`

**Comment by jrbourbeau** [comment] 2020-05-15 18:11
Closing as a duplicate of https://github.com/dask/distributed/issues/3804

**Closed by jrbourbeau** 2020-05-15 18:11 UTC

**Comment by ghltshubh** [comment] 2020-05-15 18:14
@jrbourbeau But the error is different probably because of number of workers?

**Comment by jrbourbeau** [comment] 2020-05-15 18:20
As the code snippet is the same, I'd prefer to consolidate conversation to https://github.com/dask/distributed/issues/3804 for the time being if that's okay. If there are two separate bugs, then we can spin out into two separate issues
