### ISSUE TITLE
500 Internal Server Error when clicking on graph in the dashboard

### ISSUE THREAD

**Issue by SimplicityGuy** [dask/distributed#5027] opened 2021-07-06 00:25 UTC
**What happened**:
When clicking on the `GRAPH` function on the dashboard, I get a 500, Internal Server Error. This is the exception:
```python3
tornado.application - ERROR - Uncaught exception GET /graph (192.168.1.163)
HTTPServerRequest(protocol='http', host='nox:8787', method='GET', uri='/graph', version='HTTP/1.1', remote_ip='192.168.1.163')
Traceback (most recent call last):
  File "/home/datum/.local/lib/python3.7/site-packages/tornado/web.py", line 1704, in _execute
    result = await result
  File "/home/datum/.local/lib/python3.7/site-packages/bokeh/server/views/doc_handler.py", line 52, in get
    session = await self.get_session()
  File "/home/datum/.local/lib/python3.7/site-packages/bokeh/server/views/session_handler.py", line 120, in get_session
    session = await self.application_context.create_session_if_needed(session_id, self.request, token)
  File "/home/datum/.local/lib/python3.7/site-packages/bokeh/server/contexts.py", line 218, in create_session_if_needed
    self._application.initialize_document(doc)
  File "/home/datum/.local/lib/python3.7/site-packages/bokeh/application/application.py", line 171, in initialize_document
    h.modify_document(doc)
  File "/home/datum/.local/lib/python3.7/site-packages/bokeh/application/handlers/function.py", line 132, in modify_document
    self._func(doc)
  File "/home/datum/.local/lib/python3.7/site-packages/distributed/dashboard/components/scheduler.py", line 2257, in graph_doc
    graph = TaskGraph(scheduler, sizing_mode="stretch_both")
  File "/home/datum/.local/lib/python3.7/site-packages/distributed/dashboard/components/scheduler.py", line 1550, in __init__
    self.layout = GraphLayout(scheduler)
  File "/home/datum/.local/lib/python3.7/site-packages/distributed/diagnostics/graph_layout.py", line 42, in __init__
    priority=priority,
  File "/home/datum/.local/lib/python3.7/site-packages/distributed/diagnostics/graph_layout.py", line 48, in update_graph
    stack = sorted(tasks, key=lambda k: priority.get(k, 0), reverse=True)
TypeError: '<' not supported between instances of 'NoneType' and 'tuple'
```

**What you expected to happen**:
Graph should work.

**Minimal Complete Verifiable Example**:
```python3
### NOTE: RUN THIS WITH ONLY A SINGLE WORKER. RUNNING THIS WITH MULTIPLE WORKER NODES YIELDS https://github.com/joblib/joblib/issues/1201. ###

import json
from itertools import chain

import numpy as np
import pandas as pd
from dask.distributed import Client
from joblib import Parallel, delayed, parallel_backend
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.neighbors import NearestNeighbors


def get_top_n_match(row, n=2):
    row_count = row.getnnz()
    if row_count == 0:
        return None
    elif row_count <= n:
        result = zip(row.indices, row.data)
    else:
        arg_idx = np.argpartition(row.data, -n)[-n:]
        result = zip(row.indices[arg_idx], row.data[arg_idx])
    return sorted(result, key=(lambda x: -x[1]))


def match_name(input_name, vectorizer, name_vectors, name_df, n=2):
    input_name_vector = vectorizer.transform([input_name])
    result_vector = input_name_vector.dot(name_vectors.T)
    matched_data = [get_top_n_match(row, n) for row in result_vector]
    flat_matched_data = [
        tup for data_row in matched_data if data_row is not None for tup in data_row
    ]
    if len(flat_matched_data) == 0:
        return []
    lkp_idx, lkp_sim = zip(*flat_matched_data)
    nr_matches = len(lkp_idx)
    matched_names = [None] * nr_matches
    for i in range(nr_matches):
        matched_names[i] = {
            "match": name_df["name"].iloc[lkp_idx[i]],
            "score": lkp_sim[i] * 100,
            "c.file": input_name,
        }
    return matched_names


def ngrams(string, n=3):
    fraction = 1 / 3
    limit = int(len(string) * fraction)
    string = f" {string[0:limit]} {string} "
    return ["".join(ngram) for ngram in zip(*[string[i:] for i in range(n)])]


print(f"Dask cluster starting...")
client = Client("localhost:8786")
values = pd.DataFrame(np.random.rand(5000, 2), columns=["id", "name"])
values["name"] = values["name"].astype(str)
files = pd.DataFrame(np.random.rand(750, 2), columns=["file", "c.file"])
files["file"] = files["file"].astype(str)
files["c.file"] = files["c.file"].astype(str)
print(f"... values shape {values.shape}")
print(f"... files shape {files.shape}")


vectorizer = TfidfVectorizer(
    analyzer=ngrams, encoding="ascii", stop_words="english", strip_accents="ascii"
)
tf_idf_matrix = vectorizer.fit_transform(values["name"])
print(f"... tf-idf shape {tf_idf_matrix.shape}")

n = 2
with parallel_backend("dask"):
    results = Parallel(n_jobs=-1, verbose=10)(
        delayed(match_name)(fn, vectorizer, tf_idf_matrix, values, n)
        for fn in files["c.file"]
        if len(fn) != 0
    )

matches = pd.DataFrame(list(chain(*results)))
print(f"... matches shape {matches.shape}")

matched = pd.merge(files, matches)
print(f"... matched shape {matched.shape}")
```

**Anything else we need to know?**:

**Environment**:

- Dask version: `2021.6.2`
- Python version: `3.7.3`
- Operating System: `Debian 10`
- Install method (conda, pip, source): `pip`

**Comment by jrbourbeau** [comment] 2021-07-06 20:56
Thanks for raising an issue and nice example @SimplicityGuy. I'm able to reproduce the `TypeError`. It looks like there was a previous attempt to resolve this issue over in https://github.com/dask/distributed/pull/2337, however it's been a while since that issue was updated. Is this something you're interested in working on? (no obligation though)

**Comment by SimplicityGuy** [comment] 2021-07-06 23:59
@jrbourbeau Sure, let me dig into it when I have some time.

**Comment by jrbourbeau** [comment] 2021-10-14 15:00
Closing as a duplicate of https://github.com/dask/distributed/issues/2193. Thanks again for reporting @SimplicityGuy

**Closed by jrbourbeau** 2021-10-14 15:00 UTC
Labels: diagnostics
