### ISSUE TITLE
Individual bokeh plots are squashed with new Bokeh

### ISSUE THREAD

**Issue by mrocklin** [dask/distributed#7325] opened 2022-11-17 15:20 UTC
The vertical spacing seems to be gone

<img width="711" alt="Screen Shot 2022-11-17 at 9 20 11 AM" src="https://user-images.githubusercontent.com/306380/202485967-30956c74-4af2-4782-93c1-15e7985c7b75.png">

cc @jrbourbeau @bryevdv

**Comment by jrbourbeau** [comment] 2022-11-17 15:39
Thanks @mrocklin. This is a known issue with with `bokeh=3`. For now the suggestion is to use `bokeh<3`. Closing as a duplicate of https://github.com/dask/distributed/issues/7173

**Closed by jrbourbeau** 2022-11-17 15:39 UTC
