### ISSUE TITLE
Setting custom serializers does not seem to work

### ISSUE THREAD

**Issue by MennoNij** [dask/distributed#3594] opened 2020-03-19 18:18 UTC
Setting the (de)serializer during Client construction does not seem to work. Doing

```cl = LocalCluster(n_workers=n_workers, threads_per_worker=1, ip='0.0.0.0', diagnostics_port=9292)
client = Client(cl, serializers=['dask', 'pickle'], deserializers=['dask', 'pickle'])
```
and then doing a simple `.map().compute()` with a bag
gives me
```
TypeError: Data serialized with error but only able to deserialize data with ['dask', 'pickle']
```
So it seems this is already going wrong during serializing. The reason I'm trying this is because I want to add dill as a serializer.

**Comment by jrbourbeau** [comment] 2020-03-19 18:35
Thanks for raising an issue @MennoNij. Can you produce a minimal example (see https://blog.dask.org/2018/02/28/minimal-bug-reports)? I'm not able to reproduce with the following snippet:

```python
from toolz import identity
import dask.bag as db
from distributed import Client, LocalCluster

if __name__ == "__main__":

    with LocalCluster() as cluster:
        with Client(cluster,
                    serializers=['dask', 'pickle'],
                    deserializers=['dask', 'pickle']) as client:
            bag = db.from_sequence(range(10), npartitions=4)
            result = bag.map(identity).compute()
            print(f"result = {result}")
```

which doesn't raise an error and outputs 

```
result = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
```

**Comment by mrocklin** [comment] 2020-04-05 17:40
You should include the "error" serializer in your list of serializers.  Your bag computation erred, but Dask isn't comfortable deserializing your exception without explicilty being allowed to with the `"error"` serializer.

**Comment by jrbourbeau** [comment] 2020-04-14 12:56
@MennoNij did adding the `"error"` serializer and deserializer help resolve your underlying issue?

**Comment by quasiben** [comment] 2020-09-11 14:15
I'm going to close this. @MennoNij if you are still experiencing issues please feel free to reopen

**Closed by quasiben** 2020-09-11 14:15 UTC
