### ISSUE TITLE
Error importing distributed with python=3.9.0 and 3.9.1

### ISSUE THREAD

**Issue by dougiesquire** [dask/distributed#7956] opened 2023-06-29 04:11 UTC
**Describe the issue**:

(Apologies in advance if this is not worth reporting, but I thought it might be useful to have this documented so that others don’t go down the same rabbit hole I did.)

Importing recent versions of distributed using python=3.9.0 or 3.9.1 gives `TypeError: unhashable type: 'list’`. Updating Python to >=3.9.2 fixes the issue.

**Minimal Complete Verifiable Example**:

The error can be reproduced by running

```python
import distributed
```

using the versions given below

**Environment**:

- Dask version: 2023.6.1
- Python version: 3.9.0
- Operating System: Rocky Linux 8.7
- Install method (conda, pip, source): conda

**Comment by jrbourbeau** [comment] 2023-06-29 16:42
Thanks for the issue @dougiesquire, I'm able to reproduce. With the latest `distributed=2023.6.11` release on Python 3.9.1 I get the following error when I attempt to `import distributed`

```python
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/james/mambaforge/envs/test/lib/python3.9/site-packages/distributed/__init__.py", line 23, in <module>
    from distributed.actor import Actor, ActorFuture, BaseActorFuture
  File "/Users/james/mambaforge/envs/test/lib/python3.9/site-packages/distributed/actor.py", line 13, in <module>
    from distributed.client import Future
  File "/Users/james/mambaforge/envs/test/lib/python3.9/site-packages/distributed/worker_memory.py", line 55, in <module>
    WorkerDataParameter: TypeAlias = Union[
  File "/Users/james/mambaforge/envs/test/lib/python3.9/typing.py", line 262, in inner
    return func(*args, **kwds)
  File "/Users/james/mambaforge/envs/test/lib/python3.9/typing.py", line 339, in __getitem__
    return self._getitem(self, parameters)
  File "/Users/james/mambaforge/envs/test/lib/python3.9/typing.py", line 451, in Union
    parameters = _remove_dups_flatten(parameters)
  File "/Users/james/mambaforge/envs/test/lib/python3.9/typing.py", line 231, in _remove_dups_flatten
    return tuple(_deduplicate(params))
  File "/Users/james/mambaforge/envs/test/lib/python3.9/typing.py", line 205, in _deduplicate
    all_params = set(params)
TypeError: unhashable type: 'list'
```

It looks like this is coming from an upstream bug in Python itself. From reading that issue, it sounds like this only impacts Python 3.9.0 and 3.9.1 (as you mentioned). Given 3.9.2 has been out for multiple years, I'm inclined to close this issue for now with the suggestion to "Upgrade to Python 3.9.2+".

> Apologies in advance if this is not worth reporting, but I thought it might be useful to have this documented so that others don’t go down the same rabbit hole I did

No worries -- thanks for opening this up. Hopefully if someone else runs into this issue, they're search the issue tracker, land here, and know what to do.

**Closed by jrbourbeau** 2023-06-29 16:42 UTC
Labels: needs triage

**Comment by levisocool** [comment] 2023-10-26 06:16
What a coincidence, I just happened to use python3.9.0. Thanks for helping out!
