### ISSUE TITLE
Future.result() for a complete task can block under heavy load

### ISSUE THREAD

**Issue by v0lat1le** [dask/distributed#569] opened 2016-10-10 00:39 UTC
My usage is essentially this: 

``` python
futures = [executor.submit(task) for task in tasks]
for future in as_completed(futures):
        result = future.result()
```

What I find is that `future.result()` blocks for significant time when the system is under heavy load. That causes a backlog of completed tasks to build up delaying the completion unnecessarily.

Here's a way to reproduce the behaviour:
run

```
dask-scheduler
dask-worker --nthreads 1 --nprocs 1 <host>:<port>
```

and [this script](https://github.com/dask/distributed/files/518649/reproduce.txt)

The graphs show time from the task submission till `as_completed` yielding (blue) and `Future.result` returning (green)
![1worker](https://cloud.githubusercontent.com/assets/2328459/19224813/508a1dbc-8ed9-11e6-8c8f-ea67c5e12674.png)
![16_workers](https://cloud.githubusercontent.com/assets/2328459/19224854/f94d2796-8ed9-11e6-9cd0-3e8e1dab1b76.png)

You can see that in 1 worker case there's a delay between `as_completed` yielding and `Future.result` returning. Which in the 16 worker case leads to a situation where most results arrive after all the tasks are done (which is the problem I'm trying to resolve).

From what I understand this is because the worker is 'too busy' with another task to reply to the result request. Is there a way to request the result asynchronously? Do you have any other suggestions on how to work around/resolve the issue?

While the behaviour I'm getting is the same, there are a few differences between the example and my application:
- ~~tasks do release the GIL, but spend significant time in c extensions (rasterio.reproject.warp)~~
- task results are a complex nested structure (not too crazy, but still some work to serialise)

Using python 3.5.2 and distributed 1.13.2 from conda-forge channel.

EDIT: turns out my tasks do not release the GIL

**Comment by mrocklin** [comment] 2016-10-10 02:08
Interesting.  Thanks for the minimal example.  That's really helpful.  I'll have time to take a closer look at this in a couple of days.

**Comment by v0lat1le** [comment] 2016-10-10 06:24
Thanks for quick response! Turns out my tasks don't release the GIL (which might be a bug in `rasterio.warp.reproject`), so the issue might be limited to GIL-hogging tasks.

**Comment by pitrou** [comment] 2016-10-11 08:13
Indeed, if you replace `math.factorial(some large number)` with a GIL-releasing task (e.g. `zlib.compress(some large data)`), the problem more or less disappears.

**Comment by pitrou** [comment] 2016-10-11 08:19
I'm not sure there's a reasonable fix in dask. Morally, we don't want to serialize the future's result before the user asks for it -- because serializing may be a heavy task and consume undue amounts of memory and network bandwidth. It means the serializing has to be done on demand, when `.result()` is called by the client. But serializing can only be done by the process holding the result data, which -- by construction -- is the worker which ran the task in the first place; so the GIL kicks in when another task is busy running on this worker.

**Comment by pitrou** [comment] 2016-10-11 08:31
Updated reproducer script: https://gist.github.com/pitrou/5ec6ea23b179f001ab95a9015b1fcab9

**Comment by v0lat1le** [comment] 2016-10-11 10:01
In my case the problem is not the latency of the result arriving, it's the blocking call killing the throughput. Having an async way to get results would solve it for me. Something like `as_completed` but returning results/exceptions. I might be able to use `Future._result` to implement the functionality, I'll have a closer look...

I do agree there isn't much that can be done when things don't play nicely with the GIL.

**Comment by pitrou** [comment] 2016-10-11 10:08
> Having an async way to get results would solve it for me. 

I'm a bit curious. What would it solve? The delay would still be the same.

**Comment by v0lat1le** [comment] 2016-10-11 10:42
I'm expecting to be able to 'queue up' whole bunch of requests for results. By overlapping delays for multiple request the throughput should be largely unaffected.

I want my 16 worker case to look like 1 worker one (in the graphs) - there's a latency, yeah, but i'm not falling behind in handling completed tasks

**Comment by mrocklin** [comment] 2016-10-11 12:33
Using the Tornado API might be a good choice here.

```python
results = {}
@gen.coroutine
def wait_and_download(future):
    data = yield future._result()
    results[future] = data
    # do other things with data

for future in futures:
    client.loop.add_callback(wait_and_download, future)
```

**Comment by mrocklin** [comment] 2016-10-17 14:48
Any further experiences with this @v0lat1le ?

**Comment by v0lat1le** [comment] 2016-10-17 22:43
I'm filtering futures based on their state and using `gather` to get the results:
```python
finished = [future for future in futures if future.state == 'finished']
results = executor.gather(finished)
```

I was also able to ensure that my tasks release the GIL, which improved the responsiveness.

**Comment by mrocklin** [comment] 2016-12-13 15:21
Closing this for now.  Please reopen if there is something concrete that can be done on the Dask side to improve the situation.

**Closed by mrocklin** 2016-12-13 15:21 UTC
