### ISSUE TITLE
scheduler getting closed unexpectedly 

### ISSUE THREAD

**Issue by Nareshkumar23** [dask/distributed#1688] opened 2018-01-12 07:01 UTC
scheduler is getting closed unexpectedly with stream is closed msg.

The details for reproducing the issue :
csv is just 582 mb . and i am using 9 c3.xlarge instances as workers with 4 process and 1 c3.xlarge as scheduler .
but i am doing lot of dataframe operation and running some functions on them parallely.
actual code:
[code.txt](https://github.com/dask/distributed/files/1625159/code.4.txt)
log file:
[dask_log .txt](https://github.com/dask/distributed/files/1625160/dask_log.2.txt)

that is the actual code and cmd line arguments are scheduler ip with port no and no of chunks to run at a time (eg code.py x.x.x.x:yyyy 1000) and substitute the s3 path with the below csv file
https://drive.google.com/open?id=1BMHxeRBpq_dWN_fhffP5O2JQ3DdSIYVs

i could see this error in my terminal
`tornado.application - ERROR - Exception in callback functools.partial(<function wrap..null_wrapper at 0x7fb3565c4730>, {'keys': ["('loc-d5223415298072e7ae9e98e8b84112ea', 0)"], 'op': 'client-releases-keys', 'client': 'Client-5ed5b65c-f475-11e7-9312-704d7b70e106'})

Traceback (most recent call last):
File "/home/lib/python3.5/site-packages/tornado/ioloop.py", line 605, in _run_callback ret = callback()
File "/home/lib/python3.5/site-packages/tornado/stack_context.py", line 277, in null_wrapper return fn(*args, **kwargs)
File "/homelib/python3.5/site-packages/distributed/client.py",
line 677, in _send_to_scheduler_safe self.scheduler_comm.send(msg)

AttributeError: 'NoneType' object has no attribute 'send'`

**Comment by mrocklin** [comment] 2018-01-14 15:45
Unfortunately the logs don't provide a hint about what's going on.  If you're able to provide a [minimal complete verifiable example](https://stackoverflow.com/help/mcve) then that would help developers to try to reproduce your error.

**Comment by Nareshkumar23** [comment] 2018-01-16 06:33
[code.txt](https://github.com/dask/distributed/files/1633827/code.txt)
use the this code and data as given in the first comment  

unzip and use it

**Comment by mrocklin** [comment] 2018-01-16 12:24
I recommend trying to create a simpler example that fails in the same way.
It requires a lot of time to understand your code example.  This makes it
less likely that someone will help you with their free time.

**Comment by Nareshkumar23** [comment] 2018-01-20 07:04
github gist of the code [https://gist.github.com/Nareshkumar23/c50fa35abcf4723c5dae9ccabd8c578b](url)

s3 path of data is already given and its made public 

i have 50,000 embarrassingly parallel tasks to be done on single dataframe. My plan is to build and send 1,000 of those delayed tasks at a time to the cluster in batches. This throws the above error. One thing i noticed was 1,000 tasks will be processed in one or two nodes because the relevant data for the task also resides in those two nodes. To overcome this limitation, i randomized the tasks so that all nodes will be utilized. This still throws the same error as above . For better memory management , I emptied the delayed calc list.

```
              delayed_Calc.append(
                    delayed(find_something)(second_groupby, dim,  meas, first_groupby))
              
                if len(delayed_Calc) >= 1000:
                    futs = c.compute(delayed_Calc)
                    for fut in as_completed(futs):
                        result.append(fut.result())
                    futs =[]
                    delayed_Calc = []
```

**Comment by jrbourbeau** [comment] 2021-11-02 23:05
Closing due to lack of minimal reproducer (see https://blog.dask.org/2018/02/28/minimal-bug-reports for more details)

**Closed by jrbourbeau** 2021-11-02 23:05 UTC
Labels: needs info
