### ISSUE TITLE
LocalCluster CPU usage climbs to 100% over time without submitting computations, connecting workers

### ISSUE THREAD

**Issue by joseph-long** [dask/distributed#4827] opened 2021-05-18 01:03 UTC
I noticed when I was working locally in a Jupyter Lab session on my laptop that computations would gradually slow down, down, down, until there was nothing to do but restart the notebook kernel (and therefore scheduler/workers). I started to pare down a minimal reproducing example, and got all the way down to launching a LocalCluster with zero workers. After five minutes, CPU use is hovering around 100%, and a few minutes later I start getting the message `distributed.utils_perf - WARNING - full garbage collections took 19% CPU time recently` repeated every ~1s. This is all without connecting a worker or trying to do any computation.

**What happened**: Requesting a LocalCluster results in a process that grows to use 100% of the CPU even when no workers are launched and no computations are requested.

**What you expected to happen**: CPU use should remain roughly static when not under load

**Minimal Complete Verifiable Example**:

```python
from dask.distributed import Client, LocalCluster
cluster = LocalCluster(n_workers=0)
client = Client(cluster.scheduler.address)
# wait 5 minutes and check CPU use
```

![Screen Shot 2021-05-17 at 5 47 15 PM](https://user-images.githubusercontent.com/31168267/118574129-adfca780-b738-11eb-9d11-0b64e5ccf7d4.png)
![Screen Shot 2021-05-17 at 5 51 07 PM](https://user-images.githubusercontent.com/31168267/118574137-b1902e80-b738-11eb-9901-fb915b0bc0ef.png)
![Screen Shot 2021-05-17 at 5 52 10 PM](https://user-images.githubusercontent.com/31168267/118574141-b3f28880-b738-11eb-9d69-efec67760b06.png)

**Anything else we need to know?**:

I also tried setting the loop implementation to uvloop in `~/.config/dask/dask.yaml` and the issue persisted. Above screenshots are from running with the default config except for:

```yaml
logging:
  distributed: debug
  distributed.client: warning
  distributed.scheduler: debug
  bokeh: error
```

**Environment**:

- Dask version: 2021.5.0
- Python version: 3.9.4
- Operating System: macOS Big Sur 11.3.1
- Install method (conda, pip, source): conda

**Comment by joseph-long** [comment] 2021-05-18 01:15
This appears to be an interaction between JupyterLab and Dask, since running the minimal reproducing code in a plain vanilla `python` session showed ~20% CPU consistently over time.

**Comment by joseph-long** [comment] 2021-05-18 01:32
Launching `dask-scheduler` and `dask-worker` in a terminal and just connecting from JupyterLab *does* seem to result in asymptotically increasing CPU.

**Comment by jrbourbeau** [comment] 2021-05-18 15:25
Thanks for reporting this issue @joseph-long! I tried this out locally and observed similar behavior. 

cc @ian-r-rose due to the Jupyter connection

**Comment by ian-r-rose** [comment] 2021-05-18 20:32
Thanks for the ping! I wonder if this is at all related to https://github.com/dask/dask-labextension/issues/185 .

**Comment by joseph-long** [comment] 2021-05-18 20:41
Yes, seems likely. It seems limited to the labextension display of the plots. Opening up the scheduler web UI directly doesn't accumulate CPU load the same way, in my testing. If you think it's better to continue over on the labextension issue tracker, I can move over there!

[Here's](https://gist.githubusercontent.com/joseph-long/86ec211180b600116aa0eb0c60edc6fc/raw/9ff2d5b13a151f862b6e97c551c7877c1e7564d2/trace.json) a py-spy / speedscope.app profile trace of the scheduler that (if I'm reading it correctly) indicates most of the time is spent in Bokeh:

![image](https://user-images.githubusercontent.com/31168267/118720533-8d872880-b7de-11eb-8f75-f0fde63d8557.png)


[View in speedscope](https://www.speedscope.app/#profileURL=https%3A%2F%2Fgist.githubusercontent.com%2Fjoseph-long%2F86ec211180b600116aa0eb0c60edc6fc%2Fraw%2F9ff2d5b13a151f862b6e97c551c7877c1e7564d2%2Ftrace.json)

**Comment by ian-r-rose** [comment] 2021-05-18 22:56
Fix open, if you care to take it for a spin @joseph-long: https://github.com/dask/dask-labextension/pull/188

**Comment by joseph-long** [comment] 2021-05-19 01:58
Unrelated issue but following the development install instructions I ran in to this:
```
$ jupyter labextension develop . --overwrite
Traceback (most recent call last):
  File "/Users/josephlong/devel/dask-labextension/setup.py", line 8, in <module>
    from jupyter_packaging import (
ModuleNotFoundError: No module named 'jupyter_packaging'
An error occured.
FileNotFoundError: The Python package `.` is not a valid package, it is missing the `setup.py` file.
```

Had to pip install manually and then install worked. 

Anyway, I've been running the PR version for a few minutes now and CPU use is constant! Hooray!

**Comment by ian-r-rose** [comment] 2021-06-02 23:58
I've published a patch release of `dask-labextension` which avoids this behavior.  It doesn't fix any underlying reference leaks on the scheduler, but should make it much less likely that users will run into them.

A small reproducer for this which is independent of using JupyterLab:

In one terminal:

```bash
dask-scheduler --dashboard-address :33102
```

Run a small python script:
```python
import requests
import time

while True:
    requests.get("http://localhost:33102")
    time.sleep(.1)
```

watch CPU for the process climb.

A fair criticism here is that this may not be the best way of checking alive-ness of the dashboard, and I would welcome other ideas :)

**Comment by joseph-long** [comment] 2021-06-03 00:05
It's like you read my mind. I was just checking in to see if the PR had made it into a release!

**Comment by jrbourbeau** [comment] 2021-06-03 00:46
Thanks @ian-r-rose! @joseph-long do you mind trying out the new `dask-labextension` release and letting us know if it fixes the issues you were seeing?

**Comment by jrbourbeau** [comment] 2021-06-10 19:00
Closing this issue as being resolved by https://github.com/dask/dask-labextension/pull/188. @joseph-long let us know if you want us to reopen

**Closed by jrbourbeau** 2021-06-10 19:00 UTC

**Comment by joseph-long** [comment] 2021-06-10 19:01
Tried the new release and it worked for me, but forgot to comment. Thanks!
