### ISSUE TITLE
only one worker used out of 2 available 

### ISSUE THREAD

**Issue by alokgogate** [dask/distributed#2097] opened 2018-07-06 08:28 UTC
I have 3 machines (physical). One is the scheduler, and 2 separate machines for workers (one worker process on both machines respectively). When I submit a dask_xgboost job I can see that only one worker is being used and not all of them. Any clue as to why this may be happening? Also when I submit 2 jobs simultaneously, then also only one worker is being used. 

dask - 0.16.1   
dask-glm - 0.1.0    
dask-ml - 0.6.0    
dask-searchcv - 0.2.0    
dask-xgboost - 0.1.5

**Comment by lesteve** [comment] 2018-07-06 08:49
Not familiar with dask-xgboost at all, but this may be more appropriate to open an issue in https://github.com/dask/dask-xgboost. 

Have you looked at the [dashboard](http://distributed.readthedocs.io/en/latest/web.html) to try to understand what was going on? This [dask-xgboost demo video](https://www.youtube.com/watch?v=Cc4E-PdDSro&feature=youtu.be) may help as well.

**Comment by alokgogate** [comment] 2018-07-06 09:28
Yes I have looked at the dashboard and thats where I can see only one worker using all the cpu's available. Thats the video that brought me towards dask as I was using ordinary xgboost earlier to train models which were slowing my pipeline down

**Comment by lesteve** [comment] 2018-07-06 10:02
The best thing to post a stand-alone snippet that reproduces the problem if that's possible.

**Comment by mrocklin** [comment] 2018-09-06 19:09
Closing because of lack of information.

**Closed by mrocklin** 2018-09-06 19:09 UTC
