### ISSUE TITLE
Test report links not found

### ISSUE THREAD

**Issue by fjetter** [dask/distributed#6521] opened 2022-06-07 11:42 UTC
The links in our badges pointing to our test reports are returning a 404 / Page not found

![image](https://user-images.githubusercontent.com/8629629/172370207-3973f7b4-03df-407a-bcf5-3481d79dda1f.png)

I guess this is connected to our website switch since they are targeting 
- https://dask.org/distributed/test_short_report.html
- https://dask.org/distributed/test_report.html

which I guess redirected to the github pages website. I assume this redirect is no longer working but I have no idea

cc @crusaderky @jrbourbeau @scharlottej13

**Comment by quasiben** [comment] 2022-06-07 11:48
This is a duplicate of https://github.com/dask/distributed/issues/6511

**Closed** 2022-06-07 11:48 UTC
