### ISSUE TITLE
Cluster hangs with a few tasks in "processing" state but no cpu load on any workers

### ISSUE THREAD

**Issue by GFleishman** [dask/distributed#4724] opened 2021-04-09 16:55 UTC
This problem is stochastic. It seems to occur more frequently when there is more sharing of data between workers. `map_overlap` calls seem particularly problematic.

Cluster is set up using `dask-jobqueue.LSFCluster` and `dask.distributed.Client`

```python
cluster = LSFCluster(
    cores, ncpus, memory, mem,
    walltime=walltime,
    env_extra=env_extra,
    **kwargs,
)
client = Client(cluster)
cluster.scale(job=njobs)  # number of workers
```

Workers are all allocated properly, bash scripts invoking LSF all seem fine. The task graph starts to execute, but then gets hung up and sits indefinitely in this type of state:

<img width="1619" alt="Screen Shot 2021-04-09 at 12 26 36 PM" src="https://user-images.githubusercontent.com/8507206/114213199-b212f980-9930-11eb-9e02-2eff750519a0.png">

<img width="1619" alt="Screen Shot 2021-04-09 at 12 27 24 PM" src="https://user-images.githubusercontent.com/8507206/114213258-c3f49c80-9930-11eb-8251-4d2cc510e849.png">

No workers show any cpu activity (2-4% for all workers). `env_extra` above makes sure all MKL, BLAS, and OpenMP environment variables are set to 2 threads per core (should be fine with hyper threading?).

When I click on the red task on the left of the graph I see:
[hung_cluster_last_task_left.pdf](https://github.com/dask/dask/files/6287304/hung_cluster_last_task_left.pdf)

When I click on the red task on the right of the graph (second to last column) I see:
[hung_cluster_last_task.pdf](https://github.com/dask/dask/files/6287305/hung_cluster_last_task.pdf)

For the red task on the right, the two "workers with data" show:

<img width="1619" alt="Screen Shot 2021-04-09 at 12 28 30 PM" src="https://user-images.githubusercontent.com/8507206/114214276-1aaea600-9932-11eb-86dc-2f18e70b78fa.png">

<img width="1619" alt="Screen Shot 2021-04-09 at 12 28 32 PM" src="https://user-images.githubusercontent.com/8507206/114214283-1d110000-9932-11eb-9411-1ebe5942278b.png">

I've let these hang for upwards of 30 minutes with no meaningful cpu activity on any workers before killing the cluster manually. I can't let it run any longer because I'm paying for cluster time so I don't know if it's just (intractably) slow or totally hung. Comparatively the entire rest of the task graph was executed in less than 180 seconds.

Any pointers as to what could be causing this or how to permanently avoid it would be really appreciated.

- Dask version:    2020.12.0
- Python version:    3.8.5
- Operating System:    CentOS
- Install method (conda, pip, source):    pip

**Comment by rubenvdg** [comment] 2021-04-20 20:26
We’ve seen very similar problems with map_overlap (running on Kubernetes). In the end we prepended and appended data to each partition with our own logic to circumvent it...

**Comment by GFleishman** [comment] 2021-04-20 20:41
Hi @rubenvdg - thanks for the comment. This does happen most often with `map_overlap`, but it also occurs for me with `map_blocks` on very large arrays: (40000, 500, 2048, 1024).... that's (time, z, y, x) for 4D imaging data.

**Comment by rubenvdg** [comment] 2021-04-20 21:08
Same here. In our case it also happened on `map_partitions`, although with `map_overlap` the problem seemed to happen more often. Was difficult to reproduce, so was never able to make a good issue for it.

**Comment by GFleishman** [comment] 2021-04-20 21:28
I agree that it's difficult to reproduce. On several occasions I've convinced myself that the problem was solved only to find out on the next big run that it wasn't. I think it must have something to do with worker to worker communication of dependencies and/or task states, which can be disrupted for a number of reasons, and then potentially is not reset properly by the scheduler. That's all speculation, but the error logs and behavior so far point that way. On some lucky runs I think it's possible that the disrupting events just don't occur (e.g. might be dependent on network traffic).

**Comment by abergou** [comment] 2021-04-21 17:22
@jfetter I think this may be another instance of the issues you're working on.

**Comment by fjetter** [comment] 2021-06-18 09:20
We've recently merged an important PR addressing a few error handling edge cases which caused unrecoverable deadlocks. 
These deadlocks where associated with failing worker, connection failures or host co-located workers. All of these issues could be connected to fetching dependencies, therefore dense, highly connected task graphs were more likely to be affected. Ultimately, the deadlocks where caused by subtle race conditions which made them hard to reproduce and some of them cannot be correlated to any user facing logs which is why I cannot say for certain whether your issue could be fixed.
I would encourage you to try out the latest changes on `main` and/or wait for the upcoming release later today. Feedback on whether your issue could be resolved is highly appreciated!

Deadlock fix https://github.com/dask/distributed/pull/4784
Upcoming release https://github.com/dask/community/issues/165

**Closed** 2021-10-14 14:44 UTC
Labels: bug, needs info
