### ISSUE TITLE
Asynchronous clients cannot compute delayed

### ISSUE THREAD

**Issue by agoose77** [dask/distributed#4820] opened 2021-05-11 20:13 UTC
[![Binder](https://mybinder.org/badge_logo.svg)](https://mybinder.org/v2/gh/agoose77/5b61e23614fd82a5148de749d826ad1f/HEAD?filepath=reproducer.ipynb)

Running `dask.compute` on a `delayed` function with an asynchronous client raises an `Exception`. Locally, I see `'coroutine' object is not iterable`, but in the Binder I see `zip` complains about the first argument not being iterable. I presume these are the same errors that relate to differences in the Python version.

```python3
from dask import distributed, delayed
import dask
import numpy as np

client = await distributed.Client(asynchronous=True)
client

@delayed(pure=True)
def random_data(n):
    return np.random.random(size=n)

data = random_data(24)

dask.compute(data)
```

**Comment by agoose77** [comment] 2021-05-14 15:17
@jsignell thanks for taking a look (and no need to apologise)! I initially wondered about placing it under distributed. I'll take note for the next time that I might raise an issue in this space :)

**Comment by jakirkham** [comment] 2021-05-14 15:40
I think the `compute` line needs to be `await`ed as well

**Comment by jakirkham** [comment] 2021-05-14 15:44
Something like this works for me locally

```python
import asyncio
from dask import distributed, delayed
import dask
import numpy as np


@delayed(pure=True)
def random_data(n):
    return np.random.random(size=n)


async def main():
    async with distributed.Client(asynchronous=True) as client:
        data = random_data(24)
        result = await client.compute(data)
        print(len(result))


if __name__ == "__main__":
    asyncio.run(main())
```

**Comment by agoose77** [comment] 2021-05-14 15:44
@jakirkham originally I did await anything returning a `Future`, and I couldn't get anything reproducible. I did manage to get it to work via `client.compute`.

**Comment by jakirkham** [comment] 2021-05-14 15:49
Right I don't think `dask.compute` works with the `async` `Client`. One needs to use `client.compute`. `dask.compute` is not implemented using `async` so wouldn't expect it to work. The examples in the docs also show using `client.compute` with `await`.

**Comment by agoose77** [comment] 2021-05-14 15:50
@jakirkham naively I'd expect `dask.compute` to block with a sync call, given that the internals are async (or at least, I thought that they were). If this is a WONTFIX, would it make sense to add a test in `dask.compute` that the client is synchronous?

**Comment by jrbourbeau** [comment] 2021-05-14 15:54
From briefly looking at this issue I think it may be a duplicate of https://github.com/dask/dask/issues/5518

**Comment by jakirkham** [comment] 2021-05-14 16:04
Right I think this comment from Jim ( https://github.com/dask/dask/issues/5518#issuecomment-544980219 ) and the one that follows are a good description of what would need to change and why this doesn't work today. To be clear it isn't that things couldn't change, but it would require some careful (though manageable) work from someone to do.

**Comment by jsignell** [comment] 2021-05-14 17:42
Ah ok I agree that this is a dupe of #5518 sorry for the noise!

**Closed by jsignell** 2021-05-14 17:42 UTC
