### ISSUE TITLE
Dashboard Task Stream automatically zooms in every time a task is completed

### ISSUE THREAD

**Issue by bybyte** [dask/distributed#2943] opened 2019-08-08 23:38 UTC
The Dashboard's Task Stream automatically zooms in every time a task is completed. One can refresh the page to see the "entirety" of the completed tasks in the Task Stream but the dashboard once again zooms in as a new tasks complete which is especially problematic when many tasks are regularly being processed on the cluster. 

How can one avoid this behavior? If there is no official way to fix this, would you be able to point me to a section of the code that might be handling this?

I put quotes around entirety because I am pretty sure the Task Stream resets every so often (based on a time interval I assume). It actually would be nice to know how to customize that too.

**Comment by TomAugspurger** [comment] 2019-08-09 13:10
The task stream deliberately just shows the last "batch" of tasks.

A full history of tasks is available at `/tasks`.

**Comment by mrocklin** [comment] 2019-08-09 13:44
We clear out tasks if there hasn't been any activity in a while

https://github.com/dask/distributed/blob/a55515569d4c5da734e5b14ae414cd342c37ed7b/distributed/dashboard/scheduler.py#L763-L770

Probably we need to have a bit of a buffer here that is based on the
general task duration that we're seeing.  If tasks take 1hr each, then we
should allow for gaps of a couple of hours.

**Comment by bybyte** [comment] 2019-08-09 17:32
Thanks for the replies. 

@mrocklin that seems to be it, thank you. It looks like `BokehScheduler` will create the Status's `TaskStream` by calling `status_doc` and that the `clear_interval` is hard-coded to be 10s there. Is that correct? 

It would be nice if that was a settable parameter, although it is not an issue for us to change the value ourselves.

**Comment by mrocklin** [comment] 2019-08-09 17:44
Ideally we learn that parameter over time, perhaps with an exponentially
weighted moving average, or just an average of the current set of
rectangles, so that we're robust to a variety of situations.

**Comment by mrocklin** [comment] 2019-08-09 17:44
(I would like to avoid adding another knob to tune if possible)

**Comment by GenevieveBuckley** [comment] 2021-10-22 02:04
Looking closer, I think this is a duplicate of https://github.com/dask/distributed/issues/3130. (If I've misunderstood, and they are actually different, we should reopen this issue)

I think we'll close this one, even though it was opened first, because there is an open pull request linked to https://github.com/dask/distributed/issues/3130 (PR is here https://github.com/dask/distributed/issues/3130)

**Closed by GenevieveBuckley** 2021-10-22 02:04 UTC
Labels: diagnostics
