### ISSUE TITLE
dask-scheduler and dask-worker CLI break with `click==8.0.0` 

### ISSUE THREAD

**Issue by ManuelBahr** [dask/distributed#4809] opened 2021-05-12 08:58 UTC
**What happened**:

When using `click=8.0.0` which was released on May 11th, the scheduler as well as worker CLI don't come up.

**What you expected to happen**:

Working scheduler and worker CLIs

**Minimal Complete Verifiable Example**:

```bash
$ dask-scheduler --version
ValueError: 'default' must be a list when 'multiple' is true.
$ dask-worker --version
AttributeError: module 'click._unicodefun' has no attribute '_verify_python3_env'
```

**Anything else we need to know?**:

**Probable root cause for dask-scheduler**:

Click changelog: 

> The default value for a parameter with nargs > 1 and multiple=True must be a list of tuples. #1649

https://github.com/dask/distributed/blob/5e150aa6a3bd7decd38193a3d754497f8914d83c/distributed/cli/dask_scheduler.py#L104

`dask-worker` doesn't set a default for multiple options and therefore is not affected by this, but shows a different failure.

**Probable root cause for dask-worker**:

https://github.com/dask/distributed/blob/5e150aa6a3bd7decd38193a3d754497f8914d83c/distributed/cli/utils.py#L22

**Environment**:

- `pip install distributed` reproduces the issue
- Click version needs to be: 8.0.0

**Comment by quasiben** [comment] 2021-05-12 13:00
Thanks for the report @ManuelBahr .  Confirmed that this is an issue:

```
mamba create -n dask-click-test -c conda-forge python
conda activate dask-click-test
python -m pip install distributed
```

Do you know how challenging it would be to support older and latest versions of click ?

**Comment by ManuelBahr** [comment] 2021-05-12 13:06
The fix for `multiple` is trivial since the new version of clicks seems to enforce a restriction that would have made sense earlier. The issue is that all older versions of `dask` will suffer from this as well with the newest `click`. Not sure how you would go about that.

For the `dask-worker` I believe that code fragment that `distributed` used was something internal to click. Not sure how that looks like nowadays.

**Comment by quasiben** [comment] 2021-05-12 13:16
Probably the easiest thing to do right now is set a pin for pip / conda and restrict to less than 8.X.

**Comment by jrbourbeau** [comment] 2021-05-12 14:50
Thanks for reporting @ManuelBahr and investigating @quasiben! I opened up a PR over in https://github.com/dask/distributed/pull/4810 which proposes we add some compatibility code to handle the changes in `click` 8

**Comment by ManuelBahr** [comment] 2021-05-12 15:43
Do you plan to backport those changes to the last version that supported Python3.6?

**Comment by quasiben** [comment] 2021-05-12 16:02
> Do you plan to backport those changes to the last version that supported Python3.6?

I don't think we need to do that. Dask has dropped Python 3.6 support: https://github.com/dask/dask/pull/7006

**Comment by ManuelBahr** [comment] 2021-05-12 16:41
Sure that is the definition of ending support. However, that renders `dask` effectively unusable for Python3.6 users until they discover the solution to constrain `click`. Up to now they were just frozen at a certain version.

**Comment by quasiben** [comment] 2021-05-12 16:59
That is true.  There is not a plan at moment to take this action .  Dask has typically not made patches for older versions and instead opted to encourage folks to upgrade.  We recognize this comes with some frustration but we've also found this to be helpful is resolving bugs quickly while also delivering new features/improvements.   

With that said, Is Python 3.6 critical for you and/or some community you are involved with ?  If so, can you describe some of the blockers for moving on from 3.6 ?

**Comment by ManuelBahr** [comment] 2021-05-12 17:14
> is Python 3.6 critical for you and/or some community you are involved with ?

No, I was just thinking about the new user experience for that segment of `dask` users.

**Closed** 2021-05-12 19:48 UTC

**Comment by quasiben** [comment] 2021-05-14 13:38
@ManuelBahr FYI, a patch was submitted to conda-forge to restrict `click <8` for versions of dask older than 2021.05.0:
https://github.com/conda-forge/conda-forge-repodata-patches-feedstock/pull/142/

**Comment by akamaus** [comment] 2021-06-16 11:56
Stumbled upon this issue using dask-2021.6.0 and click-8.0.1 After upgrading to click-7.1.2 problem fixed.

**Comment by jrbourbeau** [comment] 2021-06-16 13:53
@akamaus could you confirm that you were using `distributed=2021.6.0` and `click=8.0.1` when you saw this issue? I'm not able to reproduce with the following:

```python
$ conda create -n test distributed=2021.6.0 click=8.0.1
$ conda activate test
$ dask-scheduler --version
dask-scheduler, version 2021.6.0
```

**Comment by akamaus** [comment] 2021-06-17 13:47
looks like previously I had `click-8.0.1`, `dask-2021.6.0` and `distributed-2.18.0`. After I upgraded to `distributed-2021.6.0` I can no longer reproduce the issue. Dask was installed as a dependency in my case, I don't know why authors pinned `distributed-2.18.0` (https://github.com/huawei-noah/vega/blob/master/setup.py)
