### ISSUE TITLE
Cannot get result using dask.distributed

### ISSUE THREAD

**Issue by guillaumeeb** [dask/distributed#1254] opened 2017-07-12 15:32 UTC
Hello everyone,

I am using dask since a few weeks, especially dataframe module in order to analyze big csv files. I had a simple code using a little dask, but I realize now a lot of standard pandas dataframes. I wanted to optimize this code and use dask.distributed to be able to parallelize it on a small cluster. But I am running in a issue, I am unable to call future.result() or dataframe.compute() without having an error. Same dataframe process works using dask multiprocess scheduler.

I am on python 2.7 with the last version of dask.
Here is an overview of my code:
```
folderstats = ddf.map_partitions(split_dataframe_folder)
aggregation = {'PATH_NAME': 'count', 'ACCESS_TIME': 'max',
               'MODIFICATION_TIME': 'max',
               'FILE_SIZE': ['sum', 'mean']}
folderstats = folderstats.groupby(['FOLDER1', 'FOLDER2', 'FOLDER3', 'FOLDER4', 'FOLDER5']).agg(aggregation)
folderstats.compute()
```

The error I get:

```
Traceback (most recent call last):
  File "gpfs_csv_analyzer_distributed.py", line 453, in <module>
    main()
  File "gpfs_csv_analyzer_distributed.py", line 450, in main
    es_port=options.port, index_es=options.index_es, index_prefix=options.index_prefix)
  File "gpfs_csv_analyzer_distributed.py", line 419, in launch
    folder_df = generate_folder_agg_stats(ddf).compute()
  File "/work/ADM/hpc/eynardbg/ELK/elk-venv/lib/python2.7/site-packages/dask/base.py", line 98, in compute
    (result,) = compute(self, traverse=False, **kwargs)
  File "/work/ADM/hpc/eynardbg/ELK/elk-venv/lib/python2.7/site-packages/dask/base.py", line 205, in compute
    results = get(dsk, keys, **kwargs)
  File "/work/ADM/hpc/eynardbg/ELK/elk-venv/lib/python2.7/site-packages/distributed/client.py", line 1893, in get
    results = self.gather(packed)
  File "/work/ADM/hpc/eynardbg/ELK/elk-venv/lib/python2.7/site-packages/distributed/client.py", line 1355, in gather
    direct=direct, local_worker=local_worker)
  File "/work/ADM/hpc/eynardbg/ELK/elk-venv/lib/python2.7/site-packages/distributed/client.py", line 531, in sync
    return sync(self.loop, func, *args, **kwargs)
  File "/work/ADM/hpc/eynardbg/ELK/elk-venv/lib/python2.7/site-packages/distributed/utils.py", line 234, in sync
    six.reraise(*error[0])
  File "/work/ADM/hpc/eynardbg/ELK/elk-venv/lib/python2.7/site-packages/distributed/utils.py", line 223, in f
    result[0] = yield make_coro()
  File "/work/ADM/hpc/eynardbg/ELK/elk-venv/lib/python2.7/site-packages/tornado/gen.py", line 1055, in run
    value = future.result()
  File "/work/ADM/hpc/eynardbg/ELK/elk-venv/lib/python2.7/site-packages/tornado/concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "/work/ADM/hpc/eynardbg/ELK/elk-venv/lib/python2.7/site-packages/tornado/gen.py", line 1063, in run
    yielded = self.gen.throw(*exc_info)
  File "/work/ADM/hpc/eynardbg/ELK/elk-venv/lib/python2.7/site-packages/distributed/client.py", line 1235, in _gather
    traceback)
  File "/work/ADM/hpc/eynardbg/ELK/elk-venv/lib/python2.7/site-packages/distributed/protocol/pickle.py", line 59, in loads
    return pickle.loads(x)
TypeError: itemgetter expected 1 arguments, got 0
```

Can someone explain that to me? Serialization problem?

**Comment by mrocklin** [comment] 2017-07-12 15:34
Can you verify that you have the same versions of libraries on all of your
workers?

     client.get_versions(check=True)

**Comment by guillaumeeb** [comment] 2017-07-12 16:15
I am currently on a single node configuration, initializing Client with no
args. This should avoid this kind of issue, doesn't it ?

Le mer. 12 juil. 2017 à 17:34, Matthew Rocklin <notifications@github.com> a
écrit :

**Comment by mrocklin** [comment] 2017-07-12 16:37
Are you able to provide a small reproducible example?

What version of cloudpickle are you using?  Does this error persist in Python 3?

**Comment by guillaumeeb** [comment] 2017-07-12 17:12
In Toulouse working time is over :), I will try to produce a more simple
example that I can give you tomorrow! I will also have a look at
cloudpickle version. I have tried to use Python 3 earlier, but I ran into a
problem that I could not easily explained when importing dask.dataframe...
Hope you will be able to help, I'm more a distributed processing expert
than a python one (more used to Java with Hadoop and Spark), but I see a
real potential into Dask, espetially for some use cases we have at CNES
(French Spatial Agency).

Regards.

Le mer. 12 juil. 2017 à 18:37, Matthew Rocklin <notifications@github.com> a
écrit :

**Comment by guillaumeeb** [comment] 2017-07-13 12:06
OK, here is a simple example that computes a basic analysis on a file system occupation by folder. It is not elegant, but it works with standard pandas and in multiprocess mode, and throws the above error using distributed.

I can provide a more consequent dataset if needed, and I'm available to answer any question.

Cheers,
Guillaume.

[scan.work.sample.csv.txt](https://github.com/dask/distributed/files/1145044/scan.work.sample.csv.txt)
[simple_dask_distributed_example.py.txt](https://github.com/dask/distributed/files/1145045/simple_dask_distributed_example.py.txt)

**Comment by guillaumeeb** [comment] 2017-07-13 12:24
Cloudpickle verison:
```
pip freeze | grep cloudpickle 
cloudpickle==0.3.1
```

**Comment by mrocklin** [comment] 2017-07-17 20:54
Cloudpickle has had some issues with recent releases.  You might try setting it back to 0.2.2.

**Comment by guillaumeeb** [comment] 2017-07-18 07:29
OK, I installed previous cloudpickle version

```
pip freeze | grep pickle
cloudpickle==0.2.2
```

But I still get the following error:
```
$ python really_simple_dask_distributed_example.py
Generating folder stats
Traceback (most recent call last):
  File "really_simple_dask_distributed_example.py", line 37, in <module>
    folder_df = folderstats.compute()
  File "/work/ADM/hpc/eynardbg/ELK/elk-venv/lib/python2.7/site-packages/dask/base.py", line 98, in compute
    (result,) = compute(self, traverse=False, **kwargs)
  File "/work/ADM/hpc/eynardbg/ELK/elk-venv/lib/python2.7/site-packages/dask/base.py", line 205, in compute
    results = get(dsk, keys, **kwargs)
  File "/work/ADM/hpc/eynardbg/ELK/elk-venv/lib/python2.7/site-packages/distributed/client.py", line 1893, in get
    results = self.gather(packed)
  File "/work/ADM/hpc/eynardbg/ELK/elk-venv/lib/python2.7/site-packages/distributed/client.py", line 1355, in gather
    direct=direct, local_worker=local_worker)
  File "/work/ADM/hpc/eynardbg/ELK/elk-venv/lib/python2.7/site-packages/distributed/client.py", line 531, in sync
    return sync(self.loop, func, *args, **kwargs)
  File "/work/ADM/hpc/eynardbg/ELK/elk-venv/lib/python2.7/site-packages/distributed/utils.py", line 234, in sync
    six.reraise(*error[0])
  File "/work/ADM/hpc/eynardbg/ELK/elk-venv/lib/python2.7/site-packages/distributed/utils.py", line 223, in f
    result[0] = yield make_coro()
  File "/work/ADM/hpc/eynardbg/ELK/elk-venv/lib/python2.7/site-packages/tornado/gen.py", line 1055, in run
    value = future.result()
  File "/work/ADM/hpc/eynardbg/ELK/elk-venv/lib/python2.7/site-packages/tornado/concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "/work/ADM/hpc/eynardbg/ELK/elk-venv/lib/python2.7/site-packages/tornado/gen.py", line 1063, in run
    yielded = self.gen.throw(*exc_info)
  File "/work/ADM/hpc/eynardbg/ELK/elk-venv/lib/python2.7/site-packages/distributed/client.py", line 1235, in _gather
    traceback)
  File "/work/ADM/hpc/eynardbg/ELK/elk-venv/lib/python2.7/site-packages/distributed/protocol/pickle.py", line 59, in loads
    return pickle.loads(x)
TypeError: itemgetter expected 1 arguments, got 0

```

**Comment by guillaumeeb** [comment] 2017-08-18 11:15
Hi here.

I have performed some more tests for this issue. Seems like the `aggregate` method of `DataFrameGroupBy` does not work in distributed mode. When I run the following code:
```
folderstats = ddf.groupby('USER_ID').agg('count')
folder_df = folderstats.compute()
```
I got the above error.
Whereas if I run this:
```
folderstats = ddf.groupby('USER_ID').count()
folder_df = folderstats.compute()
```
Everything works well.

Problem is, I need to perform several different aggregations on the same grouping: count on a field, max on other ones, mean and sum also. So the only solution I see here is that I would need to perform each computation individually, and at the end join every resulting dataframes on the user_id. But as we cannot persist a DataFrameGroupBy, I believe I would have to recompute the groups for each of my aggregations, which seems highly innefective.

Any thoughts on this?

**Comment by TomAugspurger** [comment] 2017-08-18 12:23
@guillaumeeb do you have a simplified example available? It looks like the files linked above are HTML files.

Ideally it would be just a simple function we could stick in a unit test suite, and not rely on any additional files.

**Comment by guillaumeeb** [comment] 2017-08-18 13:13
Thanks for the answer, here you are:
```
import dask.dataframe as dd
import dask.distributed as ddis

FILE_CONTENT = '"2017-01-03 18:54:09.915224"|"2017-01-03 18:54:09.915844"|"2017-01-03 18:54:07.336751"|"+0.00000000000000E+000"|"alt_swot"|"102989996"|"1970949662"|"5023"|"9663676416"|"-rw-------"|"2"|"2016-07-04 16:27:47.000000"|"intf_test.AzPTR.Noise.LeftSwath.nc"|"/work/ALT/swot/swothr/users/blumsted/sam_tst/4.6.1/test.classif/makeInterferogramJPL_1.00/outputs/intf_test.AzPTR.Noise.LeftSwath.nc"|"capacitive"|"7282"'+ \
    '\n"2017-01-03 18:54:08.407216"|"2017-01-03 18:54:08.408393"|"2017-01-03 18:54:07.411518"|"+0.00000000000000E+000"|"alt_swot"|"16793977"|"915821477"|"5021"|"9663676417"|"-rw-rw----"|"2"|"2016-04-21 12:32:47.000000"|"Antarctica_DEM_Bamber_2350.tif"|"/work/ALT/swot/swotcls/SOFT/scripts/TDS_Ice_Sheet/output/DEM/TDS_IceSheet_001_150Km/Antarctica_DEM_Bamber/Antarctica_DEM_Bamber_2350.tif"|"capacitive"|"7380"' + \
    '\n"2017-01-03 18:54:09.108220"|"2017-01-03 18:54:09.109046"|"2017-01-03 18:54:08.408800"|"+0.00000000000000E+000"|"alt_swot"|"16793977"|"427891820"|"5021"|"9663676418"|"-rw-rw----"|"2"|"2016-04-21 12:32:48.000000"|"Antarctica_DEM_Bamber_2351.tif"|"/work/ALT/swot/swotcls/SOFT/scripts/TDS_Ice_Sheet/output/DEM/TDS_IceSheet_001_150Km/Antarctica_DEM_Bamber/Antarctica_DEM_Bamber_2351.tif"|"capacitive"|"7380"' + \
    '\n"2017-01-03 18:54:09.833224"|"2017-01-03 18:54:09.834180"|"2017-01-03 18:54:09.110531"|"+0.00000000000000E+000"|"alt_swot"|"16793977"|"2144904641"|"5021"|"9663676420"|"-rw-rw----"|"2"|"2016-04-21 12:32:48.000000"|"Antarctica_DEM_Bamber_2352.tif"|"/work/ALT/swot/swotcls/SOFT/scripts/TDS_Ice_Sheet/output/DEM/TDS_IceSheet_001_150Km/Antarctica_DEM_Bamber/Antarctica_DEM_Bamber_2352.tif"|"capacitive"|"7380"' + \
    '\n"2017-01-03 18:54:09.535222"|"2017-01-03 18:54:09.536001"|"2017-01-03 18:54:09.535504"|"+0.00000000000000E+000"|"alt_swot"|"145"|"1691799381"|"4938"|"9663676421"|"-rw-rw----"|"2"|"2016-01-28 18:09:48.000000"|"S_Am_S_.prj"|"/work/ALT/swot/swotpub/GLOWABO/GLOWABO_Points_shp/GLOWABO_Points_shp_merged/point_XY_sid_KeopGeig_COASCATS_pays/S_Am_S_.prj"|"hot"|"1548"' + \
    '\n"2017-01-03 18:54:09.864224"|"2017-01-03 18:54:09.865284"|"2017-01-03 18:54:09.536305"|"+0.00000000000000E+000"|"alt_swot"|"6152196"|"907823669"|"4938"|"9663676422"|"-rw-rw----"|"2"|"2016-01-28 18:09:51.000000"|"S_Am_S_.sbn"|"/work/ALT/swot/swotpub/GLOWABO/GLOWABO_Points_shp/GLOWABO_Points_shp_merged/point_XY_sid_KeopGeig_COASCATS_pays/S_Am_S_.sbn"|"capacitive"|"1548"' + \
    '\n"2017-01-03 18:54:10.548228"|"2017-01-03 18:54:10.548448"|"2017-01-03 18:54:09.834823"|"+0.00000000000000E+000"|"alt_swot"|"16793977"|"1715764524"|"5021"|"9663676423"|"-rw-rw----"|"2"|"2016-04-21 12:32:49.000000"|"Antarctica_DEM_Bamber_2353.tif"|"/work/ALT/swot/swotcls/SOFT/scripts/TDS_Ice_Sheet/output/DEM/TDS_IceSheet_001_150Km/Antarctica_DEM_Bamber/Antarctica_DEM_Bamber_2353.tif"|"capacitive"|"7380"' + \
    '\n"2017-01-03 18:54:09.897224"|"2017-01-03 18:54:09.897723"|"2017-01-03 18:54:09.865765"|"+0.00000000000000E+000"|"alt_swot"|"104756"|"1763274660"|"4938"|"9663676424"|"-rw-rw----"|"2"|"2016-01-28 18:09:52.000000"|"S_Am_S_.sbx"|"/work/ALT/swot/swotpub/GLOWABO/GLOWABO_Points_shp/GLOWABO_Points_shp_merged/point_XY_sid_KeopGeig_COASCATS_pays/S_Am_S_.sbx"|"hot"|"1548"' + \
    '\n"2017-01-03 18:54:10.568228"|"2017-01-03 18:54:10.568652"|"2017-01-03 18:54:09.898226"|"+0.00000000000000E+000"|"alt_swot"|"19564120"|"917775763"|"4938"|"9663676425"|"-rw-rw----"|"2"|"2016-01-28 18:10:02.000000"|"S_Am_S_.shp"|"/work/ALT/swot/swotpub/GLOWABO/GLOWABO_Points_shp/GLOWABO_Points_shp_merged/point_XY_sid_KeopGeig_COASCATS_pays/S_Am_S_.shp"|"capacitive"|"1548"' + \
    '\n"2017-01-03 18:54:11.518233"|"2017-01-03 18:54:11.519275"|"2017-01-03 18:54:09.916272"|"+0.00000000000000E+000"|"alt_swot"|"63760667"|"297596455"|"5023"|"9663676426"|"-rw-------"|"2"|"2016-07-04 16:27:39.000000"|"intf_test.LeftSwath.GO.nc"|"/work/ALT/swot/swothr/users/blumsted/sam_tst/4.6.1/test.classif/makeInterferogramJPL_1.00/outputs/intf_test.LeftSwath.GO.nc"|"capacitive"|"7282"'

GPFS_FILE_ATTRIBUTS = ["ACCESS_TIME", "CHANGE_TIME", "CREATION_TIME", "FILE_HEAT", "FILESET_NAME", "FILE_SIZE", "GENERATION", "GROUP_ID", "INODE", "MODE", "MODIFICATION_SNAPID", "MODIFICATION_TIME", "NAME", "PATH_NAME", "POOL_NAME", "USER_ID", "LINE_END"]

def run_test():
    client = ddis.Client()  # set up local cluster

    example_file = open("temp-dask-inputfile", "w")
    example_file.write(FILE_CONTENT)
    example_file.close()

    ddf = dd.read_csv("temp-dask-inputfile", sample=250001, sep='|', names=GPFS_FILE_ATTRIBUTS)

    folderstats = ddf.groupby('USER_ID').agg('count')
    # folderstats = ddf.groupby('USER_ID').count()

    print("Generating folder stats")
    # folder_df = client.compute(folderstats)
    folder_df = folderstats.compute()
    # folder_df = folderstats.compute(get=dask.multiprocessing.get)
    print(folder_df.head())

if __name__ == "__main__":
    run_test()
```

**Comment by TomAugspurger** [comment] 2017-08-18 13:17
Perfect, thanks. Does running that generate the error for you? It unfortunately works fine for me (running the latest dask and distributed).

**Comment by guillaumeeb** [comment] 2017-08-18 13:41
I don't know if it is fortunate or unfortunate :) It's more reassuring to know that it should work...

Here is my setup:
```
$ python -V
Python 2.7.12
$ pip freeze | grep dask
dask==0.15.1
$pip freeze | grep distributed
distributed==1.18.0
```

And the error I still get when running this few lines:
```
$ python really_simple_dask_distributed_example.py 
Generating folder stats
Traceback (most recent call last):
  File "really_simple_dask_distributed_example.py", line 43, in <module>
    run_test()
  File "really_simple_dask_distributed_example.py", line 38, in run_test
    folder_df = folderstats.compute()
  File "/work/ADM/hpc/eynardbg/ELK/elk-venv/lib/python2.7/site-packages/dask/base.py", line 98, in compute
    (result,) = compute(self, traverse=False, **kwargs)
  File "/work/ADM/hpc/eynardbg/ELK/elk-venv/lib/python2.7/site-packages/dask/base.py", line 205, in compute
    results = get(dsk, keys, **kwargs)
  File "/work/ADM/hpc/eynardbg/ELK/elk-venv/lib/python2.7/site-packages/distributed/client.py", line 1893, in get
    results = self.gather(packed)
  File "/work/ADM/hpc/eynardbg/ELK/elk-venv/lib/python2.7/site-packages/distributed/client.py", line 1355, in gather
    direct=direct, local_worker=local_worker)
  File "/work/ADM/hpc/eynardbg/ELK/elk-venv/lib/python2.7/site-packages/distributed/client.py", line 531, in sync
    return sync(self.loop, func, *args, **kwargs)
  File "/work/ADM/hpc/eynardbg/ELK/elk-venv/lib/python2.7/site-packages/distributed/utils.py", line 234, in sync
    six.reraise(*error[0])
  File "/work/ADM/hpc/eynardbg/ELK/elk-venv/lib/python2.7/site-packages/distributed/utils.py", line 223, in f
    result[0] = yield make_coro()
  File "/work/ADM/hpc/eynardbg/ELK/elk-venv/lib/python2.7/site-packages/tornado/gen.py", line 1055, in run
    value = future.result()
  File "/work/ADM/hpc/eynardbg/ELK/elk-venv/lib/python2.7/site-packages/tornado/concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "/work/ADM/hpc/eynardbg/ELK/elk-venv/lib/python2.7/site-packages/tornado/gen.py", line 1063, in run
    yielded = self.gen.throw(*exc_info)
  File "/work/ADM/hpc/eynardbg/ELK/elk-venv/lib/python2.7/site-packages/distributed/client.py", line 1235, in _gather
    traceback)
  File "/work/ADM/hpc/eynardbg/ELK/elk-venv/lib/python2.7/site-packages/distributed/protocol/pickle.py", line 59, in loads
    return pickle.loads(x)
TypeError: itemgetter expected 1 arguments, got 0

```

**Comment by TomAugspurger** [comment] 2017-08-18 14:01
Seems like it might be a python2 thing. I'm able to reproduce on master using python2. Taking a deeper look now.

**Comment by guillaumeeb** [comment] 2017-08-18 14:20
Okay that is a good news, I was able to install a correct python 3 test environment and indeed this works correctly. This can be a solution for me, but I need to swich my production environment now...

**Comment by TomAugspurger** [comment] 2017-08-18 15:02
I haven't had much luck tracking this down yet. The actual error is on deserializing the arguments for `dask.dataframe.core.apply_and_enforce`, and it seems like an `operator.itemgetter` isn't being created or called correctly. Or at least it isn't being serialized by distributed correctly (it does work fine with the multiprocessing scheduler).

@mrocklin does this give you any clues? If not, I can take another look later this afternoon.

**Comment by mrocklin** [comment] 2017-08-29 14:41
Yes, this also fails for me on Python 2 with cloudpickle from 0.2.2 and 0.4

**Comment by mrocklin** [comment] 2017-08-29 14:46
This diff in dask fixes the problem

```python
diff --git a/dask/dataframe/groupby.py b/dask/dataframe/groupby.py
index bed6300..3d2b7a6 100644
--- a/dask/dataframe/groupby.py
+++ b/dask/dataframe/groupby.py
@@ -440,7 +440,7 @@ def _build_agg_args_simple(result_column, func, input_column, impl_pair):
                      dict(column=input_column, func=chunk_impl))],
         aggregate_funcs=[(intermediate, _apply_func_to_column,
                          dict(column=intermediate, func=agg_impl))],
-        finalizer=(result_column, operator.itemgetter(intermediate), dict()),
+        finalizer=(result_column, lambda x: x[intermediate], dict()),
     )
```

I suggest that we just don't rely on `operator.itemgetter` to be robustly serializable.  (cc @jcrist to make sure that this is sensible)

@TomAugspurger multiprocessing tends to be a bit more forgiving because of fork.

**Comment by TomAugspurger** [comment] 2017-08-30 16:45
Closed by https://github.com/dask/dask/pull/2638 if you want to try updating to master @guillaumeeb

**Closed by TomAugspurger** 2017-08-30 16:45 UTC
