### ISSUE TITLE
Resource Warnings with LocalCluster 

### ISSUE THREAD

**Issue by bamal** [dask/distributed#2486] opened 2019-01-28 14:27 UTC
Hi Everyone, 

After starting a local cluster on my machine as shown here:

```  cluster = LocalCluster()

    print(cluster)

    client = Client()

    print(client)

    cluster.close()
```

I got so many Resource Warnings as shown below. 

```/usr/local/lib/python3.6/dist-packages/distributed/diskutils.py:161:

 ResourceWarning:

unclosed file <_io.BufferedWriter name='/home/amal/PycharmProjects/dynamicparcels/dynpar/dask-worker-space/worker-4t43rjqe.dirlock'>

/usr/local/lib/python3.6/dist-packages/distributed/diskutils.py:161: ResourceWarning:

unclosed file <_io.BufferedWriter name='/home/amal/PycharmProjects/dynamicparcels/dynpar/dask-worker-space/worker-4fyxnn5d.dirlock'>

<Client: scheduler='tcp://127.0.0.1:43123' processes=8 cores=8>
distributed.scheduler - INFO - Clear task state
distributed.nanny - INFO - Closing Nanny at 'tcp://127.0.0.1:37009'
distributed.nanny - INFO - Closing Nanny at 'tcp://127.0.0.1:41811'
distributed.nanny - INFO - Closing Nanny at 'tcp://127.0.0.1:38581'
distributed.nanny - INFO - Closing Nanny at 'tcp://127.0.0.1:42381'
distributed.nanny - INFO - Closing Nanny at 'tcp://127.0.0.1:41167'
distributed.nanny - INFO - Closing Nanny at 'tcp://127.0.0.1:39899'
distributed.nanny - INFO - Closing Nanny at 'tcp://127.0.0.1:43027'
distributed.nanny - INFO - Closing Nanny at 'tcp://127.0.0.1:34385'
distributed.scheduler - INFO - Remove worker tcp://127.0.0.1:39323
distributed.core - INFO - Removing comms to tcp://127.0.0.1:39323
distributed.scheduler - INFO - Remove worker tcp://127.0.0.1:46047
distributed.core - INFO - Removing comms to tcp://127.0.0.1:46047
distributed.scheduler - INFO - Remove worker tcp://127.0.0.1:45833
distributed.core - INFO - Removing comms to tcp://127.0.0.1:45833
distributed.scheduler - INFO - Remove worker tcp://127.0.0.1:36641
distributed.core - INFO - Removing comms to tcp://127.0.0.1:36641
distributed.scheduler - INFO - Remove worker tcp://127.0.0.1:42175
distributed.core - INFO - Removing comms to tcp://127.0.0.1:42175
distributed.scheduler - INFO - Remove worker tcp://127.0.0.1:33033
distributed.core - INFO - Removing comms to tcp://127.0.0.1:33033
distributed.scheduler - INFO - Remove worker tcp://127.0.0.1:46337
distributed.core - INFO - Removing comms to tcp://127.0.0.1:46337
distributed.scheduler - INFO - Remove worker tcp://127.0.0.1:37449
distributed.core - INFO - Removing comms to tcp://127.0.0.1:37449
distributed.scheduler - INFO - Lost all workers
distributed.scheduler - INFO - Scheduler closing...
distributed.scheduler - INFO - Scheduler closing all comms
/usr/lib/python3.6/asyncio/base_events.py:511: ResourceWarning:

unclosed event loop <_UnixSelectorEventLoop running=False closed=False debug=False>
```

Do anyone have an idea how can I fix that please ?

**Comment by mrocklin** [comment] 2019-01-28 17:46
cc @pitrou any thoughts on this?

**Comment by pitrou** [comment] 2019-01-30 20:07
Not really. The symptoms are rather vague...

**Comment by jonmoore** [comment] 2021-07-13 21:19
I don't have a minimized reproducible case yet, but have also seen this warning occur repeatably when using instances of Client while running distributed 2021.02.0 under pytest 6.2, Python 3.8.8, Windows 7.

The warning is that an instance of asyncio.base_events.BaseEventLoop was not closed before being deleted by the garbage collector.  In the cases I've investigated the loops were created by calls beginning with Client.__init__, running through distributed.utils.LoopRunner.start, which creates a daemon thread that calls tornado's BaseAsyncIOLoop.start-->asyncio.get_event_loop->(distributed)AnyThreadLoopEventPolicy.get_event_loop->, which creates BaseEventLoop.  The loop then gets recorded in LoopRunner._all_loops.  It looks like it is meant to be closed by a call to LoopRunner.stop.

If anyone knows off-hand if the current behavior is intentional or not, that would be helpful to know before digging further into this.

**Comment by fjetter** [comment] 2021-07-14 10:33
@jonmoore the `LoopRunner` should be closed if the `Client` is closed, see https://github.com/dask/distributed/blob/67f57bc0c880101bc3336557c4dce43d4fa5ec43/distributed/client.py#L1489-L1490
I guess, for some reason, the client is not closed properly before the interpreter shuts down. We've been fixing a few stability related things over the past months and I would encourage you trying a more recent version to see if the problem persists.

**Comment by jrbourbeau** [comment] 2021-11-02 23:12
@jonmoore, following up on @fjetter's comment, does upgrading to the latest `distributed` release help?

**Comment by madkinsz** [comment] 2022-04-13 19:23
See https://github.com/dask/distributed/pull/6122 and https://github.com/mwilliamson/locket.py/issues/14

**Closed** 2022-04-23 23:16 UTC
Labels: needs info
