### ISSUE TITLE
Failing bokeh tests with v3

### ISSUE THREAD

**Issue by fjetter** [dask/distributed#7732] opened 2023-03-31 09:55 UTC
In https://github.com/dask/distributed/pull/7413 we lifted the pinning on bokeh

https://dask.github.io/distributed/test_short_report.html
![image](https://user-images.githubusercontent.com/8629629/229088461-72102a5b-a90e-43b8-9d25-8257af885232.png)
![image](https://user-images.githubusercontent.com/8629629/229088479-79bcb776-9b35-4f19-ad6d-cb2ba01df0c5.png)

Since this PR the two tests 
- `distributed.dashboard.tests.test_scheduler_bokeh.test_https_support`
- `distributed.dashboard.tests.test_scheduler_bokeh.test_simple`

are reliably failing with an internal server error.

**Comment by jacobtomlinson** [comment] 2023-03-31 10:35
I think this is a duplicate of #7731

**Comment by jrbourbeau** [comment] 2023-03-31 14:56
Yeah, agreed this is the same as https://github.com/dask/distributed/issues/7731. Going to close this issue to consolidate conversation over in https://github.com/dask/distributed/issues/7731. (Thanks for opening this on @fjetter)

**Closed by jrbourbeau** 2023-03-31 14:56 UTC
Labels: flaky test, regression, dependencies, dashboard
