### ISSUE TITLE
Creating an AioClient locks up in distributed 1.25.3

### ISSUE THREAD

**Issue by uellue** [dask/distributed#2537] opened 2019-02-20 12:06 UTC
This short reproducer works in distributed 1.25.2, but locks up in 1.25.3. This behavior is triggered in https://github.com/LiberTEM/LiberTEM/ when creating a dask cluster and leads to a hard freeze of the application. 

Update: The behavior is observed both on Windows 10 and on Linux.

```python
import asyncio

from dask import distributed as dd
from distributed.asyncio import AioClient


async def async_main():
    cluster_kwargs = {
        "threads_per_worker": 1,
        "asynchronous": True,
        "n_workers": 2
    }
    client_kwargs = {}
    print("starting cluster...")
    cluster = dd.LocalCluster(**(cluster_kwargs or {}))
    print("cluster started.")
    print("creating client...")
    client = await AioClient(cluster, **(client_kwargs or {}))
    print("success")


if __name__ == '__main__':
    loop = asyncio.get_event_loop()
    loop.run_until_complete(async_main())
```

Expected behavior: It continues working the same in all version past 1.25.2.

**Comment by mrocklin** [comment] 2019-02-20 15:59
I'm curious, can you just use a normal Client?  Tornado and Asyncio have
merged to the point where I'm starting to suspect that AioClient may no
longer be worth the maintenance effort.

**Comment by uellue** [comment] 2019-02-21 07:58
That is a pretty disruptive way of depreciating a feature.

**Comment by uellue** [comment] 2019-02-21 08:02
@mrocklin Linus Torvalds' famous rant might be relevant here: https://lkml.org/lkml/2012/12/23/75

**Comment by uellue** [comment] 2019-02-21 08:18
From a professionally maintained library that provides core functionality for many other applications I'd expect a decent depreciation period (six months to one year) with a warning and a link to a resource describing how to replace the depreciated feature. 

Furthermore, I'd expect that a regression in a maintenance release of such a library is just fixed ASAP. 

Third, even just removing that feature cold and triggering a Python error is better than just breaking it and letting users figure out why their application suddenly just freezes on startup.

**Comment by TomAugspurger** [comment] 2019-02-21 13:27
@uellue does it work before and after https://github.com/dask/distributed/pull/2403?

**Comment by uellue** [comment] 2019-02-21 13:52
@TomAugspurger Yes, that commit seems to be the culprit.

* Bug reproduced in 53dd9e441fbbb0bab2ab5f9d18f35293d9a8bbda
* Bug not reproduced in 4e38022ed91b7d90ffe54703e9975d94a37fb9c3

**Comment by TomAugspurger** [comment] 2019-02-21 14:01
Thanks for checking. cc @danpf in case you have any guesses off the top of your head, though you may not be familiar with AioClient.

---

As an aside @uellue, you may have more luck in open source if you're kinder to others. Speaking personally, comments like your earlier ones tend do demotivate my as a maintainer; I'd be more likely to move onto one of the many other issues. I stepped in here so that others wouldn't have to. But if a library has a sole maintainer there won't be a backstop and you'd end up hurting yourself (not to mention making the other person feel bad).

**Comment by uellue** [comment] 2019-02-21 14:25
@TomAugspurger @mrocklin Yeah, the same goes in the other direction. I've taken the time to write a nice reproducer, and as a reply I don't even get a thank you, I'm just told that the feature is depreciated as of now and I am supposed to change my code.

Quite frankly, this is not a code base I like to depend on.

**Comment by TomAugspurger** [comment] 2019-02-21 14:30
Hmm, perhaps people's intended tone is getting lost when put to text then.
I'll just assume the best intentions.

I don't think that anything in 22 hours ago
<https://github.com/dask/distributed/issues/2537#issuecomment-465638952> was
saying that

1. AioClient is deprecated
2. We aren't interested in fixing this particular regression.

Rather, that's saying that the *need* for AioClient (maybe) isn't there
anymore. IIUC, now that tornado is using
 the asyncio event loop, async things should just work with the regular
Client.

And thanks for the simple reproducer. It is indeed appreciated.

**Comment by danpf** [comment] 2019-02-21 14:42
Asyncio stuff is still so new that not many people use it (from what I've seen). When I started using distributed I too was drawn towards the AIOClient via the documentation.  I can't exactly remember why or how I switched to using `Client(asynchronous=True)` but I also remember being frustrated and feeling mislead at that point.

but regardless, somewhere in the documentation, I'm not sure where, I do remember reading this line:
https://github.com/dask/distributed/blob/master/distributed/asyncio.py#L40

```
    AioClient is an **experimental** interface for distributed and may
    disappear without warning!
```

As for the code, the only thing you need to make sure of is to pass `asynchronous=True` to `Client` and `LocalCluster` and I've never really had any problems with that!

**Comment by uellue** [comment] 2019-02-21 15:09
@TomAugspurger So, _will_ someone fix the bug and for how long will AioClient still be supported? https://github.com/dask/distributed/issues/2537#issuecomment-465638952 was quite ambiguous, to say the least.

**Comment by uellue** [comment] 2019-02-21 15:11
@danpf The documentation has it as an official feature: http://distributed.dask.org/en/latest/asynchronous.html#asyncio

**Comment by TomAugspurger** [comment] 2019-02-21 15:15
I won't have time to look into the issue today. LMK if you're interested in
working on it and I can help you get started.

I don't have any experience with AioClient, so can't say how long it'll
stick around. That would probably depend on the
level of community interest. If it's useful to people then it'll stay. If
it's completely redundant with Client, then I could see
it being (gracefully) deprecated.

**Comment by danpf** [comment] 2019-02-21 15:49
@uellue I would highly recommend changing your code to call `Client(asynchronous=True)` instead of hoping `AioClient` is fixed.

**Comment by mrocklin** [comment] 2019-02-21 16:39
cc also @kszucs

Also feedback on the possibility of just dropping support for Tornado 4.5
would be welcome here: https://github.com/dask/distributed/issues/2538

**Comment by uellue** [comment] 2019-02-21 20:32
@danpf Many thanks, your information was very helpful.

**Comment by kszucs** [comment] 2019-02-22 11:33
Yeah, I suggest pinning tornado 5 and deprecating `AioClient` as a wrapper for `Client(asynchronous=True)`.

**Closed** 2019-05-08 22:06 UTC
