### ISSUE TITLE
ERROR - unpack requires a bytes object of length 8

### ISSUE THREAD

**Issue by rabernat** [dask/distributed#1059] opened 2017-05-04 20:10 UTC
I am using the latest github master of distributed (1.16.2)

I am having workers die with the following error. I really have no idea what it means.

```
distributed.worker - ERROR - unpack requires a bytes object of length 8
Traceback (most recent call last):
  File "/rigel/home/ra2697/distributed/distributed/worker.py", line 1838, in execute
    args2 = pack_data(args, self.data, key_types=str)
  File "/rigel/home/ra2697/distributed/distributed/utils_comm.py", line 236, in pack_data
    return typ([pack_data(x, d, key_types=key_types) for x in o])
  File "/rigel/home/ra2697/distributed/distributed/utils_comm.py", line 236, in <listcomp>
    return typ([pack_data(x, d, key_types=key_types) for x in o])
  File "/rigel/home/ra2697/distributed/distributed/utils_comm.py", line 231, in pack_data
    return d[o]
  File "/rigel/home/ra2697/miniconda/envs/dask_distributed/lib/python3.5/site-packages/zict/buffer.py", line 70, in __getitem__
    return self.slow_to_fast(key)
  File "/rigel/home/ra2697/miniconda/envs/dask_distributed/lib/python3.5/site-packages/zict/buffer.py", line 57, in slow_to_fast
    value = self.slow[key]
  File "/rigel/home/ra2697/miniconda/envs/dask_distributed/lib/python3.5/site-packages/zict/func.py", line 39, in __getitem__
    return self.load(self.d[key])
  File "/rigel/home/ra2697/distributed/distributed/protocol/serialize.py", line 364, in deserialize_bytes
    frames = unpack_frames(b)
  File "/rigel/home/ra2697/distributed/distributed/protocol/utils.py", line 119, in unpack_frames
    (length,) = struct.unpack('Q', b[(i + 1) * 8: (i + 2) * 8])
struct.error: unpack requires a bytes object of length 8
```

**Comment by rabernat** [comment] 2017-05-04 20:34
A possibly related error that also pops up:

```
distributed.worker - ERROR - a bytes-like object is required, not 'list'
Traceback (most recent call last):
  File "/rigel/home/ra2697/distributed/distributed/worker.py", line 1349, in transition_executing_done
    self.put_key_in_memory(key, value)
  File "/rigel/home/ra2697/distributed/distributed/worker.py", line 1498, in put_key_in_memory
    self.data[key] = value
  File "/rigel/home/ra2697/miniconda/envs/dask_distributed/lib/python3.5/site-packages/zict/buffer.py", line 80, in __setitem__
    self.fast[key] = value
  File "/rigel/home/ra2697/miniconda/envs/dask_distributed/lib/python3.5/site-packages/zict/lru.py", line 75, in __setitem__
    cb(k, v)
  File "/rigel/home/ra2697/miniconda/envs/dask_distributed/lib/python3.5/site-packages/zict/buffer.py", line 52, in fast_to_slow
    self.slow[key] = value
  File "/rigel/home/ra2697/miniconda/envs/dask_distributed/lib/python3.5/site-packages/zict/func.py", line 42, in __setitem__
    self.d[key] = self.dump(value)
  File "/rigel/home/ra2697/miniconda/envs/dask_distributed/lib/python3.5/site-packages/zict/file.py", line 71, in __setitem__
    f.write(value)
TypeError: a bytes-like object is required, not 'list'
```

**Comment by mrocklin** [comment] 2017-05-04 20:34
Can you verify that all of your workers are running under the same version?

client.get_versions(check=True)

**Comment by rabernat** [comment] 2017-05-04 20:41
Yes, it looks like they are.

```
{'client': {'host': [('python', '3.5.3.final.0'),
   ('python-bits', 64),
   ('OS', 'Linux'),
   ('OS-release', '3.10.0-327.el7.x86_64'),
   ('machine', 'x86_64'),
   ('processor', 'x86_64'),
   ('byteorder', 'little'),
   ('LC_ALL', 'None'),
   ('LANG', 'en_US.UTF-8'),
   ('LOCALE', 'en_US.UTF-8')],
  'packages': {'optional': [('numpy', '1.12.0'), ('pandas', '0.19.2')],
   'required': [('dask', '0.14.1'),
    ('distributed', '1.16.2'),
    ('msgpack', '0.4.8'),
    ('cloudpickle', '0.2.2'),
    ('toolz', '0.8.2')]}},
 'scheduler': {'host': [['python', '3.5.3.final.0'],
   ['python-bits', 64],
   ['OS', 'Linux'],
   ['OS-release', '3.10.0-327.el7.x86_64'],
   ['machine', 'x86_64'],
   ['processor', 'x86_64'],
   ['byteorder', 'little'],
   ['LC_ALL', 'None'],
   ['LANG', 'en_US.UTF-8'],
   ['LOCALE', 'en_US.UTF-8']],
  'packages': {'optional': [['numpy', '1.12.0'], ['pandas', '0.19.2']],
   'required': [['dask', '0.14.1'],
    ['distributed', '1.16.2'],
    ['msgpack', '0.4.8'],
    ['cloudpickle', '0.2.2'],
    ['toolz', '0.8.2']]}},
 'workers': {'tcp://10.43.8.124:38266': {'host': [('python', '3.5.3.final.0'),
    ('python-bits', 64),
    ('OS', 'Linux'),
    ('OS-release', '3.10.0-327.el7.x86_64'),
    ('machine', 'x86_64'),
    ('processor', 'x86_64'),
    ('byteorder', 'little'),
    ('LC_ALL', 'None'),
    ('LANG', 'en_US.UTF-8'),
    ('LOCALE', 'en_US.UTF-8')],
   'packages': {'optional': [('numpy', '1.12.0'), ('pandas', '0.19.2')],
    'required': [('dask', '0.14.1'),
     ('distributed', '1.16.2'),
     ('msgpack', '0.4.8'),
     ('cloudpickle', '0.2.2'),
     ('toolz', '0.8.2')]}},
  'tcp://10.43.8.125:49507': {'host': [('python', '3.5.3.final.0'),
    ('python-bits', 64),
    ('OS', 'Linux'),
    ('OS-release', '3.10.0-327.el7.x86_64'),
    ('machine', 'x86_64'),
    ('processor', 'x86_64'),
    ('byteorder', 'little'),
    ('LC_ALL', 'None'),
    ('LANG', 'en_US.UTF-8'),
    ('LOCALE', 'en_US.UTF-8')],
   'packages': {'optional': [('numpy', '1.12.0'), ('pandas', '0.19.2')],
    'required': [('dask', '0.14.1'),
     ('distributed', '1.16.2'),
     ('msgpack', '0.4.8'),
     ('cloudpickle', '0.2.2'),
     ('toolz', '0.8.2')]}},
  'tcp://10.43.8.202:49162': {'host': [('python', '3.5.3.final.0'),
    ('python-bits', 64),
    ('OS', 'Linux'),
    ('OS-release', '3.10.0-327.el7.x86_64'),
    ('machine', 'x86_64'),
    ('processor', 'x86_64'),
    ('byteorder', 'little'),
    ('LC_ALL', 'None'),
    ('LANG', 'en_US.UTF-8'),
    ('LOCALE', 'en_US.UTF-8')],
   'packages': {'optional': [('numpy', '1.12.0'), ('pandas', '0.19.2')],
    'required': [('dask', '0.14.1'),
     ('distributed', '1.16.2'),
     ('msgpack', '0.4.8'),
     ('cloudpickle', '0.2.2'),
     ('toolz', '0.8.2')]}},
  'tcp://10.43.8.22:47802': {'host': [('python', '3.5.3.final.0'),
    ('python-bits', 64),
    ('OS', 'Linux'),
    ('OS-release', '3.10.0-327.el7.x86_64'),
    ('machine', 'x86_64'),
    ('processor', 'x86_64'),
    ('byteorder', 'little'),
    ('LC_ALL', 'None'),
    ('LANG', 'en_US.UTF-8'),
    ('LOCALE', 'en_US.UTF-8')],
   'packages': {'optional': [('numpy', '1.12.0'), ('pandas', '0.19.2')],
    'required': [('dask', '0.14.1'),
     ('distributed', '1.16.2'),
     ('msgpack', '0.4.8'),
     ('cloudpickle', '0.2.2'),
     ('toolz', '0.8.2')]}},
  'tcp://10.43.8.34:42163': {'host': [('python', '3.5.3.final.0'),
    ('python-bits', 64),
    ('OS', 'Linux'),
    ('OS-release', '3.10.0-327.el7.x86_64'),
    ('machine', 'x86_64'),
    ('processor', 'x86_64'),
    ('byteorder', 'little'),
    ('LC_ALL', 'None'),
    ('LANG', 'en_US.UTF-8'),
    ('LOCALE', 'en_US.UTF-8')],
   'packages': {'optional': [('numpy', '1.12.0'), ('pandas', '0.19.2')],
    'required': [('dask', '0.14.1'),
     ('distributed', '1.16.2'),
     ('msgpack', '0.4.8'),
     ('cloudpickle', '0.2.2'),
     ('toolz', '0.8.2')]}}}}
```

**Comment by mrocklin** [comment] 2017-05-04 20:45
What version of zict are you using

```python
>>> import zict
>>> zict.__version__
```

**Comment by rabernat** [comment] 2017-05-04 22:01
'0.1.1'

**Comment by mrocklin** [comment] 2017-05-04 22:03
Try `pip install zict --upgrade`.  If this resolves things then I'll update our requirements.

**Comment by mrocklin** [comment] 2017-05-04 22:09
Ah!  This *is* listed in requirements as `zict >= 0.1.2`.  It must not have triggered when you upgraded from git.

**Comment by rabernat** [comment] 2017-05-04 22:15
Upgrading to zict v 0.1.2 did not fix the problem. Still getting `unpack requires a bytes object of length 8` errors when trying to `.persist()`.

**Comment by mrocklin** [comment] 2017-05-04 22:22
> edit: yes, I am sure I restarted all the workers / schedulers after upgrading.

I saw this *just* as I was writting "are you sure that ... " :)

**Comment by mrocklin** [comment] 2017-05-04 22:30
Are you able to easily run the distributed test suite on that machine?  Typically I do this by downloading the source, going into the directory, and running pytest


```
git clone git@github.com:dask/distributed.git
cd distributed
py.test distributed/tests --verbose
```

**Comment by rabernat** [comment] 2017-05-04 22:45
I got two failures
```
============================================================= FAILURES =============================================================
________________________________________________ test_log_exception_on_failed_task _________________________________________________

    def test_func():
        with pristine_loop() as loop:
            with check_active_rpc(loop, active_rpc_timeout):
                s, workers = loop.run_sync(lambda: start_cluster(ncores, loop,
                                Worker=Worker, scheduler_kwargs=scheduler_kwargs,
                                worker_kwargs=worker_kwargs))
                args = [s] + workers

                if client:
                    e = Client(s.address, loop=loop, start=False)
                    loop.run_sync(e._start)
                    args = [e] + args
                try:
>                   return loop.run_sync(lambda: cor(*args), timeout=timeout)

distributed/utils_test.py:520:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
../miniconda/envs/dask_distributed/lib/python3.5/site-packages/tornado/ioloop.py:457: in run_sync
    return future_cell[0].result()
../miniconda/envs/dask_distributed/lib/python3.5/site-packages/tornado/concurrent.py:237: in result
    raise_exc_info(self._exc_info)
<string>:3: in raise_exc_info
    ???
../miniconda/envs/dask_distributed/lib/python3.5/site-packages/tornado/gen.py:1024: in run
    yielded = self.gen.send(value)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

c = <Client: scheduler='tcp://127.0.0.1:37061'>, s = <Scheduler: "tcp://127.0.0.1:37061" processes: 0 cores: 0>
a = <Worker: tcp://127.0.0.1:42478, closed, stored: 0, running: 0/1, ready: 0, comm: 0, waiting: 0>
b = <Worker: tcp://127.0.0.1:57907, closed, stored: 0, running: 0/2, ready: 0, comm: 0, waiting: 0>

    @pytest.mark.avoid_travis
    @gen_cluster(client=True)
    def test_log_exception_on_failed_task(c, s, a, b):
        with tmpfile() as fn:
            fh = logging.FileHandler(fn)
            try:
                from distributed.worker import logger
                logger.addHandler(fh)

                future = c.submit(div, 1, 0)
                yield _wait(future)

                yield gen.sleep(0.1)
                fh.flush()
                with open(fn) as f:
                    text = f.read()

>               assert "ZeroDivisionError" in text
E               assert 'ZeroDivisionError' in ''

distributed/tests/test_worker.py:617: AssertionError
______________________________________________________ test_spill_by_default _______________________________________________________

    def test_func():
        with pristine_loop() as loop:
            with check_active_rpc(loop, active_rpc_timeout):
                s, workers = loop.run_sync(lambda: start_cluster(ncores, loop,
                                Worker=Worker, scheduler_kwargs=scheduler_kwargs,
                                worker_kwargs=worker_kwargs))
                args = [s] + workers

                if client:
                    e = Client(s.address, loop=loop, start=False)
                    loop.run_sync(e._start)
                    args = [e] + args
                try:
>                   return loop.run_sync(lambda: cor(*args), timeout=timeout)

distributed/utils_test.py:520:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <tornado.platform.epoll.EPollIOLoop object at 0x2aaad3f47e48>
func = <function gen_cluster.<locals>._.<locals>.test_func.<locals>.<lambda> at 0x2aab1ec231e0>, timeout = 30

    def run_sync(self, func, timeout=None):
        """Starts the `IOLoop`, runs the given function, and stops the loop.

            The function must return either a yieldable object or
            ``None``. If the function returns a yieldable object, the
            `IOLoop` will run until the yieldable is resolved (and
            `run_sync()` will return the yieldable's result). If it raises
            an exception, the `IOLoop` will stop and the exception will be
            re-raised to the caller.

            The keyword-only argument ``timeout`` may be used to set
            a maximum duration for the function.  If the timeout expires,
            a `TimeoutError` is raised.

            This method is useful in conjunction with `tornado.gen.coroutine`
            to allow asynchronous calls in a ``main()`` function::

                @gen.coroutine
                def main():
                    # do stuff...
                    # do stuff...

                if __name__ == '__main__':
                    IOLoop.current().run_sync(main)

            .. versionchanged:: 4.3
               Returning a non-``None``, non-yieldable value is now an error.
            """
        future_cell = [None]

        def run():
            try:
                result = func()
                if result is not None:
                    from tornado.gen import convert_yielded
                    result = convert_yielded(result)
            except Exception:
                future_cell[0] = TracebackFuture()
                future_cell[0].set_exc_info(sys.exc_info())
            else:
                if is_future(result):
                    future_cell[0] = result
                else:
                    future_cell[0] = TracebackFuture()
                    future_cell[0].set_result(result)
            self.add_future(future_cell[0], lambda future: self.stop())
        self.add_callback(run)
        if timeout is not None:
            timeout_handle = self.add_timeout(self.time() + timeout, self.stop)
        self.start()
        if timeout is not None:
            self.remove_timeout(timeout_handle)
        if not future_cell[0].done():
>           raise TimeoutError('Operation timed out after %s seconds' % timeout)
E           tornado.ioloop.TimeoutError: Operation timed out after 30 seconds

../miniconda/envs/dask_distributed/lib/python3.5/site-packages/tornado/ioloop.py:456: TimeoutError
============================= 2 failed, 541 passed, 37 skipped, 7 xfailed, 1 xpassed in 302.97 seconds =============================
```

**Comment by mrocklin** [comment] 2017-05-04 22:46
How about `py.test distributed/protocol --verbose`

**Comment by mrocklin** [comment] 2017-05-04 22:50
Just to give context.  The error you're getting is when workers have done some work, have too much data to fit in ram and then have stored some of that data onto disk.  This is fine so far.  What isn't fine is when they go to pick the data back up from disk when it has to be used again.

The second failure you're getting here is also related to dumping data to disk.  It may be related to your actual error.  Although, if you're on a huge machine, it might also just be that it's writing an incredible amount of data to your NFS in order to try to trigger the situation.  I should adjust this test.

**Comment by rabernat** [comment] 2017-05-04 22:57
One failure from protocol:

```
___________________________________________________ test_serialize_list_compress ___________________________________________________

    def test_serialize_list_compress():
        x = np.ones(1000000)
        L = serialize_bytelist(x)
>       assert sum(map(len, L)) < x.nbytes / 2
E       assert 8000111 < (8000000 / 2)
E        +  where 8000111 = sum(<map object at 0x2aaafaa40e10>)
E        +    where <map object at 0x2aaafaa40e10> = map(len, [b'\x02\x00\x00\x00\x00\x00\x00\x00W\x00\x00\x00\x00\x00\x00\x00\x00\x
12z\x00\x00\x00\x00\x00', b'\x87\xa5shape\x91\xc...e\xadnumpy.ndarray\xa5dtype\xa3<f8\xabcompression\x91\xc0\xa7lengths\x91\xce\x00z
\x12\x00', <memory at 0x2aaafa8e9b88>])
E        +  and   8000000 = array([ 1.,  1.,  1., ...,  1.,  1.,  1.]).nbytes

distributed/protocol/tests/test_serialize.py:177: AssertionError
========================================= 1 failed, 104 passed, 12 skipped in 8.79 seconds =========================================
```

**Comment by mrocklin** [comment] 2017-05-04 22:59
Can you verify that you have neither lz4 nor blosc installed?

**Comment by mrocklin** [comment] 2017-05-04 23:11
ipyOK, in hindsight I think that neither of these are surprising.  

Another question, is it possible that dask workers are writing to a tmp directory that is actually not ideal, either because it is remote on an NFS and so incurs some race conditions or because it is small and runs out of space?  

To test this you might see what temporary directory your workers are using:

```python
In [5]: def f(dask_worker):
   ...:     return dask_worker.local_dir
   ...: 

In [6]: client.run(f)
Out[6]: 
{'tcp://127.0.0.1:34369': '/tmp/nanny-py4i7ofu',
 'tcp://127.0.0.1:34647': '/tmp/nanny-8xtr_uvo',
 'tcp://127.0.0.1:36313': '/tmp/nanny-kakc3j3e',
 'tcp://127.0.0.1:43784': '/tmp/nanny-v7jy74pf'}
```

And then investigate what filesystem this directory lives on.  You can change this directory when setting up a worker by setting the `--local-directory` flag with a unique directory for that worker.  If using a job scheduler with clever environment variables this might look like the following:

    dask-worker ... --local-directory /local-scratch/worker-$SLURM_JOB_ID

**Comment by rabernat** [comment] 2017-05-04 23:13
I can't import either of those packages...if that's what you mean.

**Comment by rabernat** [comment] 2017-05-04 23:16
I explicitly set `--local-dir /local` in my worker launch script in order to point to the hosts' local 2TB SSDs.

The output of your command gives:
```
{'tcp://10.43.8.124:39791': '/local',
 'tcp://10.43.8.125:56611': '/local',
 'tcp://10.43.8.202:57491': '/local',
 'tcp://10.43.8.58:44885': '/local',
 'tcp://10.43.8.78:44319': '/local'}
```

**Comment by mrocklin** [comment] 2017-05-04 23:31
Are you able to replicate your error in a way that I can try on my local machine?  This might involve using random data rather than stored data.

**Comment by mrocklin** [comment] 2017-05-04 23:35
Or, put another way.  My attempts to replicate this error have failed.  What I do now:

```python
from dask.distributed import Client, wait
client = Client()  # make a local cluster

import dask.array as da
x = da.ones(2000000000, chunks=10000000)  # a large array
x = x.persist()
wait(x)
(x + 1).sum().compute()  # bring data back from disk
```

**Comment by rabernat** [comment] 2017-05-04 23:42
I will try to think of a replicable example. Your example works fine for me.

**Comment by mrocklin** [comment] 2017-05-04 23:58
To be clear we're trying to get the array to be large enough to swamp available memory.  It could be that you need to increase those numbers to fill up your available RAM

**Comment by rabernat** [comment] 2017-05-04 23:59
It's strange that you say that this is a RAM issue. I monitor my workers on the workers dashboard, and memory usage never gets about 50%. I don't understand why it's spilling to disk.

**Comment by mrocklin** [comment] 2017-05-05 00:04
[This traceback](https://github.com/dask/distributed/issues/1059#issue-226394585) is in a part of the code that gets triggered when you send data to disk.  By default dask starts spilling to disk at around 60% memory usage.  You might try looking at http://scheduler:8787/status at the upper left plot.  If the bars are red then you're using disk

**Comment by rabernat** [comment] 2017-05-05 00:07
The bars in the upper _left_  plot (bytes stored) are blue. In the upper _right_ (task processing) there is some red.

**Comment by rabernat** [comment] 2017-05-05 00:08
The worker page says the following when the error kicks in.

![image](https://cloud.githubusercontent.com/assets/1197350/25729759/7e43815c-3105-11e7-9a88-4b17a9118268.png)

**Comment by mrocklin** [comment] 2017-05-05 00:11
That's surprising.  I don't know why it would engage that code then.  At this point I recommend trying to create a reproducible example, perhaps by doing what you're doing now but with random data, and then with smaller and smaller scales and clusters.

**Comment by rabernat** [comment] 2017-05-05 00:12
I will work on a reproducible example. It's kind of intermittent, which makes it really hard to track down.

**Comment by rabernat** [comment] 2017-05-05 01:02
FYI, after playing around with the number of workers and the `--memory-limit` flag, I am in agreement that this is related to spilling to disk. If I can avoid spilling to disk, my computations work fine.

**Comment by rabernat** [comment] 2017-05-05 01:50
I am also getting this error. No idea if related or not

```
distributed.protocol.pickle - INFO - Failed to deserialize b'\x80\x04'
Traceback (most recent call last):
  File "/rigel/home/ra2697/distributed/distributed/protocol/pickle.py", line 59, in loads
    return pickle.loads(x)
EOFError: Ran out of input
distributed.protocol.core - CRITICAL - Failed to deserialize
Traceback (most recent call last):
  File "/rigel/home/ra2697/distributed/distributed/protocol/core.py", line 113, in loads
    value = _deserialize(head, fs)
  File "/rigel/home/ra2697/distributed/distributed/protocol/serialize.py", line 161, in deserialize
    return f(header, frames)
  File "/rigel/home/ra2697/distributed/distributed/protocol/serialize.py", line 23, in <lambda>
    deserializers = {None: lambda header, frames: pickle.loads(b''.join(frames))}
  File "/rigel/home/ra2697/distributed/distributed/protocol/pickle.py", line 59, in loads
    return pickle.loads(x)
```

**Comment by mrocklin** [comment] 2017-05-09 12:40
Do you have multiple workers writing to the same directory on the same machine perhaps?  That might cause some contention?

**Comment by rabernat** [comment] 2017-05-09 12:50
> Do you have multiple workers writing to the same directory on the same machine perhaps? That might cause some contention?

I only have one worker per machine, but each worker has multiple threads.

**Comment by mrocklin** [comment] 2017-05-09 12:51
Yeah, then I don't know what's going on here.

**Comment by mrocklin** [comment] 2017-05-25 07:56
Was this issue resolved by https://github.com/dask/distributed/pull/1079 ?

**Comment by tiagofrepereira2012** [comment] 2020-06-25 06:44
I'm also having this unpickling issue from time to time.
Check the log below just for illustration.

I'm using `dask_jobqueue` to create workers in a SGE grid.

It's extremely difficult to reproduce this issue because it happens randomly.
I basically don't know what to do.

Thanks for any feedback

```
distributed.worker - WARNING -  Compute Failed
Function:  execute_task
args:      ((<function apply at 0x7f45de9e44d0>, <bound method BioAlgorithm.score_samples of <bob.bio.base.pipelines.vanilla_biometrics.wrappers.BioAlgorithmCheckpointWrapper object at 0x7f456de568d0>>, [[SampleSet(samples=[DelayedSample(load=functools.partial(<function load at 0x7f45a5e29710>, '/idiap/temp/tpereira/citer/meds/facenet_sanderberg/samplewrapper-2/./data/ad/S396-03-t10_01.jpg.h5'), key='./data/ad/S396-03-t10_01.jpg', subject='396', annotations={'leye': (267.0, 250.0), 'reye': (261.0, 166.0)}, _data=array([ 1.11655816e-01,  3.54632251e-02, -4.89996700e-03, -5.31726032e-02,
        8.85177180e-02, -8.44024643e-02, -9.74103883e-02, -4.38827416e-03,
       -8.31486210e-02,  6.20006882e-02, -3.65480073e-02,  2.91100461e-02,
       -7.41371047e-03, -8.72691348e-02,  1.66366652e-01, -1.63817510e-01,
        7.46925622e-02, -3.08021475e-02, -7.94351026e-02, -1.78173289e-01,
        1.27477257e-03, -6.52376190e-02, -1.28354318e-02,  1.84421897e-01,
        8.77578557e-02,  5.58240786e-02, -7
kwargs:    {}
Exception: EOFError('Ran out of input')
```

**Comment by mrocklin** [comment] 2020-06-25 13:29
> Was this issue resolved by #1079 ?

It has been a few years since this question has been asked.  I'm guessing that this is resolved.  Closing.

@tiagofrepereira2012 your question appears to be unrelated.  I recommend raising a new issue.  
At first glance I don't know what is happening in your situation.  I recommend trying to provide a minimal reproducible example in a new issue.

**Closed by mrocklin** 2020-06-25 13:29 UTC

**Comment by tiagofrepereira2012** [comment] 2020-06-25 15:12
Yeah, I know, that's what I'm trying to do. However, it's difficult to make a consistent reproducible code for this problem (the serialization fails randomly).

I'm a bit hopeless, but thanks for the answer anyways

**Comment by mrocklin** [comment] 2020-06-25 15:14
My first guess would be a version mismatch.  I would encourage you to make sure that all of your workers and client and scheduler are on a recent version of Dask.

**Comment by tiagofrepereira2012** [comment] 2020-06-25 15:21
They are all

```
dask                      2.19.0                     py_0    defaults
dask-core                 2.19.0                     py_0    defaults
dask-jobqueue             0.7.0                      py_0    defaults
distributed               2.19.0                   py37_0    defaults
```

Basically I use SGE to launch the workers.
Both workers/scheduler use the same conda environment, which is in a shared file system.
