### ISSUE TITLE
When using the stopit module in the workload, results become unpredictable.

### ISSUE THREAD

**Issue by PGijsbers** [dask/distributed#4414] opened 2021-01-08 14:16 UTC
I wasn't sure where to report this issue, apologies if you feel it's misplaced.

**What happened**: When using the [`stopit`](https://pypi.org/project/stopit/) module in the workload to control their duration, results become unpredictable.

**What you expected to happen**:  The `TimeoutException` not to affect Dask since it's processed by the `ThreadingTimeout` context manager.

**Minimal Complete Verifiable Example**:

```python
from dask.distributed import Client, as_completed
import numpy as np
import stopit


def stopit_work(_):
    with stopit.ThreadingTimeout(1) as timeout:
        while timeout.state != timeout.TIMED_OUT:
            pass
    return np.random.random(size=(10_000, 50))


def main(func):
    with stopit.ThreadingTimeout(5):
        with Client(n_workers=1, threads_per_worker=1) as client:
            ac = as_completed(client.map(func, range(1, 10), pure=False), with_results=True)
            for future, result in ac:
                print(result.shape)
                ac.add(client.submit(func, 11, pure=False))
    print("done")


if __name__ == '__main__':
    main(stopit_work)
```

Expected output (is sometimes produced):
```
>>>python mwe.py
(10000, 50)
(10000, 50)
(10000, 50)
(10000, 50)
done
```
Unexpected output (more frequently observed):
```
>>>python mwe.py
distributed.worker - WARNING -  Compute Failed
Function:  stopit_work
args:      (1)
kwargs:    {}
Exception: TimeoutException()

done
```

**Anything else we need to know?**: The MWE mimics the setup in [GAMA](https://github.com/PGijsbers/gama), where the outer time-out controls the length of a search procedure, and the job time-out limits the time per job. In our attempts to use `distributed` we also find other errors irregularly:
 ```
 distributed.scheduler - ERROR - Workers don't have promised key: [], evaluate_individual-48f7e8adaded337558582d6544dadd1 NoneType: None
 ```
 ```
 [WinError 10054] An existing connection was forcibly closed by the remote host
 ```
But I am so far unable to create a MWE for them.

**Environment**:
Latest versions of `stopit`, `distributed` and `numpy`:
```
Package          Version
---------------- ---------
click            7.1.2
cloudpickle      1.6.0
dask             2020.12.0
distributed      2020.12.0
HeapDict         1.0.1
msgpack          1.0.2
numpy            1.19.5
pip              19.2.3
psutil           5.8.0
PyYAML           5.3.1
setuptools       41.2.0
sortedcontainers 2.3.0
stopit           1.1.2
tblib            1.7.0
toolz            0.11.1
tornado          6.1
zict             2.0.0
``` 

- Python version: 3.8.3
- Operating System: Windows 10 Pro
- Install method (conda, pip, source): pip

**Comment by jacobtomlinson** [comment] 2021-01-08 14:46
Thanks @PGijsbers for taking the time to raise this. It is a well written issue.

I'm afraid I am unable to reproduce on Linux or macOS. I've run the script 100 times on each with both the latest release and also the latest development code and I haven't seen this happen.

Do you think this could be a windows specific issue?

**Comment by PGijsbers** [comment] 2021-01-08 15:43
Thanks for taking the time @jacobtomlinson! I did some more digging and found that this behavior in the MWE is explained by a race condition. After the `Threading.Timer` is done, [`stop`](https://github.com/glenfant/stopit/blob/13def66251b8ed06cef5ea5f80b00583d80adb2d/src/stopit/threadstop.py#L48) is called, which allows the loop to exit while the `TimeoutException` is still queued (and thus will be raised outside of the context manager). Replacing `stopit_work` with:

```python
def stopit_work(_):
    with stopit.ThreadingTimeout(1) as timeout:
        while True:
            pass
    return np.random.random(size=(10_000, 50))
```
fixes the unpredictable behavior (and gives the desired output). Sorry for wasting your time there, not sure why I hadn't set it up this way in the first place. 

However, the original code never had such a check so I still encounter the issue in the wild. I'll go back to see if I can construct a new MWE which reproduces the behavior (and I'll make sure to check cross-platform behavior). Let me know what the desired procedure is from here (e.g. close the issue, and I'll comment when/if I am able to construct a new MWE).

**Comment by jacobtomlinson** [comment] 2021-01-08 15:50
> close the issue, and I'll comment when/if I am able to construct a new MWE

That sounds good. I'll close it out now but if you are able to reproduce it then just head back here and ask for it to be reopened.

**Closed by jacobtomlinson** 2021-01-08 15:50 UTC

**Comment by PGijsbers** [comment] 2021-01-18 10:23
I did have another issue with unpredictable behavior. I thought it might be due to me using the module wrong, so I posted it on [StackOverflow ](https://stackoverflow.com/questions/65634382/how-do-i-properly-clear-outstanding-futures-in-dask-distributed-when-using-as) first (per the guidelines). I am not sure if you would be willing to have a look and/or can refer me somewhere?
