### ISSUE TITLE
Message about leaked semaphores on worker shutdown

### ISSUE THREAD

**Issue by shughes-uk** [dask/distributed#1049] opened 2017-05-01 15:23 UTC
Sometime's when shutting down workers I get an error message about leaked semaphores.
Here's the log from starting a worker to shutdown

> distributed.nanny - INFO -         Start Nanny at: 'tcp://10.200.30.95:4041'
> distributed.worker - INFO -       Start worker at:    tcp://10.200.30.95:4040
> distributed.worker - INFO -              nanny at:         10.200.30.95:4041
> distributed.worker - INFO -               http at:         10.200.30.95:34383
> distributed.worker - INFO -              bokeh at:         10.200.30.95:45582
> distributed.worker - INFO - Waiting to connect to:    tcp://atx-stats-01:8786
> distributed.worker - INFO - -------------------------------------------------
> distributed.worker - INFO -               Threads:                          1
> distributed.worker - INFO -                Memory:                    1.84 GB
> distributed.worker - INFO -       Local Directory:        /tmp/nanny-m0azz3qq
> distributed.worker - INFO - -------------------------------------------------
> distributed.worker - INFO -         Registered to:          tcp://atx-stats-01:8786
> distributed.worker - INFO - -------------------------------------------------
> distributed.nanny - INFO - Nanny 'tcp://10.200.30.95:4041' starts worker process 'tcp://10.200.30.95:4040'
> distributed.dask_worker - INFO - End worker
> /home/shughes/miniconda3/lib/python3.6/multiprocessing/semaphore_tracker.py:129: UserWarning: semaphore_tracker: There appear to be 5 leaked semaphores to clean up at shutdown
>   len(cache))
>

**Comment by crusaderky** [comment] 2020-03-05 12:08
Looks to be a duplicate of #1078

**Comment by TomAugspurger** [comment] 2020-03-05 13:03
Yep, thanks.

**Closed by TomAugspurger** 2020-03-05 13:03 UTC
