### ISSUE TITLE
Plugin to pipe stdout/stderr to a log event

### ISSUE THREAD

**Issue by mrocklin** [dask/distributed#7202] opened 2022-10-26 21:14 UTC
Folks sometimes want stdout and stderr sent to the client.  This is maybe pretty easy with ...

1. Teeing off sys.stdout/stderr as in https://stackoverflow.com/questions/616645/how-to-duplicate-sys-stdout-to-a-log-file
2. Dropping the results into the `print` log event
3. All withing a WorkerPlugin

Maybe something like this for stdout?

```python
class Tee(object):
    def __init__(self, worker):
        self.stdout = sys.stdout
        self.worker = worker
        sys.stdout = self
    def close(self):
        sys.stdout = self.stdout
    def write(self, data):
        self.worker.log_event("print", data)
        self.stdout.write(data)
    def flush(self):
        self.file.flush()

class StdOut(WorkerPlugin):
    def start(self, worker):
        self.tee = Tee(worker)

    def close(self):
        self.tee.close()
```

**Comment by fjetter** [comment] 2022-11-02 08:43
I think this is a duplicate of https://github.com/dask/distributed/issues/2033

**Closed** 2022-11-15 10:39 UTC
