### ISSUE TITLE
fire_and_forget scheduler error in 2.11.0

### ISSUE THREAD

**Issue by mgh35** [dask/distributed#3551] opened 2020-03-04 20:58 UTC
Hi,

Discovered what looks like a bug with fire_and_forget in the scheduler in 2.11.0. The error doesn't exist in 2.10.1. 

**Repro**

Running a 1-worker cluster like:
```
docker run -it --network host daskdev/dask:2.11.0 dask-scheduler
docker run -it --network host daskdev/dask:2.11.0 dask-worker localhost:8786
```

I run a python shell:
```
virtualenv .venv
source .venv/bin/activate

pip install dask distributed
python
```

Using the small dask.distributed example:
```
import time
import random
import dask.distributed
import logging

 
def inc(x):
    logging.warning('blah: x')
    time.sleep(random.random())
    return x + 1


def dec(x):
    logging.warning('blah: y')
    time.sleep(random.random())
    return x - 1


def add(x, y):
    logging.warning('blah: z')
    time.sleep(random.random())
    return x + y


def repro():
    with dask.config.set({"distributed.comm.compression": "lz4"}):
        client = dask.distributed.Client("tcp://localhost:8786")
        f = client.get({
            'x': (inc, 1),
            'y': (dec, 2),
            'z': (add, 'x', 'y')
        }, 'z', sync=False)
        dask.distributed.fire_and_forget(f)


repro()
```

I get this error in the scheduler:
```
distributed.scheduler - INFO - Plugin failed with exception
Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/site-packages/distributed/scheduler.py", line 4645, in transition
    plugin.transition(key, start, finish2, *args, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/distributed/diagnostics/graph_layout.py", line 93, in transition
    self.visible_updates.append((self.index[key], "False"))
KeyError: 'z'
distributed.scheduler - ERROR - Error transitioning 'z' from 'processing' to 'memory'
Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/site-packages/distributed/scheduler.py", line 4655, in transition
    ts.prefix.groups.remove(tg)
ValueError: list.remove(x): x not in list
distributed.core - ERROR - list.remove(x): x not in list
Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/site-packages/distributed/core.py", line 473, in handle_stream
    handler(**merge(extra, msg))
  File "/opt/conda/lib/python3.7/site-packages/distributed/scheduler.py", line 2597, in handle_task_finished
    r = self.stimulus_task_finished(key=key, worker=worker, **msg)
  File "/opt/conda/lib/python3.7/site-packages/distributed/scheduler.py", line 2015, in stimulus_task_finished
    recommendations = self.transition(key, "memory", worker=worker, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/distributed/scheduler.py", line 4655, in transition
    ts.prefix.groups.remove(tg)
ValueError: list.remove(x): x not in list
distributed.scheduler - INFO - Remove worker <Worker 'tcp://127.0.0.1:36953', name: tcp://127.0.0.1:36953, memory: 0, processing: 0>
distributed.core - INFO - Removing comms to tcp://127.0.0.1:36953
distributed.scheduler - INFO - Lost all workers
distributed.utils - ERROR - list.remove(x): x not in list
Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/site-packages/distributed/utils.py", line 665, in log_errors
    yield
  File "/opt/conda/lib/python3.7/site-packages/distributed/scheduler.py", line 1739, in add_worker
    await self.handle_worker(comm=comm, worker=address)
  File "/opt/conda/lib/python3.7/site-packages/distributed/scheduler.py", line 2694, in handle_worker
    await self.handle_stream(comm=comm, extra={"worker": worker})
  File "/opt/conda/lib/python3.7/site-packages/distributed/core.py", line 473, in handle_stream
    handler(**merge(extra, msg))
  File "/opt/conda/lib/python3.7/site-packages/distributed/scheduler.py", line 2597, in handle_task_finished
    r = self.stimulus_task_finished(key=key, worker=worker, **msg)
  File "/opt/conda/lib/python3.7/site-packages/distributed/scheduler.py", line 2015, in stimulus_task_finished
    recommendations = self.transition(key, "memory", worker=worker, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/distributed/scheduler.py", line 4655, in transition
    ts.prefix.groups.remove(tg)
ValueError: list.remove(x): x not in list
distributed.core - ERROR - list.remove(x): x not in list
Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/site-packages/distributed/core.py", line 412, in handle_comm
    result = await result
  File "/opt/conda/lib/python3.7/site-packages/distributed/scheduler.py", line 1739, in add_worker
    await self.handle_worker(comm=comm, worker=address)
  File "/opt/conda/lib/python3.7/site-packages/distributed/scheduler.py", line 2694, in handle_worker
    await self.handle_stream(comm=comm, extra={"worker": worker})
  File "/opt/conda/lib/python3.7/site-packages/distributed/core.py", line 473, in handle_stream
    handler(**merge(extra, msg))
  File "/opt/conda/lib/python3.7/site-packages/distributed/scheduler.py", line 2597, in handle_task_finished
    r = self.stimulus_task_finished(key=key, worker=worker, **msg)
  File "/opt/conda/lib/python3.7/site-packages/distributed/scheduler.py", line 2015, in stimulus_task_finished
    recommendations = self.transition(key, "memory", worker=worker, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/distributed/scheduler.py", line 4655, in transition
    ts.prefix.groups.remove(tg)
ValueError: list.remove(x): x not in list
distributed.scheduler - INFO - Register worker <Worker 'tcp://127.0.0.1:36953', name: tcp://127.0.0.1:36953, memory: 0, processing: 0>
distributed.scheduler - INFO - Starting worker compute stream, tcp://127.0.0.1:36953
distributed.core - INFO - Starting established connection
```

All of the functions complete on the worker (I see the output printed). However, once the exception is thrown, the next call to `repro` does not get executed. A third call to `repro` does get executed and again throws the exception.

Running the exact same code against 2.10.1 scheduler and worker runs without the exception and behaves as expected.

Thanks,

Mark

**Comment by TomAugspurger** [comment] 2020-03-05 13:19
Thanks for the report. I'm not able to reproduce on distributed master (though I'm just using local processes, not docker. Is docker necessary?). Can you try with master?

**Comment by jrbourbeau** [comment] 2020-03-05 18:07
Thanks for opening up an issue @mgh35! I think this is a duplicate of #3465. I'm working on a fix for it now

**Comment by mgh35** [comment] 2020-03-06 03:59
Thanks both for looking. Sorry to have missed the duplicate - somehow missed that when searching fire_and_forget.

@TomAugspurger I think I can reproduce with local processes. I clone a fork of dask/distributed (at master), under a virtualenv:
```
python setup.py develop
```
and from that virtualenv in three separate windows run:
```
dask-scheduler
dask-worker localhost:8786
[repro above]
```
I get the same error.

Cherry-picking your patch @jrbourbeau the error goes away. Thank you very much!

**Comment by jrbourbeau** [comment] 2020-03-06 04:03
> Cherry-picking your patch @jrbourbeau the error goes away 

Glad to hear it, thank you for testing it out

**Closed** 2020-03-06 16:23 UTC
