### ISSUE TITLE
'distributed.protocol.core - CRITICAL - Failed to deserialize' -- With Cupy 

### ISSUE THREAD

**Issue by crumleyc** [dask/distributed#3532] opened 2020-02-29 21:19 UTC
Here is the code up to the point I get this error message:

```
import cupy as cp
import numpy as np
import dask.array as da
from dask.bag import read_text
from dask.distributed import Client

def row_to_numpy(row):
    return np.array([np.float(x) for x in row.split()])

client = Client()

S = read_text(my text file).str.strip().map(row_to_numpy)
S = da.stack(S, axis=0).map_blocks(cp.array)

u_old = da.random.random(T) 
u_old = v.map_blocks(cp.array)

_V_  = client.scatter(v, broadcast=True)
v = da.dot(_U_.result(),S).compute()
```

Basically I am reading in a txt file into a dask cupy array. I get this error message everytime I map as cupy, (numpy results in no errors). I am broadcasing this 1D array to all of the workers before doing this matrix multiplication. I looked at most other tickets and I couldn't quite see a similar issue. All of my workers are updated and I have read the Serialization page in the docs but wasn't sure how that would help me. 

I am getting this error message:
```
distributed.protocol.core - CRITICAL - Failed to deserialize
Traceback (most recent call last):
  File "/home/myid/crumleyc/anaconda3/lib/python3.7/site-packages/distributed/protocol/core.py", line 124, in loads
    value = _deserialize(head, fs, deserializers=deserializers)
  File "/home/myid/crumleyc/anaconda3/lib/python3.7/site-packages/distributed/protocol/serialize.py", line 268, in deserialize
    return loads(header, frames)
  File "/home/myid/crumleyc/anaconda3/lib/python3.7/site-packages/distributed/protocol/serialize.py", line 54, in dask_loads
    return loads(header, frames)
  File "/home/myid/crumleyc/anaconda3/lib/python3.7/site-packages/distributed/protocol/cupy.py", line 81, in dask_deserialize_cupy_ndarray
    arr = cuda_deserialize_cupy_ndarray(header, frames)
  File "/home/myid/crumleyc/anaconda3/lib/python3.7/site-packages/distributed/protocol/cupy.py", line 65, in cuda_deserialize_cupy_ndarray
    memptr=cupy.asarray(frame).data,
  File "/home/myid/crumleyc/anaconda3/lib/python3.7/site-packages/cupy/creation/from_data.py", line 66, in asarray
    return core.array(a, dtype, False, order)
  File "cupy/core/core.pyx", line 1692, in cupy.core.core.array
  File "cupy/core/core.pyx", line 1718, in cupy.core.core.array
  File "cupy/core/core.pyx", line 2498, in cupy.core.core._convert_object_with_cuda_array_interface
TypeError: zip argument #2 must support iteration
distributed.core - ERROR - zip argument #2 must support iteration
```

**Comment by quasiben** [comment] 2020-02-29 21:28
@crumleyc which versions of dask/distributed/cupy are running ?

**Comment by crumleyc** [comment] 2020-02-29 21:31
I meant to include that:
Dask 2.11.0
Distributed 2.11.0
Cupy 6.0.0

**Comment by quasiben** [comment] 2020-02-29 21:57
Can you try upgrading to CuPy 7.1 ?

**Comment by crumleyc** [comment] 2020-02-29 23:32
Just did, 7.2. 

Now I am getting an error  saying the workers couldn't compute -- cudaRunTimeError Invalid argument. Not related to this thread, but if that sparks a lightbulb any idea? 

Thanks for your help.

**Comment by quasiben** [comment] 2020-03-01 00:09
I think there is an issue with 7.2:
https://github.com/cupy/cupy/issues/3092

Can you try 7.1?

**Comment by crumleyc** [comment] 2020-03-01 04:30
Same error. I changed the function with da.dot and it completed. I guess its a problem with matmul?

**Comment by quasiben** [comment] 2020-03-02 20:49
My initial assumption of version issues was wrong.  It's possible there is an issue with the matmul.  Can you provide a minimal reproducible example ? And I can test on my machine.

**Comment by leofang** [comment] 2020-03-03 17:47
Just a drop-by comment: if you installed CuPy from conda-forge, the error due to cupy/cupy#3092, which is now fixed, would have been `cudaErrorIllegalAddress` instead of "cudaRunTimeError Invalid argument", so it should be something else.

**Comment by crumleyc** [comment] 2020-03-03 18:58
da.dot seemed more fit for a (M,N) and (M,) operation than matmul based on the documentation.

I tried something that I am not sure why it worked, but it atleast got me passed that part of the code. I am broadcasting a 1D array to all of the workers so they can compute the dot product with the matrix S. Broadcasting the dask cupy array was fine, but the da.dot function didnt like it. It works fine when I call .compute() on the broadcasted array (176,) before calling da.dot. i.e
```
u_old = da.random.random(T).map_blocks(cp.array).compute()
_U_ = client.scatter(u_old, broadcast=True)

v = da.dot(_U_.result(),S).compute()
...
```
I mean on the datasets that I have now, I might as well just make u_old a CuPy array because they are no bigger than (500,). 
I am working on making an implementation of Rank 1 Dictionary Learning algorithm in Dask for my thesis. If anyone is interested my current repo is https://github.com/quinngroup/dr1dl-Dask. I would like to get some other eyes on this just to make sure this is done in a way that is best suited for dask. 

It seems that the problem is solved regarding this thread, I am just not sure why it didnt like taking two dask arrays as input. I can still provide a minimal example, I just dont know the best way to do that with getting the data available. 

Thank you both!!

**Comment by jakirkham** [comment] 2020-03-04 02:57
Could you please share something for `my text file`, which reproduces this or better yet generate something with random data?

(Also side note `from dask.distributed import Client()`
 should be `from dask.distributed import Client`)

**Comment by crumleyc** [comment] 2020-03-04 03:08
My txt file is a (176, 895780) or (T,P) each line is one row separated by . I use the sklearn.datasets.make_sparse_coded_signal() but im sure a generated matrix will be fine. I use two 1D matrices u_old being the one for a vector-matrix operation. u-old must be the size of the columns. The only problem i've been having is when _U_ is a dask array, it says invalid argument, but when its an actual cupy array, it works. In the example above its still a dask array and shouldn't work according to my experience. I updated the example above.

**Comment by jakirkham** [comment] 2020-03-04 04:13
Could you please attach one in a comment? GitHub let's you drag and drop them into the text space.

**Comment by crumleyc** [comment] 2020-03-04 04:44
[400_50_400_0.07_S.txt](https://github.com/dask/distributed/files/4285062/400_50_400_0.07_S.txt)
This is a small example size (400,400) i.e. T=400

**Comment by jakirkham** [comment] 2020-03-04 04:53
Thanks. What is `v`?

**Comment by crumleyc** [comment] 2020-03-04 05:02
v will be a 1D array as well the length of the columns, so in this case 400. I then grab the topk elements and turn v into a sparse array. Then I use the sparse array and broadcast it to then do a matrix-vector operation I.e da.dot(S,_V_.result()) which will result in a 1D array the size of the rows which I call u_new. Then this 1D array is used as u_old for the next iteration. I do this until the difference between u_old and u_new is below some threshold. Then I do it all again every time saving the final u and sv. This is called Rank 1 Dictionary Learning. Every time u is written to the file, it’s building the Dictionary of S row by row. Same goes for the sv, it’s building the sparse representation of S.

**Comment by crumleyc** [comment] 2020-03-04 05:12
When I was running this whole algorithm locally I was running a small example and I didn’t run into any of these problems. Now that I have access to a gpu server and the data is bigger and actually distributed, I am now seeing some issues. This being one of them. But if that’s the case, these u and v vectors don’t have to be dask arrays for this to work. I was just making them dask arrays because I figured dask would better handle everything.

**Comment by jakirkham** [comment] 2020-03-04 06:00
Yeah I worked with Dictionary Learning in a former life. 😉 Glad to see you are getting some mileage out of Dask for that.  😄

Well if you have a moment to update the code a bit so this can be run as to demonstrate the behavior you are seeing, that would be really handy. Happy to dig in a bit more once we have that. 🙂

**Comment by crumleyc** [comment] 2020-03-04 06:08
Okay. I will say, now that I am implementing cupy, i am running into a problem with that part now. I have been using pydata's sparse COO matrix, but it isn't compatible with cupy yet. I am now trying to get cupyx.scipy.sparse.coo_matrix work but its being a pain for some reason. I will post the whole algorithm but the code wont go past the first iteration once we create the sparse vector. I am currently trying to reach out to cuPy's group to understand why I am getting errors with they way I am implementing it. I will work on updating the initial post with the entire algorithm.

**Comment by jakirkham** [comment] 2020-03-04 06:38
Well there are also some changes in `master` here that change how `coo_matrix` (and other SciPy and CuPy sparse matrices) are serialized. Maybe you could give that a try? 😉

In any event it would be good to capture a complete reproducer in a comment here (even if it is not minimal). It would be good to have something to work with so we can do some debugging (and hopefully get in a fix if needed) before the upcoming release. 🙂

**Comment by crumleyc** [comment] 2020-03-04 06:40
Here is a full example of my code. I have deleted the argparse and boiled it down the the essentials
```
import cupy as cp
import numpy as np
import dask.array as da
from dask.bag import read_text
from dask.distributed import Client

def row_to_numpy(row):

    return np.array([np.float(x) for x in row.split()])

def load_data(path, chunks):

    raw_bag = read_text(path) \
                .str.strip() \
                .map(row_to_numpy)

    return da.stack(raw_bag,axis=0).map_blocks(cp.array)

def dask_normalize(dask_array):

    dask_array -= dask_array.mean()
    dask_array /= da.linalg.norm(dask_array)
    return dask_array

def sparse_normalize(coo_array):
    coo_array -= coo_array.mean()
    coo_array /= np.linalg.norm(coo_array)
    return coo_array

client = Client()


# Read the data and convert it into a Dask Array.
S = load_data(my_text_file)


#Assuming you are using the provided txt file earlier in the thread
T = 400
P = 400 
epsilon = 0.01       # convergence stopping criterion
M = 50            # dimensionality of the learned dictionary
R = int(0.07 * P)        # enforces sparsity
u_new = da.zeros(T)
v = da.zeros(P)

max_iterations = P * 10
    file_D = os.path.join('some_directory', "{}_D.txt".format('file_prefix'))
    file_z = os.path.join('some_directory', "{}_z.txt".format('file_prefix'))

    # Start the loop!
    for m in range(M):
        #Let us randomly generate a integer, broadcast that int, and create a seed.
        seed = np.random.randint(max_iterations + 1, high = 4294967295)
        _SEED_ = client.scatter(seed, broadcast=True)
        np.random.seed(_SEED_.result())

        #Create a dense random vector
        #Then subtracting off the mean an normalizing it
        #Probably should just be a cupy array
        u_old = da.random.random(T).map_blocks(cp.array)
        u_old = dask_normalize(u_old).compute()

        #Setting loop criteria
        num_iterations = 0
        delta = 2 * epsilon

        # Start the inner loop: this learns a single atom.
        while num_iterations < max_iterations and delta > epsilon:

            _U_ = client.scatter(u_old, broadcast=True)
            v = da.dot(_U_.result(),S).compute()

            #Grab the indices of the top R values in v for the sparse vector
            
            indices = cp.asnumpy(np.argpartition(v, -R)[-R:])

            #let's make the sparse vector.
            #sv = sparse.COO(indices,cp.asnumpy(v[indices]),shape=(P),sorted=False) 
            sv = coo_matrix((v[indices],(np.zeros(R),indices))
            sv = da.from_array(sv)
           
            # Broadcast the sparse vector.
            _V_ = client.scatter(sv,broadcast=True)

            # P1: Matrix-vector multiplication step. Computes u.
            u_new = da.dot(S,_V_.result()).compute()
            
            # Subtract off the mean and normalize.
            u_new = sparse_normalize(u_new)
            #I need toturn this back into a cupy array

            # Update for the next iteration.
            delta = np.linalg.norm(u_old - u_new) #Should u_old be _U_?
            u_old = u_new
            num_iterations += 1

        # Save the newly-computed u and v to the output files;
        with open(file_D, "a+") as fD:
            np.savetxt(fD, u_new, fmt = "%.6f", newline = " ")
            fD.write("\n")
        with open(file_z, "a+") as fz:
            np.savetxt(fz, sv.compute().todense(), fmt = "%.6f", newline = " ")
            fz.write("\n")


        # P4: Deflation step. Update the primary data matrix S.
        _U_ = client.scatter(u_new, broadcast=True)
        _V_ = client.scatter(sv, broadcast=True)

        #Subtracting off the outer produce of u and sv from S
        S -= da.core.blockwise(operator.mul, 'ij', _U_.result(), 'i', _V_.result(), 'j', dtype='f64')
        S.persist()
```

**Comment by jakirkham** [comment] 2020-03-04 06:47
Thanks. That should be a good starting point. 🙂

I'm guessing the code outside of the func should be dedented. Is that right?

**Comment by crumleyc** [comment] 2020-03-04 06:51
I honestly dont know what you mean by that, but I just noticed I have added any docstrings. I will make a quick description for the functions at the top. 

I pasted this out of my script, so there could be some indent issues, and for that I do apologize. I can add the if __name__ == '__main__' and indent the code. whatever you need me to.

**Comment by jakirkham** [comment] 2020-03-04 07:00
Yeah I think it just a remnant indentation from `if __name__ == '__main__':`. Should be visible if you look at `max_iterations = P * 10`. Just want to make sure I'm preserving your code structure when trying.

**Comment by jakirkham** [comment] 2020-03-04 07:01
Also wouldn't worry about docstrings. This seems good enough once we can get it to run.

**Comment by crumleyc** [comment] 2020-03-04 07:02
I went ahead and added some bad doc strings and fixed the indents!

**Comment by jakirkham** [comment] 2020-03-04 07:06
Thank you for the updates. 😄 🙏

Ran locally and getting a syntax error here:

```python
    sv = coo_matrix((v[indices],(indices,cp.zeros(R)), shape=(P,1))
```

**Comment by crumleyc** [comment] 2020-03-04 07:08
https://docs-cupy.chainer.org/en/stable/reference/generated/cupyx.scipy.sparse.coo_matrix.html#cupyx.scipy.sparse.coo_matrix 

I am trying my best to follow their documentation but this is what I can't get to work.I have tried it without specifying the shape, i just figured that it might help.

**Comment by jakirkham** [comment] 2020-03-04 07:14
Maybe [this line from our tests helps]( https://github.com/dask/distributed/blob/15550952aabfecf9e6a6bbccb7dea82d72857a4c/distributed/protocol/tests/test_cupy.py#L87 )? 🙂

Also as a side note would check out [dask-cuda]( https://github.com/rapidsai/dask-cuda#example ) for launching the cluster. It has some GPU niceties baked into, which makes things pretty easy. This is analogous to `LocalCluster`.

**Comment by crumleyc** [comment] 2020-03-04 07:25
This is the error that I get when trying (v[indices],indices):

```
Traceback (most recent call last):
  File "/home/myid/crumleyc/anaconda3/lib/python3.7/site-packages/cupyx/scipy/sparse/coo.py", line 91, in __init__
    data, (row, col) = arg1
ValueError: too many values to unpack (expected 2)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "testDL.py", line 108, in <module>
    sv = coo_matrix((v[indices],indices))
  File "/home/myid/crumleyc/anaconda3/lib/python3.7/site-packages/cupyx/scipy/sparse/coo.py", line 93, in __init__
    raise TypeError('invalid input format')
TypeError: invalid input format
```
Yes I figured I would focus on customizing the client once I got the code running. I saw that some time ago, thanks for the reminder!

**Comment by jakirkham** [comment] 2020-03-04 07:31
Yeah I don't know enough about your data to advise unfortunately.

Would take a look at this example, play with it, and try to adjust it until it matches your use case.

```python
import numpy
import cupy
from cupyx.scipy.sparse import coo_matrix

a_host = numpy.array([[0, 1, 0],
                      [2, 0, 3],
                      [0, 4, 0]], dtype=float)
a = cupy.asarray(a_host)
  
anz = a.nonzero()
acoo = coo_matrix((a[anz], anz))
```

**Comment by crumleyc** [comment] 2020-03-04 07:42
In my example, the 1D array that i need to make sparse is v. v when computed isn't sparse, but I grab the top R values and those indices to create a sparse vector. In my example a == v and indides == anz. 

```
indices = np.argpartition(v, -R)[-R:] 
#let's make the sparse vector.
sv = coo_matrix((v[indices],indices))
sv = da.from_array(sv)

**Comment by crumleyc** [comment] 2020-03-04 08:40
So i tried to use the a.nonzero() function because its output is what the coo_matrix is accepting, versus mine. It worked!!!
```
min = np.argpartition(v, -R)[-R]
v[ v < v[min] ] = 0
indices = v.nonzero()
#let's make the sparse vector.
sv = coo_matrix((v[indices],indices))
sv = da.from_array(sv)
```

**Comment by crumleyc** [comment] 2020-03-04 08:44
`u_new = da.dot(S,_V_.result()).compute()` is causing an error:
```
TypeError: 'coo_matrix' object is not subscriptable
```
I dont think this has anything to do with _V_.result() being a dask array like the first da.dot call.

**Comment by jakirkham** [comment] 2020-04-03 01:39
Sorry for the delay. Sounds like the last exception is related to issue ( https://github.com/cupy/cupy/issues/3178 ).

**Comment by crumleyc** [comment] 2020-04-21 03:18
Thank you! I guess I should post my code in cupy's ticket and close this one? Or just rename this? How can I contribute to get this working? 

I really appreciate your help with this.

**Comment by jakirkham** [comment] 2020-04-21 04:27
I don't know.

As there is already an issue about subscript support for CuPy sparse arrays, it doesn't seem like there is much to add. Maybe just subscribe to the issue? Unless you are interested on working on a CuPy PR to add that functionality 😉

It doesn't seem like a Dask issue any more. So closing this issue seems appropriate.

**Comment by crumleyc** [comment] 2020-04-21 04:39
You think it will be decent for a first project? If my time can be used creating this functionality, then yes I wouldn't mind helping on this.

**Comment by jakirkham** [comment] 2020-04-21 05:34
Guessing it's probably moderately challenging to solve. If it's interesting to you, would suggest offering to help on issue ( https://github.com/cupy/cupy/issues/3178 ) and asking for guidance. Someone should be able to point you in the right direction 🙂

**Closed** 2020-04-28 05:50 UTC
