### ISSUE TITLE
Unstable cluster after calling e.restart()

### ISSUE THREAD

**Issue by hussainsultan** [dask/distributed#338] opened 2016-06-16 02:07 UTC
After doing some work, i often clear the state of the executor by calling `restart` method. After the state clears and i resume the work with dataframes, and often times a call that should return immediately doesnt return. 

example:

```python
e.restart()

df = dd.read_csv('s3://...')
df = e.persist(df) # bokeh web UI shows that the df gets read correctly
df.head() #hangs forever
```
I am trying to figure out what is the best way to debug this, the scheduler logs do not show anything unusual. However, the bokeh web ui (/status end point), shows many tiny `head` tasks forever.

**Comment by hussainsultan** [comment] 2016-06-16 02:09
to recover from this, i have to restart the scheduler and worker processes.

**Comment by mrocklin** [comment] 2016-06-16 02:34
Can you verify that your executor.get method is set to be default

    dask.set_options(get=e.get)

**Comment by mrocklin** [comment] 2016-06-16 02:46
The many tiny `head` tasks seem quite odd

**Comment by hussainsultan** [comment] 2016-06-16 02:47
`dask.set_options(get=e.get)` is set. Also i thought that was the new default and we didnt need it anymore. is that correct?

**Comment by mrocklin** [comment] 2016-06-16 02:50
I chickened out.  It's all set up to go, but for now the default is not to turn it on by default.  There is a keyword argument in the Executor for now:

    e = Executor('scheduler:8786', set_as_default=True)

I intend to play with it myself for a while before changing behavior globally

**Comment by hussainsultan** [comment] 2016-06-16 02:55
ahh. no worries. i will let you know how it feels as well.

**Comment by mrocklin** [comment] 2016-06-16 02:58
I can get things to misbehave if I first use the old dataframe with the old futures in computations after the `restart`.  This seems to muck things up so that other correct things that happen afterwards fail.  I'm not yet unable to make head fail after a restart without doing something like this though.

```python
In [53]: df = dd.demo.make_timeseries('2000', '2001', {'x': float, 'y': float}, '1s', '1d')

In [54]: df.head()
Out[54]: 
                            x         y
2000-01-01 00:00:00 -0.113429 -0.726942
2000-01-01 00:00:01  0.981856 -0.140475
2000-01-01 00:00:02 -0.935046  0.581248
2000-01-01 00:00:03 -0.467437  0.842126
2000-01-01 00:00:04 -0.985084 -0.131019

In [55]: df = e.persist(df)

In [56]: df.head()
Out[56]: 
                            x         y
2000-01-01 00:00:00 -0.113429 -0.726942
2000-01-01 00:00:01  0.981856 -0.140475
2000-01-01 00:00:02 -0.935046  0.581248
2000-01-01 00:00:03 -0.467437  0.842126
2000-01-01 00:00:04 -0.985084 -0.131019

In [57]: e.restart()
distributed.executor - INFO - Receive restart signal from scheduler
Out[57]: <Executor: scheduler=127.0.0.1:8786 processes=4 cores=32>

In [58]: df.head()  #  oops, this was a bad choice
KeyError: "('head-5-make-timeseries-8de07ca483bf46648bf05c6d923ecadd', 0)"

In [59]: df = e.persist(df)  # also a bad choice

In [60]: df = dd.demo.make_timeseries('2000', '2001', {'x': float, 'y': float}, '1s', '1d')

In [61]: df = e.persist(df)  # doesn't work now

In [62]: df.head()  # this hangs
```

**Comment by hussainsultan** [comment] 2016-06-16 02:59
how is bokeh web ui behaving?

**Comment by mrocklin** [comment] 2016-06-16 03:01
No movement.

**Comment by hussainsultan** [comment] 2016-06-16 03:01
in my case,  i see this happen after successful `e.persist(df)` that i can confirm from the bokeh web ui that all tasks completed successfuly and the subsequent head() just goes wonky

**Comment by mrocklin** [comment] 2016-06-16 03:04
Are you able to reproduce the issue, perhaps with `dd.demo.make_timeseries` as shown above?  If you can provide a sequence of events that causes the failure that would help me in identifying it.

**Comment by hussainsultan** [comment] 2016-06-16 03:05
yea let me try it again. one moment....

**Comment by hussainsultan** [comment] 2016-06-16 03:17
i couldnt reliably reproduce but the above sequence got me their again on a really large data. Could their be some memory thing going on here as well? like some memory didnt get appropriately freed up between restarts and one of the workers ran out of memory? hmmm

**Comment by mrocklin** [comment] 2016-06-16 03:19
The worker processes are literally being killed and restarted.  The memory space of the worker process is definitely being completely cleaned out.  That doesn't mean that we're not running into space issues though.  

The memory percentage of each host is listed in the table at the bottom of the web UI.

**Comment by mrocklin** [comment] 2016-06-16 03:19
You should be able to tweak the date range (2005 -> 2050) or sampling frequency ('1s' -> '10ms') to increase the scale of the demo dataset

**Comment by hussainsultan** [comment] 2016-06-16 19:28
I can confirm that this issue doesn't exist with demo data and is probably just apply to `s3` based tasks. 
I can replicate this with s3  `read_csv` tasks where after a restart doing it again will create many heads. I also tried doing it with single threaded configuration with same result.

**Comment by mrocklin** [comment] 2016-06-16 19:53
Thanks for trying out single-threaded execution.

We did end up finding a flaw with s3fs and forked processes in https://github.com/dask/dask/issues/1292 but this may or may not be related.

I would be curious to see the scheduler and worker logs during the repeated head calls.  This might be more interesting under DEBUG level verbosity.

**Comment by mrocklin** [comment] 2016-06-23 16:24
FWIW https://github.com/dask/distributed/pull/350 identified and fixed an issue that arose during a restart.  There is a small chance that it was related.

**Comment by mrocklin** [comment] 2016-08-12 19:47
The scheduler has been significantly reworked since this issue arose.  Does the problem still persist?

**Comment by mrocklin** [comment] 2016-08-17 22:31
Closing for now under the assumption that the scheduler refactor resolved this.  Please reopen if the problem persists.

**Closed by mrocklin** 2016-08-17 22:31 UTC
