### ISSUE TITLE
script creating LocalCluster never stops

### ISSUE THREAD

**Issue by dchudz** [dask/distributed#5726] opened 2022-01-28 13:46 UTC
**What happened**: A short Python script that creates a LocalCluster never finishes, but instead outputs exceptions forever.

**What you expected to happen**: I expected the script to do something, and then stop.

**Minimal Complete Verifiable Example**:

`hi.py`:

```python
from dask.distributed import LocalCluster

lc = LocalCluster()
```

Then running `python hi.py` in my terminal produces:

<details>
<summary>Details</summary>
<pre>
python hi.py
/Users/davidchudzicki/miniconda3/envs/coiled/lib/python3.8/site-packages/distributed/node.py:160: UserWarning: Port 8787 is already in use.
Perhaps you already have a cluster running?
Hosting the HTTP server on port 51043 instead
  warnings.warn(
/Users/davidchudzicki/miniconda3/envs/coiled/lib/python3.8/site-packages/distributed/node.py:160: UserWarning: Port 8787 is already in use.
Perhaps you already have a cluster running?
Hosting the HTTP server on port 51044 instead
  warnings.warn(
/Users/davidchudzicki/miniconda3/envs/coiled/lib/python3.8/site-packages/distributed/node.py:160: UserWarning: Port 8787 is already in use.
Perhaps you already have a cluster running?
Hosting the HTTP server on port 51045 instead
  warnings.warn(
/Users/davidchudzicki/miniconda3/envs/coiled/lib/python3.8/site-packages/distributed/node.py:160: UserWarning: Port 8787 is already in use.
Perhaps you already have a cluster running?
Hosting the HTTP server on port 51046 instead
  warnings.warn(
Task exception was never retrieved
future: <Task finished name='Task-21' coro=<_wrap_awaitable() done, defined at /Users/davidchudzicki/miniconda3/envs/coiled/lib/python3.8/asyncio/tasks.py:688> exception=RuntimeError('\n        An attempt has been made to start a new process before the\n        current process has finished its bootstrapping phase.\n\n        This probably means that you are not using fork to start your\n        child processes and you have forgotten to use the proper idiom\n        in the main module:\n\n            if __name__ == \'__main__\':\n                freeze_support()\n                ...\n\n        The "freeze_support()" line can be omitted if the program\n        is not going to be frozen to produce an executable.')>
Traceback (most recent call last):
  File "/Users/davidchudzicki/miniconda3/envs/coiled/lib/python3.8/asyncio/tasks.py", line 695, in _wrap_awaitable
    return (yield from awaitable.__await__())
  File "/Users/davidchudzicki/miniconda3/envs/coiled/lib/python3.8/site-packages/distributed/core.py", line 283, in _
    await self.start()
  File "/Users/davidchudzicki/miniconda3/envs/coiled/lib/python3.8/site-packages/distributed/nanny.py", line 338, in start
    response = await self.instantiate()
  File "/Users/davidchudzicki/miniconda3/envs/coiled/lib/python3.8/site-packages/distributed/nanny.py", line 421, in instantiate
    result = await self.process.start()
  File "/Users/davidchudzicki/miniconda3/envs/coiled/lib/python3.8/site-packages/distributed/nanny.py", line 691, in start
    await self.process.start()
  File "/Users/davidchudzicki/miniconda3/envs/coiled/lib/python3.8/site-packages/distributed/process.py", line 32, in _call_and_set_future
    res = func(*args, **kwargs)
  File "/Users/davidchudzicki/miniconda3/envs/coiled/lib/python3.8/site-packages/distributed/process.py", line 186, in _start
    process.start()
  File "/Users/davidchudzicki/miniconda3/envs/coiled/lib/python3.8/multiprocessing/process.py", line 121, in start
    self._popen = self._Popen(self)
  File "/Users/davidchudzicki/miniconda3/envs/coiled/lib/python3.8/multiprocessing/context.py", line 284, in _Popen
    return Popen(process_obj)
  File "/Users/davidchudzicki/miniconda3/envs/coiled/lib/python3.8/multiprocessing/popen_spawn_posix.py", line 32, in __init__
    super().__init__(process_obj)
  File "/Users/davidchudzicki/miniconda3/envs/coiled/lib/python3.8/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/Users/davidchudzicki/miniconda3/envs/coiled/lib/python3.8/multiprocessing/popen_spawn_posix.py", line 42, in _launch
    prep_data = spawn.get_preparation_data(process_obj._name)
  File "/Users/davidchudzicki/miniconda3/envs/coiled/lib/python3.8/multiprocessing/spawn.py", line 154, in get_preparation_data
    _check_not_importing_main()
  File "/Users/davidchudzicki/miniconda3/envs/coiled/lib/python3.8/multiprocessing/spawn.py", line 134, in _check_not_importing_main
    raise RuntimeError('''
RuntimeError:
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.
Task exception was never retrieved
future: <Task finished name='Task-19' coro=<_wrap_awaitable() done, defined at /Users/davidchudzicki/miniconda3/envs/coiled/lib/python3.8/asyncio/tasks.py:688> exception=RuntimeError('\n        An attempt has been made to start a new process before the\n        current process has finished its bootstrapping phase.\n\n        This probably means that you are not using fork to start your\n        child processes and you have forgotten to use the proper idiom\n        in the main module:\n\n            if __name__ == \'__main__\':\n                freeze_support()\n                ...\n\n        The "freeze_support()" line can be omitted if the program\n        is not going to be frozen to produce an executable.')>
Traceback (most recent call last):
  File "/Users/davidchudzicki/miniconda3/envs/coiled/lib/python3.8/asyncio/tasks.py", line 695, in _wrap_awaitable
    return (yield from awaitable.__await__())
  File "/Users/davidchudzicki/miniconda3/envs/coiled/lib/python3.8/site-packages/distributed/core.py", line 283, in _
    await self.start()
  File "/Users/davidchudzicki/miniconda3/envs/coiled/lib/python3.8/site-packages/distributed/nanny.py", line 338, in start
    response = await self.instantiate()
  File "/Users/davidchudzicki/miniconda3/envs/coiled/lib/python3.8/site-packages/distributed/nanny.py", line 421, in instantiate
    result = await self.process.start()
  File "/Users/davidchudzicki/miniconda3/envs/coiled/lib/python3.8/site-packages/distributed/nanny.py", line 691, in start
    await self.process.start()
  File "/Users/davidchudzicki/miniconda3/envs/coiled/lib/python3.8/site-packages/distributed/process.py", line 32, in _call_and_set_future
    res = func(*args, **kwargs)
  File "/Users/davidchudzicki/miniconda3/envs/coiled/lib/python3.8/site-packages/distributed/process.py", line 186, in _start
    process.start()
  File "/Users/davidchudzicki/miniconda3/envs/coiled/lib/python3.8/multiprocessing/process.py", line 121, in start
    self._popen = self._Popen(self)
  File "/Users/davidchudzicki/miniconda3/envs/coiled/lib/python3.8/multiprocessing/context.py", line 284, in _Popen
    return Popen(process_obj)
  File "/Users/davidchudzicki/miniconda3/envs/coiled/lib/python3.8/multiprocessing/popen_spawn_posix.py", line 32, in __init__
    super().__init__(process_obj)
  File "/Users/davidchudzicki/miniconda3/envs/coiled/lib/python3.8/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/Users/davidchudzicki/miniconda3/envs/coiled/lib/python3.8/multiprocessing/popen_spawn_posix.py", line 42, in _launch
    prep_data = spawn.get_preparation_data(process_obj._name)
  File "/Users/davidchudzicki/miniconda3/envs/coiled/lib/python3.8/multiprocessing/spawn.py", line 154, in get_preparation_data
    _check_not_importing_main()
  File "/Users/davidchudzicki/miniconda3/envs/coiled/lib/python3.8/multiprocessing/spawn.py", line 134, in _check_not_importing_main
    raise RuntimeError('''
RuntimeError:
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.
Task exception was never retrieved
future: <Task finished name='Task-18' coro=<_wrap_awaitable() done, defined at /Users/davidchudzicki/miniconda3/envs/coiled/lib/python3.8/asyncio/tasks.py:688> exception=RuntimeError('\n        An attempt has been made to start a new process before the\n        current process has finished its bootstrapping phase.\n\n        This probably means that you are not using fork to start your\n        child processes and you have forgotten to use the proper idiom\n        in the main module:\n\n            if __name__ == \'__main__\':\n                freeze_support()\n                ...\n\n        The "freeze_support()" line can be omitted if the program\n        is not going to be frozen to produce an executable.')>
Traceback (most recent call last):
  File "/Users/davidchudzicki/miniconda3/envs/coiled/lib/python3.8/asyncio/tasks.py", line 695, in _wrap_awaitable
    return (yield from awaitable.__await__())
  File "/Users/davidchudzicki/miniconda3/envs/coiled/lib/python3.8/site-packages/distributed/core.py", line 283, in _
    await self.start()
  File "/Users/davidchudzicki/miniconda3/envs/coiled/lib/python3.8/site-packages/distributed/nanny.py", line 338, in start
    response = await self.instantiate()
  File "/Users/davidchudzicki/miniconda3/envs/coiled/lib/python3.8/site-packages/distributed/nanny.py", line 421, in instantiate
    result = await self.process.start()
  File "/Users/davidchudzicki/miniconda3/envs/coiled/lib/python3.8/site-packages/distributed/nanny.py", line 691, in start
    await self.process.start()
  File "/Users/davidchudzicki/miniconda3/envs/coiled/lib/python3.8/site-packages/distributed/process.py", line 32, in _call_and_set_future
    res = func(*args, **kwargs)
  File "/Users/davidchudzicki/miniconda3/envs/coiled/lib/python3.8/site-packages/distributed/process.py", line 186, in _start
    process.start()
  File "/Users/davidchudzicki/miniconda3/envs/coiled/lib/python3.8/multiprocessing/process.py", line 121, in start
    self._popen = self._Popen(self)
  File "/Users/davidchudzicki/miniconda3/envs/coiled/lib/python3.8/multiprocessing/context.py", line 284, in _Popen
    return Popen(process_obj)
  File "/Users/davidchudzicki/miniconda3/envs/coiled/lib/python3.8/multiprocessing/popen_spawn_posix.py", line 32, in __init__
    super().__init__(process_obj)
  File "/Users/davidchudzicki/miniconda3/envs/coiled/lib/python3.8/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/Users/davidchudzicki/miniconda3/envs/coiled/lib/python3.8/multiprocessing/popen_spawn_posix.py", line 42, in _launch
    prep_data = spawn.get_preparation_data(process_obj._name)
  File "/Users/davidchudzicki/miniconda3/envs/coiled/lib/python3.8/multiprocessing/spawn.py", line 154, in get_preparation_data
    _check_not_importing_main()
  File "/Users/davidchudzicki/miniconda3/envs/coiled/lib/python3.8/multiprocessing/spawn.py", line 134, in _check_not_importing_main
    raise RuntimeError('''
RuntimeError:
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.
Task exception was never retrieved
future: <Task finished name='Task-20' coro=<_wrap_awaitable() done, defined at /Users/davidchudzicki/miniconda3/envs/coiled/lib/python3.8/asyncio/tasks.py:688> exception=RuntimeError('\n        An attempt has been made to start a new process before the\n        current process has finished its bootstrapping phase.\n\n        This probably means that you are not using fork to start your\n        child processes and you have forgotten to use the proper idiom\n        in the main module:\n\n            if __name__ == \'__main__\':\n                freeze_support()\n                ...\n\n        The "freeze_support()" line can be omitted if the program\n        is not going to be frozen to produce an executable.')>
Traceback (most recent call last):
  File "/Users/davidchudzicki/miniconda3/envs/coiled/lib/python3.8/asyncio/tasks.py", line 695, in _wrap_awaitable
    return (yield from awaitable.__await__())
  File "/Users/davidchudzicki/miniconda3/envs/coiled/lib/python3.8/site-packages/distributed/core.py", line 283, in _
    await self.start()
  File "/Users/davidchudzicki/miniconda3/envs/coiled/lib/python3.8/site-packages/distributed/nanny.py", line 338, in start
    response = await self.instantiate()
  File "/Users/davidchudzicki/miniconda3/envs/coiled/lib/python3.8/site-packages/distributed/nanny.py", line 421, in instantiate
    result = await self.process.start()
  File "/Users/davidchudzicki/miniconda3/envs/coiled/lib/python3.8/site-packages/distributed/nanny.py", line 691, in start
    await self.process.start()
  File "/Users/davidchudzicki/miniconda3/envs/coiled/lib/python3.8/site-packages/distributed/process.py", line 32, in _call_and_set_future
    res = func(*args, **kwargs)
  File "/Users/davidchudzicki/miniconda3/envs/coiled/lib/python3.8/site-packages/distributed/process.py", line 186, in _start
    process.start()
  File "/Users/davidchudzicki/miniconda3/envs/coiled/lib/python3.8/multiprocessing/process.py", line 121, in start
    self._popen = self._Popen(self)
  File "/Users/davidchudzicki/miniconda3/envs/coiled/lib/python3.8/multiprocessing/context.py", line 284, in _Popen
    return Popen(process_obj)
  File "/Users/davidchudzicki/miniconda3/envs/coiled/lib/python3.8/multiprocessing/popen_spawn_posix.py", line 32, in __init__
    super().__init__(process_obj)
  File "/Users/davidchudzicki/miniconda3/envs/coiled/lib/python3.8/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/Users/davidchudzicki/miniconda3/envs/coiled/lib/python3.8/multiprocessing/popen_spawn_posix.py", line 42, in _launch
    prep_data = spawn.get_preparation_data(process_obj._name)
  File "/Users/davidchudzicki/miniconda3/envs/coiled/lib/python3.8/multiprocessing/spawn.py", line 154, in get_preparation_data
    _check_not_importing_main()
  File "/Users/davidchudzicki/miniconda3/envs/coiled/lib/python3.8/multiprocessing/spawn.py", line 134, in _check_not_importing_main
    raise RuntimeError('''
RuntimeError:
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/davidchudzicki/miniconda3/envs/coiled/lib/python3.8/multiprocessing/spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "/Users/davidchudzicki/miniconda3/envs/coiled/lib/python3.8/multiprocessing/spawn.py", line 125, in _main
    prepare(preparation_data)
  File "/Users/davidchudzicki/miniconda3/envs/coiled/lib/python3.8/multiprocessing/spawn.py", line 236, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "/Users/davidchudzicki/miniconda3/envs/coiled/lib/python3.8/multiprocessing/spawn.py", line 287, in _fixup_main_from_path
    main_content = runpy.run_path(main_path,
  File "/Users/davidchudzicki/miniconda3/envs/coiled/lib/python3.8/runpy.py", line 265, in run_path
Task exception was never retrieved
future: <Task finished name='Task-21' coro=<_wrap_awaitable() done, defined at /Users/davidchudzicki/miniconda3/envs/coiled/lib/python3.8/asyncio/tasks.py:688> exception=RuntimeError('\n        An attempt has been made to start a new process before the\n        current process has finished its bootstrapping phase.\n\n        This probably means that you are not using fork to start your\n        child processes and you have forgotten to use the proper idiom\n        in the main module:\n\n            if __name__ == \'__main__\':\n                freeze_support()\n                ...\n\n        The "freeze_support()" line can be omitted if the program\n        is not going to be frozen to produce an executable.')>
Traceback (most recent call last):
  File "/Users/davidchudzicki/miniconda3/envs/coiled/lib/python3.8/asyncio/tasks.py", line 695, in _wrap_awaitable
    return (yield from awaitable.__await__())
  File "/Users/davidchudzicki/miniconda3/envs/coiled/lib/python3.8/site-packages/distributed/core.py", line 283, in _
    await self.start()
  File "/Users/davidchudzicki/miniconda3/envs/coiled/lib/python3.8/site-packages/distributed/nanny.py", line 338, in start
    response = await self.instantiate()
  File "/Users/davidchudzicki/miniconda3/envs/coiled/lib/python3.8/site-packages/distributed/nanny.py", line 421, in instantiate
    result = await self.process.start()
  File "/Users/davidchudzicki/miniconda3/envs/coiled/lib/python3.8/site-packages/distributed/nanny.py", line 691, in start
    await self.process.start()
  File "/Users/davidchudzicki/miniconda3/envs/coiled/lib/python3.8/site-packages/distributed/process.py", line 32, in _call_and_set_future
    res = func(*args, **kwargs)
  File "/Users/davidchudzicki/miniconda3/envs/coiled/lib/python3.8/site-packages/distributed/process.py", line 186, in _start
    process.start()
  File "/Users/davidchudzicki/miniconda3/envs/coiled/lib/python3.8/multiprocessing/process.py", line 121, in start
    self._popen =     return _run_module_code(code, init_globals, run_name,
self._Popen(self)
  File "/Users/davidchudzicki/miniconda3/envs/coiled/lib/python3.8/multiprocessing/context.py", line 284, in _Popen
    return Popen(process_obj)
  File "/Users/davidchudzicki/miniconda3/envs/coiled/lib/python3.8/multiprocessing/popen_spawn_posix.py", line 32, in __init__
    super().__init__(process_obj)
  File "/Users/davidchudzicki/miniconda3/envs/coiled/lib/python3.8/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/Users/davidchudzicki/miniconda3/envs/coiled/lib/python3.8/multiprocessing/popen_spawn_posix.py", line 42, in _launch
    prep_data = spawn.get_preparation_data(process_obj._name)
  File "/Users/davidchudzicki/miniconda3/envs/coiled/lib/python3.8/multiprocessing/spawn.py", line 154, in get_preparation_data
    _check_not_importing_main()
  File "/Users/davidchudzicki/miniconda3/envs/coiled/lib/python3.8/multiprocessing/spawn.py", line 134, in _check_not_importing_main
    raise RuntimeError('''
RuntimeError:
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.
  File "/Users/davidchudzicki/miniconda3/envs/coiled/lib/python3.8/runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/Users/davidchudzicki/miniconda3/envs/coiled/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Users/davidchudzicki/cloud/hi.py", line 3, in <module>
    lc = LocalCluster()
  File "/Users/davidchudzicki/miniconda3/envs/coiled/lib/python3.8/site-packages/distributed/deploy/local.py", line 235, in __init__
Task exception was never retrieved
future: <Task finished name='Task-19' coro=<_wrap_awaitable() done, defined at /Users/davidchudzicki/miniconda3/envs/coiled/lib/python3.8/asyncio/tasks.py:688> exception=RuntimeError('\n        An attempt has been made to start a new process before the\n        current process has finished its bootstrapping phase.\n\n        This probably means that you are not using fork to start your\n        child processes and you have forgotten to use the proper idiom\n        in the main module:\n\n            if __name__ == \'__main__\':\n                freeze_support()\n                ...\n\n        The "freeze_support()" line can be omitted if the program\n        is not going to be frozen to produce an executable.')>
Traceback (most recent call last):
  File "/Users/davidchudzicki/miniconda3/envs/coiled/lib/python3.8/asyncio/tasks.py", line 695, in _wrap_awaitable
    return (yield from awaitable.__await__())
  File "/Users/davidchudzicki/miniconda3/envs/coiled/lib/python3.8/site-packages/distributed/core.py", line 283, in _
    await self.start()
  File "/Users/davidchudzicki/miniconda3/envs/coiled/lib/python3.8/site-packages/distributed/nanny.py", line 338, in start
    response = await self.instantiate()
  File "/Users/davidchudzicki/miniconda3/envs/coiled/lib/python3.8/site-packages/distributed/nanny.py", line 421, in instantiate
    result = await self.process.start()
  File "/Users/davidchudzicki/miniconda3/envs/coiled/lib/python3.8/site-packages/distributed/nanny.py", line 691, in start
    await self.process.start()
  File "/Users/davidchudzicki/miniconda3/envs/coiled/lib/python3.8/site-packages/distributed/process.py", line 32, in _call_and_set_future
    res = func(*args, **kwargs)
  File "/Users/davidchudzicki/miniconda3/envs/coiled/lib/python3.8/site-packages/distributed/process.py", line 186, in _start
    process.start()
  File "/Users/davidchudzicki/miniconda3/envs/coiled/lib/python3.8/multiprocessing/process.py", line 121, in start
    self._popen = self._Popen(self)
  File "/Users/davidchudzicki/miniconda3/envs/coiled/lib/python3.8/multiprocessing/context.py", line 284, in _Popen
    return Popen(process_obj)
  File "/Users/davidchudzicki/miniconda3/envs/coiled/lib/python3.8/multiprocessing/popen_spawn_posix.py", line 32, in __init__
    super().__init__(process_obj)
  File "/Users/davidchudzicki/miniconda3/envs/coiled/lib/python3.8/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/Users/davidchudzicki/miniconda3/envs/coiled/lib/python3.8/multiprocessing/popen_spawn_posix.py", line 42, in _launch
    prep_data = spawn.get_preparation_data(process_obj._name)
  File "/Users/davidchudzicki/miniconda3/envs/coiled/lib/python3.8/multiprocessing/spawn.py", line 154, in get_preparation_data
    _check_not_importing_main()
  File "/Users/davidchudzicki/miniconda3/envs/coiled/lib/python3.8/multiprocessing/spawn.py", line 134, in _check_not_importing_main
    raise RuntimeError('''
RuntimeError:
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.
Task exception was never retrieved
future: <Task finished name='Task-20' coro=<_wrap_awaitable() done, defined at /Users/davidchudzicki/miniconda3/envs/coiled/lib/python3.8/asyncio/tasks.py:688> exception=RuntimeError('\n        An attempt has been made to start a new process before the\n        current process has finished its bootstrapping phase.\n\n        This probably means that you are not using fork to start your\n        child processes and you have forgotten to use the proper idiom\n        in the main module:\n\n            if __name__ == \'__main__\':\n                freeze_support()\n                ...\n\n        The "freeze_support()" line can be omitted if the program\n        is not going to be frozen to produce an executable.')>
Traceback (most recent call last):
  File "/Users/davidchudzicki/miniconda3/envs/coiled/lib/python3.8/asyncio/tasks.py", line 695, in _wrap_awaitable
    return (yield from awaitable.__await__())
  File "/Users/davidchudzicki/miniconda3/envs/coiled/lib/python3.8/site-packages/distributed/core.py", line 283, in _
    await self.start()
  File "/Users/davidchudzicki/miniconda3/envs/coiled/lib/python3.8/site-packages/distributed/nanny.py", line 338, in start
    response = await self.instantiate()
  File "/Users/davidchudzicki/miniconda3/envs/coiled/lib/python3.8/site-packages/distributed/nanny.py", line 421, in instantiate
    result = await self.process.start()
  File "/Users/davidchudzicki/miniconda3/envs/coiled/lib/python3.8/site-packages/distributed/nanny.py", line 691, in start
    await self.process.start()
  File "/Users/davidchudzicki/miniconda3/envs/coiled/lib/python3.8/site-packages/distributed/process.py", line 32, in _call_and_set_future
    res = func(*args, **kwargs)
  File "/Users/davidchudzicki/miniconda3/envs/coiled/lib/python3.8/site-packages/distributed/process.py", line 186, in _start
    process.start()
  File "/Users/davidchudzicki/miniconda3/envs/coiled/lib/python3.8/multiprocessing/process.py", line 121, in start
    self._popen = self._Popen(self)
  File "/Users/davidchudzicki/miniconda3/envs/coiled/lib/python3.8/multiprocessing/context.py", line 284, in _Popen
    return Popen(process_obj)
  File "/Users/davidchudzicki/miniconda3/envs/coiled/lib/python3.8/multiprocessing/popen_spawn_posix.py", line 32, in __init__
    super().__init__(process_obj)
  File "/Users/davidchudzicki/miniconda3/envs/coiled/lib/python3.8/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/Users/davidchudzicki/miniconda3/envs/coiled/lib/python3.8/multiprocessing/popen_spawn_posix.py", line 42, in _launch
    prep_data = spawn.get_preparation_data(process_obj._name)
  File "/Users/davidchudzicki/miniconda3/envs/coiled/lib/python3.8/multiprocessing/spawn.py", line 154, in get_preparation_data
    _check_not_importing_main()
  File "/Users/davidchudzicki/miniconda3/envs/coiled/lib/python3.8/multiprocessing/spawn.py", line 134, in _check_not_importing_main
    raise RuntimeError('''
RuntimeError:
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.
    super().__init__(
  File "/Users/davidchudzicki/miniconda3/envs/coiled/lib/python3.8/site-packages/distributed/deploy/spec.py", line 276, in __init__
    self.sync(self._correct_state)
  File "/Users/davidchudzicki/miniconda3/envs/coiled/lib/python3.8/site-packages/distributed/deploy/cluster.py", line 258, in sync
Task exception was never retrieved
future: <Task finished name='Task-18' coro=<_wrap_awaitable() done, defined at /Users/davidchudzicki/miniconda3/envs/coiled/lib/python3.8/asyncio/tasks.py:688> exception=RuntimeError('\n        An attempt has been made to start a new process before the\n        current process has finished its bootstrapping phase.\n\n        This probably means that you are not using fork to start your\n        child processes and you have forgotten to use the proper idiom\n        in the main module:\n\n            if __name__ == \'__main__\':\n                freeze_support()\n                ...\n\n        The "freeze_support()" line can be omitted if the program\n        is not going to be frozen to produce an executable.')>

</pre>

</details>

(That's just the first few hundred lines.)

**Anything else we need to know?**: nope

**Environment**:

- Dask version: 2022.1.0
- Python version: 3.8.12
- Operating System: MacOS 11.6
- Install method (conda, pip, source): pip

**Comment by jrbourbeau** [comment] 2022-01-31 22:48
Thanks for raising an issue @dchudz! This behavior can be avoided by guarding your `LocalCluster()` call in a `if __name__ == "__main__":` block (there's a nice explanation here https://github.com/dask/distributed/issues/2520#issuecomment-835830897). It would be great if we could raise a more informative/shorter message in this case -- see https://github.com/dask/distributed/issues/2708 for a discussion around this. Closing as a duplicate of https://github.com/dask/distributed/issues/2708

**Closed by jrbourbeau** 2022-01-31 22:48 UTC

**Comment by dchudz** [comment] 2022-01-31 23:03
oh, sorry for not catching that this is a duplicate!

**Comment by jrbourbeau** [comment] 2022-02-01 16:28
No worries at all 👍
